<?php $cookie = Mage::getSingleton('core/cookie');?>
<?php if($cookie->get("store_new_code")):
   $store_value = $cookie->get("store_new_code");
   $url = Mage::helper("page/switch")->getPreviousUrl();
   Mage::app()->getResponse()
    ->setRedirect(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true ).$store_value.$url, 302)
    ->sendResponse();
?>
<?php else:?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Online Shopping: Dresses, Shoes & Accessories | eLabelz</title>
    <meta name="description" content="The Coolest Fashion Online Mall for Men, Women and Kids. Shop for Dresses, Shoes, Bags &amp; Accessories with Free Next Day Shipping 14 Days Exchange Policy">
    <meta id="viewportmeta" name=viewport content="width=device-width, initial-scale=1">
<style type="text/css" media="screen">
        *{-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;}
        html,body,.container{margin:0;padding:0;/* height:100%; */min-height:100%;clear:both;}
        html{background-image:url("<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ); ?>images/desktop-bg.jpg");background-size:cover;background-position:center center;background-repeat:no-repeat;}
        .container{padding:0;clear:both;}
        .container .container{padding:20px;margin:10px auto;border:1px solid #000; display: inline-block;}
        .lander-page,.data-table{border-collapse:collapse;border:1px solid #000;height:100%;width:100%;}
        .lander-page{border:0;}
        .data-table{height:400px;max-width:600px;}
        .lander-page .logo{height:auto;text-align:center;vertical-align:middle;padding:20px;}
        .lander-page .logo a,.data-table td a{display:inline-block;}
        .lander-page .logo a .logo-class{width:auto;height:166px;max-height:120px;max-width:100%;}
        .lander-page .middle{width:40%;vertical-align:top;}
        .data-table{background:#000;color:#fff;}
        .data-table td{text-align:left;vertical-align:middle;padding:20px;border-bottom:1px solid #525252;width:33%;}
        .data-table td[colspan="3"]{width:100%;text-align:center;}
        .flagsimg{display:inline-block;margin-right:1%;vertical-align:top;width:32%;max-width: 56px;}
        .flagslinks{display:inline-block;padding-top:0px;vertical-align:top;width:63%;line-height: 16px;}
        .data-table td .flagslinks a{display:block;}
        .flagsimg img { max-width:100%;width:100%;} 
        .flagslinks img { max-width: 100%; width:auto; }
        .data-table td.uk .flagslinks a,.data-table td.us .flagslinks a,.data-table td.int .flagslinks a{padding-top:9px;padding-left:2px;}
        .data-table td.int .flagslinks a{padding-top:7px;}
        .data-table td.int .flagslinks a img{max-width:100%;}
        .divwidth{width:170px;margin:0;clear:both;display:block;text-align:left;}
        .flagslinks{padding-top:0;}
        .flagslinks a.en img{max-width:80%;max-height:11px;}
        .data-table tr.last td{border:0;}
        .divouter  { text-align: center; }

        @media (min-width:1281px){
            .data-table{height:100%;}
            .container .container{max-height:100%;}
            .data-table td:nth-child(1){padding-left:30px;}
        }
        @media (min-width:993px) and (max-width:1280px){
            .lander-page .logo{padding:20px 15px 15px;}
            .container .container{margin-top:0;padding:15px;}
        }
        @media (max-width:992px){
            .lander-page .left,.lander-page .right{width:5%;}
            .container{padding:0px;}
            .data-table td:nth-child(1){padding-left:30px;}
        }
        @media (min-width:768px) and (max-width:992px){
            .divouter {width:100%;margin:auto;text-align:center;clear:both;}
            .innerTable {width: 100%; max-width: 100%; }
            .outeTable tr.logo { height:  100px; }
            a.logo { margin: 40px 0; }
            .flagsimg img { max-width: none !important; }
            .flagsimg { max-width: none; width: 35%; }
            .flagslinks { width: 60%; }
        }
        @media (max-width:767px){
            .lander-page .middle{width:100%;}
            .inner_table tr { height: 100px; }
            .data-table td{display:inline-block;width:50%;padding:20px;}
        }
        @media (max-width:450px){
            .container .container{padding:10px;margin:0px auto;}
            .data-table td:nth-child(1){padding-left:20px;}
            .data-table td{padding:20px 0;}
            .data-table tr td.head{padding-top:15px;}
            .data-table tr td.head img{max-width:80%;}
        }
        @media (max-width:359px){
            .data-table tr td .divwidth{margin:0 auto;padding-left:10px;}
            .data-table td{display:block;width:100%;padding:10px;border-bottom:1px solid #7e7e7e;}
            .data-table tr.last td{border-bottom:1px solid #7e7e7e;}
            .lander-page .logo a .logo-class{max-width:80%;height:auto;}
        }
        @media only screen and (orientation: portrait) {
        html{background-image:url("<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ); ?>images/mobile-portrait-bg.jpg");}
        }
</style>
</head>
<body>
      <div class="container outertContainer">
        <table width="100%" height="100%" border="0" class="lander-page outeTable">
            <tr class="logo">
                <td class="logo">
                    <a href="http://elabelz.com/" class="logo">
                        <img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/logos-white.png" class="logo-class" width="341" height="166">
                    </a>
                </td>
            </tr>
            <tr>
            <td class="middle" width="100%">
                <div class="divouter ">
                    <div class="container innerContainer">
                        <table width="100%" border="0" class="data-table innerTable">
                            <tr>
                                <td colspan="3" class="head"><img title="Choose Your Location" src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/head-txt.png" alt="Choose Your Location"></td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url = Mage::helper("page/switch")->getPreviousUrl();
                                            $url = "/";  
                                            $url_ae = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_ae".$url ?>
                                            <a href="<?php echo $url_ae ?>">
                                                <img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/uae_logo.png" alt="">
                                            </a>
                                        </div>
                                        <div class="flagslinks">
                                            <?php $url_aear = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."ar_ae".$url ?>
                                            <a href="<?php echo $url_aear ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/uae_arabic.png" alt=""> </a>
                                            <a class="en" href="<?php echo $url_ae ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/uae_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="divwidth sa">
                                        <div class="flagsimg">
                                            <?php $url_sa = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_sa".$url ?>
                                            <a href="<?php echo $url_sa ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/saudi_logo.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <?php $url_saar = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."ar_sa".$url ?>
                                            <a href="<?php echo $url_saar ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/saudi_arabic.png" alt=""> </a>
                                            <a class="en" href="<?php echo $url_sa ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/saudi_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url_bh = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_bh".$url ?>
                                            <a href="<?php echo $url_bh ?> "><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/bahrain_logo.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <?php $url_bhar = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."ar_bh".$url ?>
                                            <a href="<?php echo $url_bhar ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/Bahrine_arabic.png" alt=""> </a>
                                            <a class="en" href="<?php echo $url_bh ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/Bahrine_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url_kw = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_kw".$url ?>
                                            <a href="<?php echo $url_kw ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/kuwait_logo.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <?php $url_kwar = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."ar_kw".$url ?>
                                            <a href="<?php echo $url_kwar ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/kuwait_arabic.png" alt=""> </a>
                                            <a class="en" href="<?php echo $url_kw ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/kuwait_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url_qa = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_qa".$url ?>
                                            <a href="<?php echo $url_qa ?> "><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/egypt_logo.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <?php $url_qaar = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."ar_qa".$url ?>
                                            <a href="<?php echo $url_qaar ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/egypt_arabic.png" alt=""> </a>
                                            <a class="en" href="<?php echo $url_qa ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/egypt_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url_om = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_om".$url ?>
                                            <a href="<?php echo $url_om  ?> "><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/oman_logo.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <?php $url_omar = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."ar_om".$url ?>
                                            <a href="<?php echo $url_omar ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/oman_arabic.png" alt=""> </a>
                                            <a class="en" href="<?php echo $url_om  ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/oman_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url_ir = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_iq".$url ?>
                                            <a href="<?php echo $url_ir ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/iraq_flag.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <?php $url_irar = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."ar_iq".$url ?>
                                            <a href="<?php echo $url_irar ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/iraq_arabic.png" alt=""> </a>
                                            <a class="en" href="<?php echo $url_ir ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/iraq_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                                <td class="us">
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url_us = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_us".$url ?>
                                            <a href="<?php echo $url_us ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/us_logo.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <a class="en" href="<?php echo $url_us ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/us_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr class="last">
                                <td class="uk">
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url_uk = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_uk".$url ?>
                                            <a href="<?php echo $url_uk ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/uk_logo.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <a class="en" href="<?php echo $url_uk ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/uk_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                                <td class="int">
                                    <div class="divwidth">
                                        <div class="flagsimg">
                                            <?php $url_int = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )."en_int".$url ?>
                                            <a href="<?php echo $url_int; ?> "><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/us_logo.png" alt=""></a>
                                        </div>
                                        <div class="flagslinks">
                                            <a class="en" href="<?php echo $url_int; ?>"><img src="<?php echo Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true )?>images/int_english.png" alt=""> </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>

                    </div>
                </div>
                </td>
              
            </tr>
        </table>
    </div>
<?php endif ?>
</body>
</html>