<div class="block1" style="width:700px;">
	<div class="column first odd">
		<div class="itemMenu level1">
			<a class="itemMenuName level1" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=3"><span><?php echo $this->__('Women') ?></span></a>
			<div class="itemSubMenu level1">
				<div class="itemMenu level2">
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=7"><span><?php echo $this->__('Clothing') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=6"><span><?php echo $this->__('Shoes') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=9"><span><?php echo $this->__('Bags') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=8"><span><?php echo $this->__('Accessories') ?></span></a>
				</div>
			</div>
		</div>
	</div>
	<div class="column first even">
		<div class="itemMenu level1">
			<a class="itemMenuName level1" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=4"><span><?php echo $this->__('Men') ?></span></a>
			<div class="itemSubMenu level1">
				<div class="itemMenu level2">
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=51"><span><?php echo $this->__('Clothing') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=43"><span><?php echo $this->__('Shoes') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=65"><span><?php echo $this->__('Bags') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=65"><span><?php echo $this->__('Accessories') ?></span></a>
				</div>
			</div>
		</div>
	</div>
	<div class="column first even">
		<div class="itemMenu level1">
			<a class="itemMenuName level1" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=5"><span><?php echo $this->__('Kids') ?></span></a>
			<div class="itemSubMenu level1">
				<div class="itemMenu level2">
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=77"><span><?php echo $this->__('Clothing') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=75"><span><?php echo $this->__('Shoes') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=82"><span><?php echo $this->__('Bags') ?></span></a>
					<a class="itemMenuName level2" href="<?php echo Mage::getBaseUrl() ?>what-is-new?cat=85"><span><?php echo $this->__('Accessories') ?></span></a>
				</div>
			</div>
		</div>
	</div>

    <div class="clearBoth">&nbsp;</div>
</div>
<!-- summer-new-arrivals-ar -->
<div class="column one_third">

<?php
$store = Mage::app()->getStore();
?>

<a class="banner" title="Sneaker Arena" href="<?php echo $this->getUrl("what-is-new") ?>"> <img alt="Sneaker Arena" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>wysiwyg/summer-new-arrival_<?php echo $store->getCode() ?>.jpg" /> </a></div>




