<?php 
/**
 *
 *
 * @package     Apptha_Marketplace
 * @author      Progos Team
 * @copyright   Copyright (c) 2016 Progos Tech.
 *
 */
?>

<div id="cus_menu1" class="menu act" onmouseover="ShowMenuPopup(this, event, 'cus_popup1');" onmouseout="HideMenuPopup(this, event, 'cus_popup1', 'cus_menu1')">
    <div class="parentMenu"><a href="javascript:void(0);" rel="http://localhost/elabels/women"> <span><?php echo $this->__('Sports Shop'); ?></span> </a></div>
</div>
<div id="cus_popup1" class="custom-menu-popup" onmouseover="PopupOver(this, event, 'popup', 'cus_menu1')" onmouseout="HideMenuPopup(this, event, 'cus_popup1', 'cus_menu1')">
    <div class="block1"><?php echo $this->__('Sports Shop'); ?>
        <div class="clearBoth">&nbsp;</div>
    </div>
</div>

<div id="cus_menu2" class="menu act" onmouseover="ShowMenuPopup(this, event, 'cus_popup2');" onmouseout="HideMenuPopup(this, event, 'cus_popup2', 'cus_menu2')">
    <div class="parentMenu"><a href="javascript:void(0);" rel="http://localhost/elabels/women"> <span><?php echo $this->__('Brands'); ?></span> </a></div>
</div>
<div id="cus_popup2" class="custom-menu-popup" onmouseover="PopupOver(this, event, 'popup', 'cus_menu2')" onmouseout="HideMenuPopup(this, event, 'cus_popup2', 'cus_menu2')">
    <div class="block1"><?php echo $this->__('Brands'); ?>
        <div class="clearBoth">&nbsp;</div>
    </div>
</div>

<div id="menu7" class="menu act" onmouseover="ShowMenuPopup(this, event, 'popup7');" onmouseout="HideMenuPopup(this, event, 'popup7', 'menu7')">
    <div class="parentMenu"><a href="javascript:void(0);" rel="http://localhost/elabels/women"> <span><?php echo $this->__('Designer Deals'); ?></span> </a></div>
</div>
<div id="popup7" class="custom-menu-popup" onmouseover="PopupOver(this, event, 'popup', 'menu7')" onmouseout="HideMenuPopup(this, event, 'popup7', 'menu7')">
    <div class="block1"><?php echo $this->__('Designer Deals'); ?>
        <div class="clearBoth">&nbsp;</div>
    </div>
</div>

<div id="menu8" class="menu act adn-sale" onmouseover="ShowMenuPopup(this, event, 'popup8');" onmouseout="HideMenuPopup(this, event, 'popup8', 'menu8')">
    <div class="parentMenu"><a href="javascript:void(0);" rel="http://localhost/elabels/women"> <span><?php echo $this->__('Sale'); ?></span> </a></div>
</div>
<div id="popup8" class="custom-menu-popup" onmouseover="PopupOver(this, event, 'popup', 'menu8')" onmouseout="HideMenuPopup(this, event, 'popup8', 'menu8')">
    <div class="block1"><?php echo $this->__('Sale'); ?>
        <div class="clearBoth">&nbsp;</div>
    </div>
</div>