<?php $categories =  $this->getCategoryCollection();
$genders = array( 22=>"WOMEN" , 20=>"MEN" , 12=>"KIDS" );
$arabicGender = array( "WOMEN" => "النساء" , "MEN" => "الرجال" , "KIDS"=> "الاطفال" );
$storeId = Mage::app()->getStore()->getId();
$path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/';
?>
<div class="navbar navbar-default yamm">
    <div class="navbar-header">
    </div>
    <div id="navbar-collapse-grid" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <?php foreach( $genders as $key => $gender  ){ ?>
                <li class="dropdown yamm-fw">
                    <a href="<?php echo Mage::getBaseUrl().strtolower($gender).'/';?>" data-toggle="dropdown" class="dropdown-toggle"><?php echo $this->__($gender) ; ?></a>
                    <ul class="dropdown-menu multi-column columns-3 animation open popup_<?php echo $gender; ?>">
                        <div class="row">
                            <div class="navColsOuter">

                                <?php
                                $changeColumnAfter = $key;
                                $count = 1;
                                $liCount = 0;
                                $html = '';
                                $kidsCount = 1;
                                foreach( $categories as $category ){
                                    if( $count == 1 )
                                        $html .= $this->openHtmlBlock();

                                    $children = $category->getChildrenCategories();
                                    if( !$children )
                                        $children = $category->getChildren();

                                if( strtolower($category->getName()) == strtolower('New Arrivals') || trim($category->getName()) == "وصلنا حديثاً" ){

                                    $liCount ++;
                                    foreach ($children as $child) {

                                            /* If current category and current gender is matched then It enter into the block */
                                            if( strtolower($child->getName()) == strtolower($gender) || $arabicGender[$gender] == $this->__(trim($child->getName())) ){
                                                $html .= '<li class="firstchild"><a href="'.$this->getCategoryUrl($child).'">'.$this->__($category->getName()).'</a></li>';
                                                /* Load Thumbnail Image for Menu from Category */
                                                $tempCat = $this->getBannerImage($child);

                                                /* Show Image of category if category image is added for top postion. */
                                                if( !empty( $tempCat->getMegamenubannerPosition()) && $tempCat->getMegamenubannerPosition()== 'top' ){
                                                    $html .= '<img src="'.$path.$tempCat->getMegamenubanner().'"/>';
                                                }


                                                $tempResutl = $this->generateChildLevelCategoryNewArrival($child , $liCount , $changeColumnAfter , $kidsCount );
                                                $liCount = $tempResutl['liCount'];
                                                $html .= $tempResutl['html'];

                                                /* Show Image of category if category image is added for bottom postion. */
                                                if( !empty( $tempCat->getMegamenubannerPosition()) && $tempCat->getMegamenubannerPosition()== 'bottom' ){
                                                    $html .= '<img src="'.$path.$tempCat->getMegamenubanner().'"/>';
                                                }

                                            }

                                        }
                                    }else if( strtolower($category->getName()) ==  strtolower($gender) || $arabicGender[$gender] == $this->__(trim($category->getName()))  ){

                                        /* Show Image of category if category image is added for top postion. */
                                        if( !empty( $category->getMegamenubannerPosition()) && $category->getMegamenubannerPosition()== 'top' ){
                                            $html .= '<img src="'.$path.$category->getMegamenubanner().'"/>';
                                        }

                                        foreach ($children as $child) {
                                            $html .= '<li class="firstchild"><a href="'.$this->getCategoryUrl($child).'">'.$this->__($child->getName()).'</a></li>';
                                            $liCount ++;
                                            $tempResutl = $this->generateChildLevelCategory($child , $liCount , $changeColumnAfter , $kidsCount );
                                            $liCount = $tempResutl['liCount'];
                                            $html .= $tempResutl['html'];
                                        }

                                        /* Show Image of category if category image is added for bottom postion. */
                                        if( !empty( $category->getMegamenubannerPosition()) && $category->getMegamenubannerPosition()== 'bottom' ){
                                            $html .= '<img src="'.$path.$category->getMegamenubanner().'"/>';
                                        }

                                }else if( strtolower($category->getName()) == strtolower('Sales') || trim($category->getName()) =="تخفيضات" ){
                                    foreach ($children as $child) {

                                            /* If current category and current gender is matched then It enter into the block */
                                            if( strtolower($child->getName()) == strtolower($gender) || $arabicGender[$gender] == $this->__(trim($child->getName())) ){

                                                $identifierLandingPages = "mega-menu-desktop-landingpages-".strtolower($gender);

                                                $staticLandingPages =  $this->getLayout()->createBlock('cms/block')->setStoreId($storeId)->setBlockId($identifierLandingPages)->toHtml();
                                                if( $staticLandingPages != '' ){
                                                    $html .= $staticLandingPages;
                                                    $liCount = $liCount + 3;
                                                }


                                                /* Load Thumbnail Image for Menu from Category */
                                                $tempCat = $this->getBannerImage($child);
                                                $html .= '<li class="firstchild sale"><a href="'.$this->getCategoryUrl($category).'">'.$this->__("SALE").'</a></li>';
                                                /* Show Image of category if category image is added for top postion. */
                                                if( !empty( $tempCat->getMegamenubannerPosition()) && $tempCat->getMegamenubannerPosition()== 'top' ){
                                                    $html .= '<img src="'.$path.$tempCat->getMegamenubanner().'"/>';
                                                }
                                                $liCount ++;
                                                $tempResutl = $this->generateChildLevelCategory( $child , $liCount , $changeColumnAfter , $kidsCount );
                                                $liCount = $tempResutl['liCount'];
                                                $html .= $tempResutl['html'];

                                                /* Show Image of category if category image is added for bottom postion. */
                                                if( !empty( $tempCat->getMegamenubannerPosition()) && $tempCat->getMegamenubannerPosition()== 'bottom' ){
                                                    $html .= '<img src="'.$path.$tempCat->getMegamenubanner().'"/>';
                                                }
                                            }
                                        }
                                    }

                                    if( is_array($changeColumnAfter) )
                                        $changeColumnAfter = $changeColumnAfter[$kidsCount];

                                    if( $liCount == $changeColumnAfter &&  $count != $categories->count() ){
                                        $html .= $this->closeHtmlBlock();
                                        $html .= $this->openHtmlBlock();
                                        $liCount = 0;
                                        $kidsCount++;
                                    }

                                    if( $count == $categories->count() ){
                                        $html .= $this->closeHtmlBlock();
                                    }


                                    $count++;
                                }
                                echo $html;
                                $identifier = "mega-menu-desktop-".strtolower($gender);
                                echo $this->getLayout()->createBlock('cms/block')->setStoreId($storeId)->setBlockId($identifier)->toHtml();
                                ?>
                            </div>
                        </div>
                    </ul>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
