<?php
$active = Mage::getStoreConfig('aramexsettings/aramexcalculator/active');
if ($active) {
    ?>
    <button data-popup-open="popup-1" type="button" style="margin-top:10px; margin-bottom:10px;"
            title="Check Aramex Shipping Rate"
            class="button btn-cart aramexcalculator"
    >
        <span><span>Check Aramex Shipping Rate</span></span>
    </button>
    <div class="aramex_popup" data-popup="popup-1">
        <div class="aramex_popup-inner">
            <h2 style="color: #EA7601;">Check Aramex Shipping Rate</h2>
            <form method="post" action="">
                <h3>Shipment Destination</h3>
                <div class="aramex_field">
                    <label>Country</label>
                    <select name="destination_country" class="arm_country" id="destination_country">
                        <?php if (count($this->getCountries()) > 0): ?>
                            <?php foreach ($this->getCountries() as $_country): ?>
                                <option value="<?php echo $_country['value'] ?>" <?php
                                if ($this->getDestinationAddress()) {
                                    $address = $this->getDestinationAddress();
                                    echo ($address['country_id'] == $_country['value']) ? 'selected="selected"' : '';
                                }
                                ?>>
                                    <?php echo $_country['label'] ?>
                                </option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>
                </div>
                <div class="aramex_field">
                    <label>City <span class="red no-display">*</span></label>
                    <input type="text" name="destination_city" autocomplete="off" id="destination_city"
                           value="<?php echo ($address) ? $address['city'] : ''; ?>"/>
                    <div id="destination_city_loading_autocomplete" class="loading_autocomplete" style="display:none;">
                        <img style="height:30px; margin-left:65px;"
                             src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                             alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading cities...')) ?>"
                             title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading cities...')) ?>"
                             class="v-middle"/>
                    </div>
                </div>
                <div class="aramex_field">
                    <div class="field fl width-270">
                        <label>Zip code <span class="red no-display">*</span></label>
                        <input type="text" name="destination_zipcode" id="destination_zipcode"
                               value="<?php echo ($address) ? $address['postcode'] : ''; ?>"/>
                    </div>
                </div>
                <div class="aramex_field aramex_result_block">
                    <h3 style="display:none; color: #EA7601;">Result</h3>
                    <div class="aramex_result mar-10">
                    </div>
                    <span class="aramex-please-wait" id="payment-please-wait" style="display:none;">
                        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                             alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Please wait...')) ?>"
                             title="<?php echo Mage::helper('core')->quoteEscape($this->__('Please wait...')) ?>"
                             class="v-middle"/> <?php echo $this->__('Please wait...') ?>
                    </span>
                </div>
                <button name="aramex_calc_rate_submit" class="button btn-cart" type="button"
                        id="aramex_calc_rate_submit"
                        onclick="sendAramexRequest('<?php echo $product_id; ?>')">Calculate
                </button>
            </form>
            <a class="aramex_popup-close" data-popup-close="popup-1" href="#">x</a>
        </div>
    </div>

    <script src="<?php echo $this->getSkinUrl('aramex/js/jquery-ui.js'); ?>"></script>
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl('aramex/css/jquery-ui.css'); ?>"/>
    <script>
        jQuery.noConflict();
        jQuery(document).ready(function () {
            jQuery(function () {
                //----- OPEN
                jQuery('[data-popup-open]').on('click', function (e) {
                    var targeted_popup_class = jQuery(this).attr('data-popup-open');
                    jQuery('[data-popup="' + targeted_popup_class + '"]').fadeIn(350);
                    e.preventDefault();
                });

                //----- CLOSE
                jQuery('[data-popup-close]').on('click', function (e) {
                    var targeted_popup_class = jQuery(this).attr('data-popup-close');
                    jQuery('[data-popup="' + targeted_popup_class + '"]').fadeOut(350);
                    e.preventDefault();
                });
            });
        });

        function sendAramexRequest() {
            var chk_city = jQuery('#destination_city').val();
            var chk_postcode = jQuery('#destination_zipcode').val();
            var country_code = jQuery("#destination_country").val();
            var store_id = "<?php echo Mage::app()->getStore()->getId(); ?>";
            var currency = "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>";
            var product_id = "<?php echo $this->getId(); ?>";
            var system_base_url = getSystemBaseUrl();
            jQuery('.aramex_result_block h3').css("display", "none");
            jQuery('.aramex-please-wait').css("display", "block");
            jQuery('.aramex_result').css("display", "none");
            jQuery.ajax({
                url: system_base_url + "aramexcalculator/index/calculator",
                data: {
                    city: chk_city,
                    post_code: chk_postcode,
                    country_code: country_code,
                    store_id: store_id,
                    product_id: product_id,
                    currency: currency
                },
                type: 'Post',
                success: function (result) {
                    var message = "";
                    var response = jQuery.parseJSON(result);
                    if (response.error) {
                        message = "<p style='color:red;'>" + response.error + "</p>";
                    } else {
                        jQuery.each(response, function (index, value) {
                            message = message + "<p style='color: rgb(234, 118, 1);'>" + value.label + " " + value.amount + " " + value.currency + "</p>";
                        });
                    }
                    jQuery('.aramex_result_block h3').css("display", "block");
                    jQuery('.aramex_result').css("display", "block");
                    jQuery('.aramex-please-wait').css("display", "none");
                    jQuery('.aramex_result').html(message);
                }
            });
        }

        function getSystemBaseUrl() {
            return BASE_URL = '<?php echo Mage::getBaseUrl();?>';
        }

        var billingAramexCitiesObj;
        var billing_aramex_cities_temp;
        var billing_aramex_cities;
        billingAramexCitiesObj = AutoSearchControls('destination_city', billing_aramex_cities);
        jQuery("select[name='destination_country']").change(function () {
            getAllCitiesJson('destination_country');
        });
        getAllCitiesJson('destination_country');

        function AutoSearchControls(type, search_city) {
            return jQuery('input[name="' + type + '"]')
                .autocomplete({
                    /*source: search_city,*/
                    minLength: 3,
                    scroll: true,
                    source: function (req, responseFn) {
                        var re = jQuery.ui.autocomplete.escapeRegex(req.term);
                        var matcher = new RegExp("^" + re, "i");
                        var a = jQuery.grep(search_city, function (item, index) {
                            return matcher.test(item);
                        });
                        responseFn(a);
                    },
                    search: function (event, ui) {
                        /* open initializer */
                        forceDisableNext(type);
                    },
                    response: function (event, ui) {
                        /* open initializer */
                        jQuery('#' + type + '_loading_autocomplete').css("display", "none");
                    },
                }).focus(function () {
                    jQuery(this).autocomplete("search", "");
                });
        }

        function forceDisableNext(type) {
            jQuery('#' + type + '_loading_autocomplete').show();
        }

        function getAllCitiesJson(type) {
            var system_base_url = getSystemBaseUrl();
            var country_code = jQuery("select[name='" + type + "']").val();
            var url_check = system_base_url + "apilocationvalidator/index/searchallcitiesJson?country_code=" + country_code;
            billing_aramex_cities_temp = '';
            billingAramexCitiesObj.autocomplete("option", "source", url_check);
        }
    </script>

    <style>
        .content {
            max-width: 800px;
            width: 100%;
            margin: 0px auto;
            margin-bottom: 60px;
        }

        /*------------------------------------------------------------
        -------- DEMO Code
        ------------------------------------------------------------*/
        /* Outer */
        .aramex_popup {
            width: 100%;
            height: 100%;
            display: none;
            position: fixed;
            top: 0px;
            left: 0px;
            background: rgba(0, 0, 0, 0.75);
            z-index: 9999;
        }

        /* Inner */
        .aramex_popup-inner {
            max-width: 700px;
            width: 90%;
            padding: 40px;
            position: absolute;
            top: 50%;
            left: 50%;
            -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            box-shadow: 0px 2px 6px rgba(0, 0, 0, 1);
            border-radius: 3px;
            background: #fff;
        }

        /* Close Button */
        .aramex_popup-close {
            width: 30px;
            height: 30px;
            padding-top: 4px;
            display: inline-block;
            position: absolute;
            top: 0px;
            right: 0px;
            transition: ease 0.25s all;
            -webkit-transform: translate(50%, -50%);
            transform: translate(50%, -50%);
            border-radius: 1000px;
            background: rgba(0, 0, 0, 0.8);
            font-family: Arial, Sans-Serif;
            font-size: 20px;
            text-align: center;
            line-height: 100%;
            color: #fff;
        }

        .aramex_popup-close:hover {
            -webkit-transform: translate(50%, -50%) rotate(180deg);
            transform: translate(50%, -50%) rotate(180deg);
            background: rgba(0, 0, 0, 1);
            text-decoration: none;
        }

        .aramex_popup .aramex_field {
            padding: 10px;
        }

        .aramex_popup label {
            width: 60px;
        }

        .aramex_popup select {
            padding: 5px;
        }

        .aramex_popup-inner button, .aramex_popup-inner input, .aramex_popup-inner select, .aramex_popup-inner table, .aramex_popup-inner textarea {
            font-family: Arial !important;
        }

        .ui-helper-hidden-accessible {
            display: none;
        }
    </style>
<?php } ?>