<div class="home-page-top-cat-list">

    <div class="women-top-cats">
        <p><?php echo $this->__('Shop'); ?></p>
        <h2><?php echo $this->__('Top Women Categories'); ?></h2>
        <div class="top-cat-list women-cats-list">
        	<a href="#">Angus And Angel</a>
        	<a href="#">Dolce And Gabbana</a>
        	<a href="#">Giampieronicola</a>
        </div>
    </div>

    <div class="men-top-cats">
        <p><?php echo $this->__('Shop'); ?></p>
        <h2><?php echo $this->__('Top Men Categories'); ?></h2>
        <div class="top-cat-list men-cats-list">
        	<a href="#">Angus And Angel</a>
        	<a href="#">Dolce And Gabbana</a>
        	<a href="#">Giampieronicola</a>
        </div>
    </div>

</div>