<p class="title"><?php echo $this->__("Our Top Categories"); ?></p>
<ul>
<li><a onclick="footerMenuTrigger('<?php echo $this->__('Women&rsquo;s Clothing'); ?>')" title="Women&rsquo;s Clothing" href="<?php echo Mage::getUrl('women-clothing') ?>"><?php echo $this->__("Women&rsquo;s Clothing"); ?></a></li>

<li><a onclick="footerMenuTrigger('<?php echo $this->__('Men&rsquo;s Clothing'); ?>')" title="Men&rsquo;s Clothing" href="<?php echo Mage::getUrl('men-clothing') ?>"><?php echo $this->__("Men&rsquo;s Clothing"); ?></a></li>

<li><a onclick="footerMenuTrigger('<?php echo $this->__('Women&rsquo;s Shoes'); ?>')" title="Women&rsquo;s Shoes" href="<?php echo Mage::getUrl('women-shoes') ?>"><?php echo $this->__("Women&rsquo;s Shoes"); ?></a></li>

<!-- <li><a title="Men&rsquo;s Football Shoes" href="<?php echo Mage::getUrl('football-shoes') ?>"><?php echo $this->__("Men&rsquo;s Football Shoes"); ?></a></li> -->

<li><a onclick="footerMenuTrigger('<?php echo $this->__('Women&rsquo;s Dresses'); ?>')" title="Women&rsquo;s Dresses" href="<?php echo Mage::getUrl('women-clothing-dresses') ?>">
<?php echo $this->__("Women&rsquo;s Dresses"); ?></a></li>

<li><a onclick="footerMenuTrigger('<?php echo $this->__('Women&rsquo;s Accessories'); ?>')" title="Women&rsquo;s Accessories" href="<?php echo Mage::getUrl('women-accessories') ?>"><?php echo $this->__("Women&rsquo;s Accessories"); ?></a></li>

<!-- <li><a title="Shoes Online" href="<?php echo Mage::getUrl('----------') ?>"><?php echo $this->__("Shoes Online"); ?></a></li> -->

<!-- <li><a title="Clothes Online" href="<?php echo Mage::getUrl('----------') ?>"><?php echo $this->__("Clothes Online"); ?></a></li> -->
</ul>
