<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>
<div id="onestepcheckout_forgotbox" style="display: none;" class='op_login_area'>

	<h3>
        <?php echo $this->__('Forgot Password') ?>
    </h3>
	<p>
		<?php echo $this->__('Please enter your email below and we will send you a new password.') ?>
	</p>
	
<?php
$forgot_url	= $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
$http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
if($http_mode)
	$forgot_url	= str_replace('http:', 'https:', $forgot_url);  
?>
    <form action="<?php echo $forgot_url ?>" method="post" id="forgot-password-form">
        <div class="boxcontent form_fields">

			<table>
				<tr>
					
					<td><label>
							<?php echo $this->__('Email Address:') ?><span class="required"></span>
						</label>
						<div class="data_area">
							<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email-nonarabic" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" size="30" />
						</div>
					</td>
				</tr>
			</table>
        </div>
        <div class="buttons-set">

			<button type="submit" title="<?php echo $this->__('Send password') ?>" id="btn-forgot" class="button"><?php echo $this->__('Send password') ?></button>
            <span class="please-wait" id="forgot-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" class="v-middle" alt=""/>
            </span>
            <p class="back-link"><a href="javascript:void(0)" class="onestepcheckout_loginlink" onclick='open_login();'><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var forgotForm = new VarienForm('forgot-password-form', true);
    //]]>
    </script>
</div>
<?php }?>