<?php
/**
 * Created by JetBrains PhpStorm.
 * Author Rudyuk Vitalij Anatolievich
 * Email rvansp@gmail.com
 * Blog www.cervic.info
 */
$order = Mage::registry('order');
$storeId = NULL;
/*multistore*/
$storeId = $order->getStoreId();
/*multistore*/
$servicecodesReturn = Mage::registry('servicecodesreturn');
$servicecodes = Mage::registry('servicecodes');
$shipTo = Mage::registry('shipTo');
$shipment = Mage::registry('shipment');
$type = Mage::registry('type');
$shipmentTotalPrice = Mage::registry('shipmentTotalPrice');
$shipmentTotalWeight = Mage::registry('shipmentTotalWeight');
$shipByUps = Mage::registry('shipByUps');
$shipByUpsCode = Mage::registry('shipByUpsCode');
$shipByUpsMethodName = Mage::registry('shipByUpsMethodName');
$shipByGlobalMethodName = Mage::registry('shipByGlobalMethodName');
$shipByUpsMethods = Mage::registry('shipByUpsMethods');
$shipByGlobalMethods = Mage::registry('shipByGlobalMethods');
$unitofmeasurement = Mage::registry('unitofmeasurement');
$paymentmethod = Mage::registry('paymentmethod');
$shippingAmount = Mage::registry('shippingAmount');
$dhlAccounts = Mage::registry('dhlAccounts');
$dhlAccountsDuty = Mage::registry('dhlAccountsDuty');
$defParams = Mage::registry('defParams');
$defConfParams = Mage::registry('defConfParams');
$notificationMessage = Mage::registry('notificationMessage');
?>
<?php
echo '<form id="edit_form" action="' . $this->getUrl('adminhtml/dhllabel_dhllabel/showlabel/order_id/' . $this->getRequest()->getParam('order_id') . '/shipment_id/' . $this->getRequest()->getParam('shipment_id') . '/type/' . $this->getRequest()->getParam('type')) . '" method="post">';
?>
    <div class="f-right" style="clear:both;margin-bottom: 15px;">
        <button type="button" class="scalable save submit-button"
                onclick="if(editForm.submit()) disableElements('submit-button');" style="">
            <span><?php echo Mage::helper('dhllabel')->__('Submit'); ?></span></button>
    </div>
    <div class="clear"></div>
    <div class="clear"></div>
    <div class="box-left" id="box_package_count">
        <?php /*if ($this->getRequest()->getParam('type') == 'shipment'):*/ ?>
        <div class="entry-edit" id="box_package_count_first">
            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend"><?php echo Mage::helper('dhllabel')->__('Add Package'); ?></h4>
            </div>
            <div class="np fieldset">
                <div>
                    <div class="content">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list" id="add_package_table">
                                <tbody>
                                <tr id="add_package_tr_id">
                                    <td class="label"><label
                                                for="add_package_func"><?php echo Mage::helper('dhllabel')->__('Add Package'); ?></label>
                                    </td>
                                    <td class="value">
                                        <button type="button"
                                                id="add_package_func"><?php echo Mage::helper('dhllabel')->__('Add'); ?></button>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php /*endif;*/ ?>
        <?php $i = 1;
        foreach ($defParams AS $val): ?>
            <div class="entry-edit package_count">
                <div class="entry-edit-head collapseable">
                    <a href="#" class="open"><?php echo Mage::helper('dhllabel')->__('Package ' . $i);
                        $i++; ?><?php if ($i > 2): ?><span class="delete_package"
                                                           style="float: right;margin-right: 50px;">Delete Package</span><?php endif; ?>
                    </a>
                </div>
                <div class="np fieldset">
                    <div>
                        <div class="content">
                            <div class="hor-scroll">
                                <table cellspacing="0" class="form-list">
                                    <tbody>
                                    <tr>
                                        <td class="label">
                                            <label><?php echo Mage::helper('dhllabel')->__('Weight'); ?> <span
                                                        class="required">*</span></label>
                                        </td>
                                        <td class="value">
                                            <input type="text"
                                                   value="<?php echo round($val['weight'], 1) > 0 ? round($val['weight'], 1) : '0'; ?>"
                                                   name="package[weight][]" class="input-text  required-entry">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">
                                            <label><?php echo Mage::helper('dhllabel')->__('Pack weight'); ?></label>
                                        </td>
                                        <td class="value">
                                            <input type="text" name="package[packweight][]"
                                                   value="<?php echo $val['packweight']; ?>"
                                                   class=" input-text">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">
                                            <label><?php echo Mage::helper('dhllabel')->__('Depth'); ?></label>
                                        </td>
                                        <td class="value">
                                            <input type="text"
                                                   value="<?php echo isset($val['length']) ? $val['length'] : ""; ?>"
                                                   name="package[depth][]" class="input-text">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">
                                            <label><?php echo Mage::helper('dhllabel')->__('Width'); ?></label>
                                        </td>
                                        <td class="value">
                                            <input type="text"
                                                   value="<?php echo isset($val['width']) ? $val['width'] : ""; ?>"
                                                   name="package[width][]" class="input-text">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">
                                            <label><?php echo Mage::helper('dhllabel')->__('Height'); ?></label>
                                        </td>
                                        <td class="value">
                                            <input type="text"
                                                   value="<?php echo isset($val['height']) ? $val['height'] : ""; ?>"
                                                   name="package[height][]" class="input-text">
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend">
                    <?php echo Mage::helper('dhllabel')->__('Configuration options'); ?>
                </h4>
            </div>
            <div class="np fieldset">
                <div>
                    <div class="content">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                <tr>
                                    <td class="label">
                                        <label for="upsaccount">
                                            <?php echo Mage::helper('dhllabel')->__('Who pay for Shipment?'); ?>
                                        </label>
                                    </td>
                                    <td class="value">
                                        <select name="upsaccount" id="upsaccount">
                                            <?php foreach ($dhlAccounts AS $v): ?>
                                                <option value="<?php echo $v['value']; ?>"
                                                    <?php echo $defConfParams['upsaccount'] == $v['value'] ?
                                                        ' SELECTED' : ''; ?>><?php echo $v['label']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                                <?php if ($type != 'refund'): ?>
                                    <tr>
                                        <td class="label">
                                            <label for="duty_payment_type">
                                                <?php echo Mage::helper('dhllabel')->__('Who pay for Duty and Tax?'); ?>
                                            </label>
                                        </td>
                                        <td class="value">
                                            <select name="duty_payment_type" id="duty_payment_type">
                                                <?php foreach ($dhlAccountsDuty AS $v): ?>
                                                    <option
                                                            value="<?php echo $v['value']; ?>"<?php echo $defConfParams['duty_payment_type'] == $v['value'] ? ' SELECTED' : ''; ?>><?php echo $v['label']; ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <?php /*<tr>
        <td class="label">
            <label
                for="serviceCode"><?php echo Mage::helper('dhllabel')->__('Local Product Code'); ?></label>
        </td>
        <td class="value">
            <?php if ($shipByUps == 'dhlint'): ?>
                <span style="text-decoration: underline;"><?php echo $shipByUpsMethodName; ?></span>
                <input type="hidden" name="serviceCode" readonly="readonly"
                       value="<?php echo $shipByUpsCode; ?>">
                <br/>
            <?php endif; ?>
            <select name="serviceCode" id="serviceCode">
                <?php foreach ($shipByUpsMethods AS $k => $v): ?>
                    <option
                        value="<?php echo $k; ?>"<?php echo $shipByUpsCode == $k || ($shipByUps !== 'dhlint' && Mage::getStoreConfig('dhllabel/shipping/defaultshipmentmethod', $storeId) == $k) ? ' SELECTED' : ''; ?>><?php echo $v; ?><?php echo in_array($k, $servicecodes['local'], true)?' (Recommended)':''; ?></option>
                <?php endforeach; ?>
            </select>
        </td>
    </tr>*/ ?>
                                <tr>
                                    <td class="label">
                                        <label for="serviceGlobalCode">
                                            <?php echo Mage::helper('dhllabel')->__('Shipping method'); ?></label>
                                    </td>
                                    <td class="value">
                                        <?php if ($shipByUps == 'dhlint'): ?>
                                            <span
                                                    style="text-decoration: underline;"><?php echo $shipByGlobalMethodName; ?></span>
                                            <input type="hidden" name="serviceGlobalCode" readonly="readonly"
                                                   value="<?php echo $shipByUpsCode; ?>">
                                            <br/>
                                        <?php endif; ?>
                                        <select name="serviceGlobalCode" id="serviceGlobalCode">
                                            <?php foreach ($shipByGlobalMethods AS $k => $v):
                                                if (isset($servicecodes['global'])
                                                    && is_array($servicecodes['global'])
                                                    && in_array($k, $servicecodes['global'], true)
                                                ): ?>
                                                    <option value="<?php echo $k; ?>"
                                                        <?php echo $defConfParams['serviceGlobalCode'] == $k ?
                                                            ' SELECTED' : ''; ?>><?php echo $v; ?></option>
                                                <?php endif; endforeach; ?>
                                        </select>
                                        <textarea style="display:none;" name="shipping_methods" id="shipping_methods"><?php
                                            echo $this->getRequest()->getParam('type') == 'shipment' ?
                                                $defConfParams['shipping_methods']
                                                :$defConfParams['return_methods']; ?></textarea>
                                        <textarea style="display:none;"><?php
                                            echo $this->getRequest()->getParam('type') == 'shipment' ?
                                                $defConfParams['error_shipping_methods']
                                                :$defConfParams['error_return_methods']; ?></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="shipper_no">
                                            <?php echo Mage::helper('dhllabel')->__('Shipper address'); ?></label>
                                    </td>
                                    <td class="value">
                                        <select name="shipper_no" id="shipper_no" onchange="window.location.assign('<?php echo preg_replace("/\/shipperaddress\/[0-9]+/i", "", trim(Mage::helper('core/url')->getCurrentUrl(), "/")); ?>/shipperaddress/'+this.value)">
                                            <?php
                                            $shipperAddress = Mage::getStoreConfig('dhllabel/shipping/defaultshipper', $storeId);
                                            if($this->getRequest()->getParam('shipperaddress', null) !== null){
                                                $shipperAddress = $this->getRequest()->getParam('shipperaddress', null);
                                            }
                                            for ($shpf = 1; $shpf <= 5; $shpf++) {
                                                if (Mage::getStoreConfig('dhllabel/address_' . $shpf . '/enable') == 1) {
                                                    ?>
                                                    <option value="<?php echo $shpf; ?>"
                                                        <?php echo $shipperAddress == $shpf ? " SELECTED" : ""; ?>><?php
                                                        echo Mage::helper('dhllabel')->__(Mage::getStoreConfig('dhllabel/address_' . $shpf . '/addressname', $storeId));
                                                        ?></option>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="testing"><?php echo Mage::helper('dhllabel')->__('Test mode'); ?></label>
                                    </td>
                                    <td class="value">
                                        <?php
                                        $isTestingSelected[0] = '';
                                        $isTestingSelected[1] = '';
                                        $isTestingSelected[Mage::getStoreConfig('dhllabel/testmode/testing', $storeId)] = ' SELECTED';
                                        ?>
                                        <select name="testing" id="testing">
                                            <option
                                                    value="1"<?php echo $isTestingSelected[1]; ?>><?php echo Mage::helper('dhllabel')->__('Yes'); ?></option>
                                            <option
                                                    value="0"<?php echo $isTestingSelected[0]; ?>><?php echo Mage::helper('dhllabel')->__('No'); ?></option>
                                        </select>
                                    </td>
                                </tr>
                                <?php if ($this->getRequest()->getParam('type') == 'shipment'): ?>
                                    <tr>
                                        <td class="label"><label
                                                    for="addtrack"><?php echo Mage::helper('dhllabel')->__('Add tracking number automatically ?'); ?></label>
                                        </td>
                                        <td class="value">
                                            <?php
                                            $isAddtrackSelected[0] = '';
                                            $isAddtrackSelected[1] = '';
                                            $isAddtrackSelected[Mage::getStoreConfig('dhllabel/shipping/addtrack', $storeId)] = ' SELECTED';
                                            ?>
                                            <select name="addtrack" id="addtrack">
                                                <option
                                                        value="1"<?php echo $isAddtrackSelected[1]; ?>><?php echo Mage::helper('dhllabel')->__('Yes'); ?></option>
                                                <option
                                                        value="0"<?php echo $isAddtrackSelected[0]; ?>><?php echo Mage::helper('dhllabel')->__('No'); ?></option>
                                            </select>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <tr>
                                    <td class="label"><label
                                                for="shipmentdescription"><?php echo Mage::helper('dhllabel')->__('Shipment description'); ?></label>
                                    </td>
                                    <td class="value"><textarea id="shipmentdescription"
                                                                name="shipmentdescription"
                                                                rows="3"
                                                                class=" input-text"><?php echo isset($defConfParams['shipmentdescription']) ? $defConfParams['shipmentdescription'] : ''; ?></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="currencycode"><?php echo Mage::helper('dhllabel')->__('Currency code'); ?></label>
                                    </td>
                                    <td class="value">
                                        <select name="currencycode" id="currencycode" class=" input-text">
                                            <?php
                                            $dhlcurrency = Mage::getModel('adminhtml/system_config_source_currency')->toOptionArray(false);
                                            foreach ($dhlcurrency AS $k => $v): ?>
                                                <option
                                                        value="<?php echo $v['value']; ?>" <?php if (isset($defConfParams['currencycode']) && $defConfParams['currencycode'] == $v['value']): ?>
                                                    SELECTED<?php endif; ?>><?php echo $v['label']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                                <?php if ($type == 'shipment'): ?>
                                    <tr>
                                        <td class="label"><label
                                                    for="cod"><?php echo Mage::helper('dhllabel')->__('COD'); ?></label>
                                        </td>
                                        <td class="value">
                                            <input type="hidden" name="cod" value="0">
                                            <input type="checkbox" name="cod" id="cod"
                                                   value="1"<?php if (Mage::getStoreConfig('dhllabel/ratepayment/cod', $storeId) == 1 || $paymentmethod == 'cashondelivery' || $paymentmethod == 'phoenix_cashondelivery'): ?>
                                                checked="checked"<?php endif; ?>>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label
                                                    for="codmonetaryvalue"><?php echo Mage::helper('dhllabel')->__('COD Monetary value'); ?></label>
                                        </td>
                                        <td class="value">
                                            <input id="codmonetaryvalue"
                                                   name="codmonetaryvalue"
                                                   value="<?php echo Mage::getStoreConfig('dhllabel/ratepayment/cod_shipping_cost', $storeId) == 0 ? $shipmentTotalPrice - $shippingAmount : $shipmentTotalPrice; ?>"
                                                   class=" input-text" type="text">
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <tr>
                                    <td class="label"><label
                                                for="qvn"><?php echo Mage::helper('dhllabel')->__('Notification'); ?></label>
                                    </td>
                                    <td class="value">
                                        <input type="hidden" name="qvn" value="0">
                                        <input type="checkbox" name="qvn" id="qvn"
                                               value="1"<?php if (Mage::getStoreConfig('dhllabel/quantum/qvn', $storeId) == 1): ?>
                                            checked="checked"<?php endif; ?>>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="qvn_message_shipto"><?php echo Mage::helper('dhllabel')->__('Notification Message'); ?></label>
                                    </td>
                                    <td class="value">
            <textarea type="text" name="qvn_message_shipto"
                      id="qvn_message_shipto"
                      class=" input-text"><?php echo $notificationMessage; ?></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('dhllabel')->__('Packaging Type'); ?></label>
                                    </td>
                                    <td class="value">
                                        <select name="packagingtypecode" class=" input-text">
                                            <?php
                                            $dhlpackagecode = new Infomodus_Dhllabel_Model_Config_Dhlpackagecode();
                                            $dhlpackagecode = $dhlpackagecode->toOptionArray();
                                            foreach ($dhlpackagecode AS $k => $v): ?>
                                                <option
                                                        value="<?php echo $v['value']; ?>" <?php if (isset($defConfParams['packagingtypecode']) && $defConfParams['packagingtypecode'] == $v['value']): ?>
                                                    SELECTED<?php endif; ?>><?php echo $v['label']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('dhllabel')->__('Reference ID'); ?></label>
                                    </td>
                                    <td class="value">
                                        <textarea name="reference_id" cols="30"
                                                  rows="10"><?php echo isset($defConfParams['reference_id']) ? $defConfParams['reference_id'] : ''; ?></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('dhllabel')->__('Door to'); ?></label>
                                    </td>
                                    <td class="value">
                                        <select name="doorto" class=" input-text">
                                            <?php
                                            $doorto = new Infomodus_Dhllabel_Model_Config_Doorto();
                                            $doorto = $doorto->toOptionArray();
                                            foreach ($doorto AS $k => $v): ?>
                                                <option
                                                        value="<?php echo $v['value']; ?>"<?php if (Mage::getStoreConfig('dhllabel/shipping/doorto', $storeId) == $v['value']): ?>
                                                    SELECTED<?php endif; ?>><?php echo $v['label']; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label">
                                        <label><?php echo Mage::helper('dhllabel')->__('Declared Value'); ?></label>
                                    </td>
                                    <td class="value">
                                        <input name="declared_value" id="declaredValue" class="input-text"
                                               value="<?php echo isset($defConfParams['declared_value']) ? $defConfParams['declared_value'] : ''; ?>">
                                    </td>
                                </tr>
                                <?php if ($type == 'shipment'): ?>
                                    <tr>
                                        <td class="label"><label
                                                    for="default_return"><?php echo Mage::helper('dhllabel')->__('Create return label now'); ?></label>
                                        </td>
                                        <td class="value">
                                            <?php
                                            $isResidentialaddressSelected['Yes'] = '';
                                            $isResidentialaddressSelected['No'] = '';
                                            if (Mage::getStoreConfig('dhllabel/return/default_return', $storeId) == 0 || Mage::getStoreConfig('dhllabel/return/default_return_amount', $storeId) > $shipmentTotalPrice) {
                                                $isResidentialaddressSelected['No'] = ' SELECTED';
                                            } else {
                                                $isResidentialaddressSelected['Yes'] = ' SELECTED';
                                            }
                                            ?>
                                            <select name="default_return" id="default_return">
                                                <option
                                                        value="1"<?php echo $isResidentialaddressSelected['Yes']; ?>>
                                                    <?php echo Mage::helper('dhllabel')->__('Yes'); ?>
                                                </option>
                                                <option
                                                        value="0"<?php echo $isResidentialaddressSelected['No']; ?>><?php echo Mage::helper('dhllabel')->__('No'); ?></option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">
                                            <label
                                                    for="default_return_servicecode"><?php echo Mage::helper('dhllabel')->__('DHL shipping method for return label'); ?></label>
                                        </td>
                                        <td class="value">
                                            <?php if ($shipByUps == 'dhl'): ?>
                                                <span
                                                        style="text-decoration: underline;"><?php echo $shipByUpsMethodName; ?></span>
                                                <input type="hidden" name="default_return_servicecode"
                                                       readonly="readonly"
                                                       value="<?php echo $shipByUpsCode; ?>">
                                                <br/>
                                            <?php endif; ?>
                                            <select name="default_return_servicecode" id="default_return_servicecode">
                                                <?php foreach ($shipByUpsMethods AS $k => $v):
                                                    if(isset($servicecodesReturn['global'])
                                                        && is_array($servicecodesReturn['global'])
                                                        && in_array($k, $servicecodesReturn['global'], true)): ?>
                                                    <option
                                                            value="<?php echo $k; ?>"<?php echo ($shipByUpsCode == $k && !Mage::getStoreConfig('dhllabel/return/default_return_method', $storeId)) || Mage::getStoreConfig('dhllabel/return/default_return_method', $storeId) == $k ? ' SELECTED' : ''; ?>><?php echo $v; ?></option>
                                                <?php endif; endforeach; ?>
                                                <textarea style="display:none;" name="return_methods"
                                                          id="return_methods"><?php echo $defConfParams['return_methods']; ?></textarea>
                                                <textarea style="display:none;"><?php
                                                    echo $defConfParams['error_return_methods']; ?></textarea>
                                            </select>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend"><?php echo Mage::helper('dhllabel')->__('Configuration weight and dimension'); ?></h4>
            </div>
            <div class="np fieldset">
                <div>
                    <div class="content">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                <tr>
                                    <td class="label"><label
                                                for="weightunits"><?php echo Mage::helper('dhllabel')->__('Specific unit weight'); ?></label>
                                    </td>
                                    <td class="value">
                                        <?php
                                        $isWeightunitsSelected['L'] = '';
                                        $isWeightunitsSelected['K'] = '';
                                        $isWeightunitsSelected[Mage::getStoreConfig('dhllabel/weightdimension/weightunits', $storeId)] = ' SELECTED';
                                        ?>
                                        <select name="weightunits" id="weightunits">
                                            <option value="L"<?php echo $isWeightunitsSelected['L']; ?>>Pounds</option>
                                            <option value="K"<?php echo $isWeightunitsSelected['K']; ?>>Kilograms
                                            </option>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="unitofmeasurement"><?php echo Mage::helper('dhllabel')->__('Unit of measurement'); ?></label>
                                    </td>
                                    <td class="value">
                                        <select name="unitofmeasurement" id="unitofmeasurement">
                                            <?php foreach ($unitofmeasurement AS $k => $v): ?>
                                                <option
                                                        value="<?php echo $k; ?>"<?php echo Mage::getStoreConfig('dhllabel/weightdimension/unitofmeasurement', $storeId) == $k ? ' SELECTED' : '' ?>><?php echo $v; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend"><?php echo Mage::helper('dhllabel')->__('Customer Address'); ?></h4>
            </div>
            <div class="np fieldset">
                <div>
                    <div class="content">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                <tr>
                                    <td class="label"><label
                                                for="shiptocompanyname"><?php echo Mage::helper('dhllabel')->__('Company name'); ?>
                                            <span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptocompanyname" id="shiptocompanyname"
                                               value="<?php echo strlen($shipTo->getCompany()) > 0 ? $shipTo->getCompany() : $shipTo->getFirstname() . ' ' . $shipTo->getLastname(); ?>"
                                               class="required-entry input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="shiptoattentionname"><?php echo Mage::helper('dhllabel')->__('Contact name'); ?>
                                            <span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptoattentionname" id="shiptoattentionname"
                                               value="<?php echo $shipTo->getFirstname() . ' ' . $shipTo->getLastname(); ?>"
                                               class="required-entry input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="shiptophonenumber"><?php echo Mage::helper('dhllabel')->__('Phone number'); ?>
                                            <span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptophonenumber" id="shiptophonenumber"
                                               value="<?php echo $shipTo->getTelephone(); ?>"
                                               class="required-entry input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="shiptoaddressline1"><?php echo Mage::helper('dhllabel')->__('Street Address'); ?>
                                            <span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptoaddressline1" id="shiptoaddressline1"
                                               value="<?php echo $defConfParams['shiptoaddressline1']; ?>"
                                               class="required-entry input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="shiptoaddressline2"><?php echo Mage::helper('dhllabel')->__('Street Address 2'); ?></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptoaddressline2" id="shiptoaddressline2"
                                               value="<?php echo $defConfParams['shiptoaddressline2']; ?>"
                                               class="input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="shiptoaddressline3"><?php echo Mage::helper('dhllabel')->__('Street Address 3'); ?></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptoaddressline3" id="shiptoaddressline3"
                                               value="<?php echo $defConfParams['shiptoaddressline3']; ?>"
                                               class="input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="shiptocity"><?php echo Mage::helper('dhllabel')->__('City'); ?></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptocity" id="shiptocity"
                                               value="<?php echo $shipTo->getCity(); ?>" class="input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label style="color: green;"
                                                for="shiptocityselect"><?php echo Mage::helper('dhllabel')->__('Select Correct City Name In above Field'); ?></label>
                                    </td>
                                    <td class="value">
                                        <select onchange="updateCorrectCity()" name="shiptocityselect" id="shiptocityselect">
                                            <?php $cities = Mage::helper('dhllabel/help')->getKsaCities();
                                            foreach ($cities as $key=>$city){
                                                ?>
                                                <option value="<?php echo $key; ?>"><?php echo $city; ?></option>
                                            <?php } ?>
                                        </select>

                                    </td>
                                </tr>

                                <tr>
                                    <td class="label"><label
                                                for="shiptostateprovincecode"><?php echo Mage::helper('dhllabel')->__('State (province)'); ?></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptostateprovincecode" id="shiptostateprovincecode"
                                               value="<?php echo $shipTo->getRegion(); ?>" class="input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="shiptopostalcode"><?php echo Mage::helper('dhllabel')->__('Postal code'); ?></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="shiptopostalcode" id="shiptopostalcode"
                                               value="<?php echo $defConfParams['shiptopostalcode']; ?>"
                                               class="input-text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="shiptocountrycode"><?php echo Mage::helper('dhllabel')->__('Country code'); ?>
                                            <span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <select name="shiptocountrycode" id="shiptocountrycode" class="required-entry">
                                            <?php $countries = Mage::getModel('adminhtml/system_config_source_country')->toOptionArray();
                                            foreach ($countries as $country){
                                                ?>
                                                <option value="<?php echo $country['value']; ?>" <?php echo $country['value']== $shipTo->getCountryId()?" SELECTED":""; ?>><?php echo $country['label']; ?></option>
                                            <?php } ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label
                                                for="qvn_email_shipto"><?php echo Mage::helper('dhllabel')->__('Notification Email'); ?></label>
                                    </td>
                                    <td class="value">
                                        <input type="text" name="qvn_email_shipto"
                                               id="qvn_email_shipto" value="<?php echo $shipTo->getEmail(); ?>"
                                               class=" input-text">
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend"><?php echo Mage::helper('dhllabel')->__('Products'); ?></h4>
            </div>
            <div class="np fieldset">
                <div>
                    <div class="content">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                <?php if (isset($defConfParams['invoice_product']) && count($defConfParams['invoice_product']) > 0) {
                                    foreach ($defConfParams['invoice_product'] AS $i => $invoiceProduct): ?>
                                        <tr>
                                            <td class="label"><label
                                                        for="invoice_product"><?php echo Mage::helper('dhllabel')->__('Product ' . ($i + 1)); ?>
                                                    <span class="required">*</span></label>
                                            </td>
                                            <td class="value">
                                                <label for="invoice_product_<?php echo $i; ?>_enable"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span style="display: inline-block; width: 45px;"></span>
                                                    <input type="checkbox"
                                                           name="invoice_product[<?php echo $i; ?>][enable]"
                                                           id="invoice_product_<?php echo $i; ?>_enable" value="1"
                                                           checked="checked"
                                                           class="invoice_product_enable"></label><br/>
                                                <label for="invoice_product_<?php echo $i; ?>_name"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Name'); ?>
                                                        :</span>
                                                    <input type="text"
                                                           name="invoice_product[<?php echo $i; ?>][name]"
                                                           id="invoice_product"
                                                           id="invoice_product_<?php echo $i; ?>_name"
                                                           value="<?php echo $invoiceProduct['name']; ?>"
                                                           class="input-text"></label><br/>
                                                <label for="invoice_product_<?php echo $i; ?>_price"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Price'); ?>
                                                        :</span>
                                                    <input type="text"
                                                           name="invoice_product[<?php echo $i; ?>][price]"
                                                           id="invoice_product_<?php echo $i; ?>_price"
                                                           value="<?php echo round($invoiceProduct['price'], 2); ?>"
                                                           class="input-text invoice_product_price"></label><br/>
                                                <label for="invoice_product_<?php echo $i; ?>_qty"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Qty'); ?>
                                                        :</span>
                                                    <input type="text" name="invoice_product[<?php echo $i; ?>][qty]"
                                                           id="invoice_product_<?php echo $i; ?>_qty"
                                                           value="<?php echo round($invoiceProduct['qty'], 2); ?>"
                                                           class="input-text invoice_product_qty"></label><br/>
                                                <!--<label for="invoice_product_<?php echo $i; ?>_weight" style="display: inline-block; padding-bottom: 7px;">
                                                    <span style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Weight'); ?>:</span>-->
                                                <input type="hidden" name="invoice_product[<?php echo $i; ?>][weight]"
                                                       value="<?php echo round($invoiceProduct['weight'], 2); ?>"
                                                       id="invoice_product_<?php echo $i; ?>_weight"
                                                       class="required-entry input-text"><!--</label><br/>-->
                                                <label for="invoice_product_<?php echo $i; ?>_commodity_type"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Commodity type'); ?>
                                                        :</span>
                                                    <input type="text" name="invoice_product[<?php echo $i; ?>][commodity_type]"
                                                           value="<?php echo $invoiceProduct['commodity_type']; ?>"
                                                           id="invoice_product_<?php echo $i; ?>_commodity_type"
                                                           class="input-text">
                                                </label>
                                                <label for="invoice_product_<?php echo $i; ?>_commodity_code"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Commodity code'); ?>
                                                        :</span>
                                                    <input type="text" name="invoice_product[<?php echo $i; ?>][commodity_code]"
                                                           value="<?php echo $invoiceProduct['commodity_code']; ?>"
                                                           id="invoice_product_<?php echo $i; ?>_commodity_code"
                                                           class="input-text">
                                                </label>
                                                <label for="invoice_product_<?php echo $i; ?>_dangerous_goods"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Dangerous goods'); ?>
                                                        :</span>
                                                    <select name="invoice_product[<?php echo $i; ?>][dangerous_goods]" id="invoice_product_<?php echo $i; ?>_dangerous_goods">
                                                        <option value="0" <?php echo !isset($invoiceProduct['dangerous_goods']) || $invoiceProduct['dangerous_goods'] == '' ||  $invoiceProduct['dangerous_goods'] == 0?' SELECT':''; ?>><?php echo Mage::helper('dhllabel')->__('No'); ?></option>
                                                        <option value="1" <?php echo isset($invoiceProduct['dangerous_goods']) && $invoiceProduct['dangerous_goods'] == 1?' SELECT':''; ?>><?php echo Mage::helper('dhllabel')->__('Yes'); ?></option>
                                                    </select>
                                                </label>
                                                <label for="invoice_product_<?php echo $i; ?>_dg_attribute_label"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Dangerous Label'); ?>
                                                        :</span>
                                                    <input type="text" name="invoice_product[<?php echo $i; ?>][dg_attribute_label]"
                                                           value="<?php echo $invoiceProduct['dg_attribute_label']; ?>"
                                                           id="invoice_product_<?php echo $i; ?>_dg_attribute_label"
                                                           class="input-text">
                                                </label>
                                                <label for="invoice_product_<?php echo $i; ?>_dg_attribute_content_id"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Dangerous Goods Content ID'); ?>
                                                        :</span>
                                                    <input type="text" name="invoice_product[<?php echo $i; ?>][dg_attribute_content_id]"
                                                           value="<?php echo $invoiceProduct['dg_attribute_content_id']; ?>"
                                                           id="invoice_product_<?php echo $i; ?>_dg_attribute_content_id"
                                                           class="input-text">
                                                </label>
                                                <label for="invoice_product_<?php echo $i; ?>_dg_attribute_uncode"
                                                       style="display: inline-block; padding-bottom: 7px;">
                                                    <span
                                                            style="display: inline-block; width: 45px;"><?php echo Mage::helper('dhllabel')->__('Dangerous UNCode'); ?>
                                                        :</span>
                                                    <input type="text" name="invoice_product[<?php echo $i; ?>][dg_attribute_uncode]"
                                                           value="<?php echo $invoiceProduct['dg_attribute_uncode']; ?>"
                                                           id="invoice_product_<?php echo $i; ?>_dg_attribute_uncode"
                                                           class="input-text">
                                                </label>
                                                <input type="hidden" name="invoice_product[<?php echo $i; ?>][id]"
                                                       value="<?php echo $invoiceProduct['id']; ?>"
                                                       class="required-entry input-text">
                                            </td>
                                        </tr>
                                    <?php endforeach;
                                } ?>
                                </tbody>
                            </table>
                            <?php if (isset($defConfParams['invoice_declared_value'])): ?>
                                <input type="hidden" id="count_product_for_invoice"
                                       value="<?php echo count($defConfParams['invoice_product']) ?>"/>
                                <input name="invoice_declared_value" class="input-text" type="hidden"
                                       value="<?php echo $defConfParams['invoice_declared_value']; ?>">
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style type="text/css">
        #defaultPrice_negotiatedPrice {
            display: none;
        }

        .defaultPrice, .negotiatedPrice {
            display: none;
        }
    </style>
    <div class="f-right" style="clear:both;">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
        <button type="button" class="scalable save submit-button"
                onclick="if(editForm.submit()) disableElements('submit-button');" style="">
            <span><?php echo Mage::helper('dhllabel')->__('Submit'); ?></span></button>
    </div>
    </form>
    <script type="text/javascript">
        if (typeof window.$("box_package_count").on === 'undefined') {
            Event.Handler = Class.create({
                initialize: function (element, eventName, selector, callback) {
                    this.element = $(element);
                    this.eventName = eventName;
                    this.selector = selector;
                    this.callback = callback;
                    this.handler = this.handleEvent.bind(this);
                },

                start: function () {
                    Event.observe(this.element, this.eventName, this.handler);
                    return this;
                },

                stop: function () {
                    Event.stopObserving(this.element, this.eventName, this.handler);
                    return this;
                },

                handleEvent: function (event) {
                    var element = Event.findElement(event, this.selector);
                    if (element) this.callback.call(this.element, event, element);
                }
            });
            function on(element, eventName, selector, callback) {
                element = $(element);
                return new Event.Handler(element, eventName, selector, callback).start();
            }

            Element.addMethods({
                on: on
            });
        }
        editForm = new varienForm('edit_form', '');
        function getShipmentPrice() {
            var serializeForm = $("edit_form").serialize(true);

            $('defaultPrice_negotiatedPrice').setStyle({display: 'none'});
            $$('.defaultPrice')[0].setStyle({display: 'none'});
            $$('.negotiatedPrice')[0].setStyle({display: 'none'});

            new Ajax.Request("<?php echo $this->getUrl('adminhtml/dhllabel_dhllabel/showlabel/order_id/' . $this->getRequest()->getParam('order_id') . '/shipment_id/' . $this->getRequest()->getParam('shipment_id') . '/type/ajaxprice_' . $this->getRequest()->getParam('type')); ?>",
                {
                    method: "post",
                    parameters: serializeForm,
                    onSuccess: function (o) {
                        o = o.responseText.evalJSON();
                        if (o.error) {
                            alert("Error: " + o.error[0]);
                        }
                        else {
                            $('defaultPrice_negotiatedPrice').setStyle({display: 'block'});
                            $$('.defaultPrice')[0].setStyle({display: 'block'});
                            $$('.defaultPrice span')[0].innerHTML = o.price.def.MonetaryValue[0] + ' ' + o.price.def.CurrencyCode[0];
                            if (o.price.negotiated.MonetaryValue[0].length > 0) {
                                $$('.negotiatedPrice')[0].setStyle({display: 'block'});
                                $$('.negotiatedPrice span')[0].innerHTML = o.price.negotiated.MonetaryValue[0] + ' ' + o.price.negotiated.CurrencyCode[0];
                            }
                        }
                    }
                });
        }
        <?php /*if ($this->getRequest()->getParam('type') == 'shipment'):*/ ?>
        $("add_package_func").observe("click", function () {
            $$("#box_package_count .package_count div.fieldset").invoke("hide");
            $$("#box_package_count .package_count .collapseable a.open").invoke("addClassName", "close");
            $$("#box_package_count .package_count .collapseable a.open").invoke("removeClassName", "open");
            $("box_package_count").insert({
                bottom: '<div class="entry-edit package_count">' +
                '<div class="entry-edit-head collapseable">' +
                '<a href="#" class="open"><?php echo Mage::helper('dhllabel')->__('Package'); ?> ' + ($$(".package_count").length + 1) + '<span class="delete_package" style="float: right;margin-right: 50px;"><?php echo Mage::helper('dhllabel')->__('Delete Package'); ?></span></a>' +
                '</div>' + $("box_script_package_count").innerHTML + "</div>"
            });
        });
        var handler1 = $("box_package_count").on("click", ".package_count .collapseable a.close", function (e, el) {
            $$("#box_package_count .package_count div.fieldset").invoke("hide");
            $$("#box_package_count .package_count .collapseable a.open").invoke("addClassName", "close");
            $$("#box_package_count .package_count .collapseable a.open").invoke("removeClassName", "open");
            el.up().next().show();
            el.removeClassName("close");
            el.addClassName("open");
            handler2.stop();
            handler2.start();
            Event.stop(e)
        });
        var handler2 = $("box_package_count").on("click", ".package_count .collapseable a.open", function (e, el) {
            el.up().next().hide();
            el.addClassName("close");
            el.removeClassName("open");
            handler1.stop();
            handler1.start();
            Event.stop(e)
        });

        var handler3 = $("box_package_count").on("click", ".delete_package", function (e, el) {
            el.up(2).remove();
            handler1.stop();
            handler1.start();
            handler2.stop();
            handler2.start();
            Event.stop(e)
        });
        <?php /*endif;*/ ?>
        document.observe('dom:loaded', function () {
            $$('.invoice_product_enable').invoke('observe', 'change', setDeclaredValue);
            $$('.invoice_product_price').invoke('observe', 'keyup', setDeclaredValue);
            $$('.invoice_product_qty').invoke('observe', 'keyup', setDeclaredValue);
        });
        function setDeclaredValue(e) {
            var countProduct = $("count_product_for_invoice").value, price = 0;
            for (var i = 0; i < countProduct; i++) {
                if ($("invoice_product_" + i + "_enable") && $("invoice_product_" + i + "_enable").checked == true) {
                    price += parseFloat($("invoice_product_" + i + "_price").value, 10) * parseInt($("invoice_product_" + i + "_qty").value, 10);
                }
            }
            $('declaredValue').value = price;
        }
        function updateCorrectCity() {
            document.getElementById("shiptocity").value = document.getElementById("shiptocityselect").value;
            // if empty service list due to wrong city on correction of city update Express worldwide for KSA
            servicCodes = document.getElementById("serviceGlobalCode");
            if(servicCodes.length == 0){
                servicCodes.options[servicCodes.length] = new Option('Express worldwide (WPX, NON DOC)','P');
            }
        }
    </script>
    <style type="text/css">
        .delete_package:hover {
            text-decoration: underline;
        }
    </style>
<?php if (count($defParams) > 0/*$this->getRequest()->getParam('type') == 'shipment'*/): ?>
    <script type="text/html" id="box_script_package_count">
        <div class="np fieldset">
            <div>
                <div class="content">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                            <tr>
                                <td class="label">
                                    <label><?php echo Mage::helper('dhllabel')->__('Weight'); ?> <span
                                                class="required">*</span></label>
                                </td>
                                <td class="value">
                                    <input type="text" value="" name="package[weight][]"
                                           class="input-text  required-entry">
                                </td>
                            </tr>
                            <tr>
                                <td class="label">
                                    <label><?php echo Mage::helper('dhllabel')->__('Pack weight'); ?></label>
                                </td>
                                <td class="value">
                                    <input type="text" name="package[packweight][]"
                                           value="<?php echo $defParams[0]['packweight']; ?>"
                                           class=" input-text">
                                </td>
                            </tr>
                            <tr>
                                <td class="label">
                                    <label><?php echo Mage::helper('dhllabel')->__('Depth'); ?></label>
                                </td>
                                <td class="value">
                                    <input type="text" value="" name="package[depth][]" class="input-text">
                                </td>
                            </tr>
                            <tr>
                                <td class="label">
                                    <label><?php echo Mage::helper('dhllabel')->__('Width'); ?></label>
                                </td>
                                <td class="value">
                                    <input type="text" value="" name="package[width][]" class="input-text">
                                </td>
                            </tr>
                            <tr>
                                <td class="label">
                                    <label><?php echo Mage::helper('dhllabel')->__('Height'); ?></label>
                                </td>
                                <td class="value">
                                    <input type="text" value="" name="package[height][]" class="input-text">
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </script>
<?php endif; ?>