<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.6
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt 
 */
?>
<?php 
/**
 * Initilising downloadable product options like
 * sample count
 * link count
 */
$sampleCount = $linkCount = 0;
?>
<script type="text/javascript">
$( document ).ready(function() {
    $('#supplier_sku').attr('readonly', 'readonly');
});

var addProductForm = new VarienForm('edit_exist_product_form', true);
function checkTextarea() {
    var nicEdit = new nicEditors.findEditor('short_description');
    var questionVar = nicEdit.getContent();
    if (questionVar == '') {
        $('short_description').show();
        $('short_description').setStyle({
            'width': '529px',
            'margin-top': '-140px',
            'border': 'none !important',
            'background': 'none !important',
            'padding': '0px',
            'position': 'absolute',
            'z-index': '-1'
        });
    }
    var nicEdit = new nicEditors.findEditor('description');
    var questionVar = nicEdit.getContent();
    if (questionVar == '') {
        $('description').show();
        $('description').setStyle({
            'width': '529px',
            'margin-top': '-140px',
            'border': 'none !important',
            'background': 'none !important',
            'padding': '0px',
            'position': 'absolute',
            'z-index': '-1'
        });

    }
}
</script>
<!-- Product SKU available or not -->
<script type="text/javascript">
$('sku').observe('keyup', function(event) { 
//alert($('sku_for_avail').getValue());	
validateSkuForAddProduct();	
});

function validateSkuForAddProduct(){
    var inputskuVar = $('sku').getValue();
    var emptycheck = inputskuVar.replace(/^\s+/, '').replace(/\s+$/, '');
    var sku = inputskuVar.trim().length;
    if (sku === 0 && emptycheck === '') {      
        $('empty-text').setStyle({display: 'block'});     
        $('not-available').setStyle({display: 'none'});
        $('available').setStyle({display: 'none'});
    } else {

    $('not-available').setStyle({display: 'none'});
    $('available').setStyle({display: 'none'});  
    $('empty-text').setStyle({display: 'none'});
       
    $('category-loading').show(); 
        new Ajax.Request("<?php echo Mage::getBaseUrl(); ?>marketplace/product/checksku/", {
            method: "get",
            parameters: {sku: inputskuVar},
            onSuccess: successFunc
        });
    } 	
}

function validateSupplierSkuForAddProduct(){

        var inputskuData = $('supplier_sku').getValue();
        var input_save_sku = $('supplier_sku_for_avail').getValue();
        var emptycheck = inputskuData.replace(/^\s+/, '').replace(/\s+$/, '');
        var sku = inputskuData.trim().length;
        if (sku === 0 && emptycheck === '') {
            $('not-available2').setStyle({display: 'none'});
            $('available2').setStyle({display: 'none'});  
            $('empty-text2').setStyle({display: 'block'});              
        }
        else if(inputskuData == input_save_sku){
           return;
        } else {         
           $('empty-text2').setStyle({display: 'none'});
           $('available2').setStyle({display: 'none'});
           $('not-available2').setStyle({display: 'none'});            
            
        $('category-loading2').setStyle({display:'block'});
            new Ajax.Request("<?php echo Mage::getBaseUrl(); ?>marketplace/product/checksuppliersku/", {
                method: "get",
                parameters: {sku: inputskuData},
                onSuccess: successSupplierFunc
            });
        }
    }

function successSupplierFunc(response) {
        $('category-loading2').hide(); 
          var inputskuData = $('supplier_sku').getValue();
        var sku = inputskuData.length;     
        
        if (sku === 0) {
         $('available2').setStyle({display: 'none'});
            $('empty-text2').setStyle({display: 'block'});
            $('not-available2').setStyle({display: 'none'});
            skuAvailableFlag = 1;             
            return;
        }else{           
          var content = response.responseText;
          if (content == 0) {    
          $('not-available2').setStyle({display: 'none'});  
          $('category-loading2').setStyle({display:'none'});         
              $('available2').setStyle({display: 'block'});                       
              $('empty-text2').setStyle({display: 'none'});
              skuAvailableFlag = 0;
          } else {
          $('empty-text2').setStyle({display: 'none'});
          $('category-loading2').setStyle({display:'none'});
          $('not-available2').setStyle({display: 'block'});             
          $('available2').setStyle({display: 'none'});  
          skuAvailableFlag = 1;                  
          }
          }
      }

//Check sku empty validation
function checkSkuValidation(){
    var inputskuVar = $('sku').getValue();
    var sku = inputskuVar.length;
    if (sku === 0) {
        $('empty-text').setStyle({display: 'block'});
        $('available').setStyle({display: 'none'});
        $('not-available').setStyle({display: 'none'});  
        $('sku').setStyle({'border-color': 'red'});           
        return false;
    }
    $('sku').setStyle({'border-color': '#ccc'}); 
    return true;
}

function successFunc(response) {  
$('category-loading').hide(); 
  var inputskuVar = $('sku').getValue();
      var sku = inputskuVar.length;      
    var content = response.responseText;
        
    if (content == 0) {
        $('available').setStyle({display: 'block'});
        $('not-available').setStyle({display: 'none'});
        $('empty-text').setStyle({display: 'none'});
    }
    else {
        $('available').setStyle({display: 'none'});
        $('not-available').setStyle({display: 'block'});
        $('empty-text').setStyle({display: 'none'});
    }

    if (sku === 0) {
        $('empty-text').setStyle({display: 'block'});
        $('not-available').setStyle({display: 'none'});
        $('available').setStyle({display: 'none'});
        return;
    } 
}
</script>

<!-- Special to date picket -->
<script type="text/javascript">
//<![CDATA[
/*Calendar.setup({
    inputField: "special_to_date",
    ifFormat: "%m/%e/%Y",
    showsTime: false,
    button: "special_to_date_trig",
    align: "Bl",
    singleClick: true
});*/
//]]>
</script>

<!-- Special from date picket -->
<script type="text/javascript">
//<![CDATA[
/*Calendar.setup({
	inputField: "special_from_date",
	ifFormat: "%m/%e/%Y",
	showsTime: false,
	button: "special_from_date_trig",
	align: "Bl",
	singleClick: true
});
*///]]>
</script>

<!-- Category child node show/hide -->
<script type="text/javascript">
$$('.block-category li.parent ul').each(function(item) {
    item.hide();
});

$$('.block-category li.parent > a span').each(function(element) {
    element.observe('click', function(e) {
        e.element().toggleClassName('end-minus', true);
        e.element().toggleClassName('end-plus', true);
        var idd = e.element().up().next('ul');
        Effect.toggle(idd, 'blind', {duration: 0.5});

        e.preventDefault();
    });
    element.observe('dblclick', function(e) {
        e.element().toggleClassName('end-minus', true);
        e.element().toggleClassName('end-plus', true);
        var idd = e.element().up().next('ul');
        Effect.toggle(idd, 'blind', {duration: 0.5});

        e.preventDefault();
    });
});
</script>

<!-- Multiple image upload -->
<script type="text/javascript">
var fields = 0;
function addNewImage() {
    var id = "image" + fields;
    $("marketplace_image_list").insert("<div class='market_place_add_image'><div class='base-image'><div class='file' style='width: 100% !important;'><span class='ftitle'>Choose File</span><span class='fpath'>No File Selected</span></div><input type='file' name='" + id + "' class='ufile' /></div><div class='base-image'><input id='set_base_image_"+id+"' type='radio' name='setbase' value ='" + fields + "'/></div><div class='base-image'><input id='set_thumb_image_"+id+"' type='radio' name='setthumb' value ='" + fields + "'/></div><div class='base-image'><input id='set_small_image_"+id+"' type='radio' name='setsmall' value ='" + fields + "'/></div><a style='text-decoration: none;font-size: 12px;' type='button' class='button2' onclick='removeAddedImage(this)' /><i class='fa fa-times-circle-o fa-lg'></i>  <?php
echo $this->__( 'Remove' );?></a>");
    fields += 1;
}
function removeAddedImage(value) {
    value.up('div').remove();
}
</script>

<!-- Product custom option and dynamically add downloadable product data -->
<script type="text/javascript">
function removeMarketPlaceCustomOption(value) {
    value.up('div').remove();
}

function changeMarketPlaceCustomOption(value, option_value) {
    var child_html;
    var child_custom_option_value = value.getValue();
    switch (child_custom_option_value) {   
        case "drop_down":
        case "radio":
        case "checkbox":
        case "multiple":
            child_html = $("product_option_CCC_type_select").innerHTML.replace(/CCC/g, option_value);
            break; 
        case "field":
        case "area":
            child_html = $("product_option_CCC_type_text").innerHTML.replace(/CCC/g, option_value);
            break;     
        case "date":
        case "date_time":
        case "time":
            child_html = $("product_option_CCC_type_date").innerHTML.replace(/CCC/g, option_value);
            break;      
        case "file":
            child_html = $("product_option_CCC_type_file").innerHTML.replace(/CCC/g, option_value);
            break;  
        default :
            child_html = $("product_option_CCC_type_text").innerHTML.replace(/CCC/g, option_value);
    }
    if (value.up('table').nextSiblings('table') != '')
    {
        value.up('table').next('table').remove();
        value.up('div').insert(child_html);
    }
    else
    {
        value.up('div').insert(child_html);
    }
}

function removeMarketPlaceChildSelectOption(value) {
    value.up('tr').remove();
}

function addMarketPlaceChildSelectOption(value, sub_option_value) {

    var selectChildCustomOption = $("product_option_CCC_select_AAA").innerHTML.replace(/CCC/g, sub_option_value);
    var new_selectChildCustomOption = selectChildCustomOption.replace(/AAA/g, selectSubChildCustomOptionCount);
    $(value).insert(new_selectChildCustomOption);
    selectSubChildCustomOptionCount = selectSubChildCustomOptionCount + 1;

}
var marketplaceDownloadableSampleRow = <?php echo $sampleCount; ?>;
var marketplaceDownloadableLinkRow = <?php echo $linkCount; ?>;
function addMarketPlaceDownloadableSamplesRow(value) {
    var selectSampleOption = $("marketplace_download_sample_row_CCC").innerHTML.replace(/CCC/g, marketplaceDownloadableSampleRow);
    $(value).insert(selectSampleOption);
    marketplaceDownloadableSampleRow = marketplaceDownloadableSampleRow + 1;
}

function addMarketPlaceDownloadableLinksRow(value) {
    var selectLinkOption = $("marketplace_download_link_row_CCC").innerHTML.replace(/CCC/g, marketplaceDownloadableLinkRow);
    $(value).insert(selectLinkOption);
    marketplaceDownloadableLinkRow = marketplaceDownloadableLinkRow + 1;
}

function removeMarketPlaceDownloadableSamplesRow(value) {
    value.up('tr').remove();
}

//Hiding existing sample, link and link sample files name
function hideOldFileName(id)
{
    var hide_div = id + '-old';
    $(hide_div).hide();
}

function removeMarketPlaceDownloadableLinksRow(value) {
    value.up('table').remove();
}


//For text editor
//<![CDATA[
bkLib.onDomLoaded(function() {
  new nicEditor({iconsPath: '<?php echo $this->getSkinUrl('marketplace/nicEditorIcons.gif'); ?>'}).panelInstance('short_description');
});
//]]>

// For text editor
//<![CDATA[
bkLib.onDomLoaded(function() {
    new nicEditor({iconsPath: '<?php echo $this->getSkinUrl('marketplace/nicEditorIcons.gif'); ?>'}).panelInstance('description');
});
//]]>
</script>
<script type="text/javascript">

function sellerShippingFunctionChange(){
    var selected = $('seller_shipping').select("option[selected]")[0].innerHTML;
    if (selected == 'Shipping Cost') {
        $('shipping_price').setStyle('display:block');
    } else  {
    $('shipping_price').setStyle('display:none');
        $('national_shipping_price').value = '0';
    $('international_shipping_price').value = '0';
    }
}

document.observe("dom:loaded", function() {
if($('seller_shipping')){
    var shippingoption = $('seller_shipping').select("option[selected]")[0].innerHTML;    
    if(shippingoption == 'Shipping Cost'){       
      $('shipping_price').setStyle('display:block');  
    }
} 
});
$('button').observe('click', function() { 
		var checkedAtLeastOne = false;
		$j('.selected-check').each(function() {
			if ($j(this).is(":checked")) {
				checkedAtLeastOne = true;
			}
		});
		
		if (!checkedAtLeastOne) { 
			$j('.block-category .ch-box-err').html('Please select category').fadeIn('slow');
			//$j('html, body').animate({scrollTop:$j('.block-category .ch-box-err').position().top-100 }, 'slow');
		} else { 
			$j('.block-category').find('.ch-box-err').html('');
		}
	});

</script>
<script>
    jQuery(document).ready(function($) {
		
		$(".selectpicker2").select2();
		
        var max_fields      = 8; //maximum input boxes allowed
        var wrapper         = $(".desc_fields_wrap"); //Fields wrapper
        var add_button      = $(".desc_add_field_btn"); //Add button ID

        var x = 1; //initlal text box count
        /*$(add_button).click(function(e){ //on add input button click
            e.preventDefault();
            if(x < max_fields){ //max input box allowed
                x++; //text box increment
                $(wrapper).append('<div class="input-box"><input class="input-text" type="text" name="descriptionLine[]"/><a href="#" class="remove_field">Remove</a></div>'); //add input box
            }
        });*/
		$(wrapper).on('click', ".desc_add_field_btn", function(e){ //on add input button click
            e.preventDefault();
            if(x < max_fields){ //max input box allowed
                x++; //text box increment
				$(this).hide();
                $(wrapper).append('<div class="input-box"><input class="input-text" type="text" name="descriptionLine[]"/><a href="#" class="remove_field"><i class="fa fa-times-circle-o fa-lg"></i></a> &nbsp; <button class="desc_add_field_btn"> <span> Add Another </span> </button></div>'); //add input box
            }
        });

        $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
            e.preventDefault(); 
			var prevEle = $(this).parent().prev().find('.desc_add_field_btn');
			$(this).parent('div').remove();
			var addBtnShow = false;
			$(".desc_add_field_btn").each(function() {
				if ( $(this).css('display')=='inline-block') { 
					addBtnShow = true;
				}
			}); 
			if (addBtnShow==false) { prevEle.show(); }
			x--;
        });

        $(wrapper).on("change",".input-text", function(){ //Actually modify text in description
            console.log("Changed...");
            var htmlDesc = "<ul>";
            jQuery('[name*="descriptionLine"]').each(function(){
                console.log("+"+jQuery(this).val());
                htmlDesc += "<li>" + jQuery(this).val() + "</li>";
            });
            htmlDesc += "</ul>";
            jQuery('#description').attr('value', htmlDesc);
            jQuery('#description').parent('div').find('div.nicEdit-main').html(htmlDesc);
        });
    });

    //ensure the seller selects the leaf (deepest category)
    jQuery(document).ready(function(){
        jQuery('form .marketplace-category-type .block-category input[type="checkbox"]').on('click', function(){
            var child_ul = jQuery(this).closest('li.parent').find('ul.category_ul');
            if(child_ul.length > 0){
                $j('.block-category .ch-box-err').html('You cannot choose a parent category, please pick a specific child category.').fadeIn('slow');
				$j('html, body').animate({scrollTop:$j('.block-category .ch-box-err').position().top-100 }, 'slow');
                jQuery(this).attr('checked', false);
                //Deselect everything
                jQuery('form .marketplace-category-type .block-category input[type="checkbox"]').prop('checked', false);
				return;
            } else {
                //count selections and make sure there are not multiple selections
                var checked_count = jQuery('form .marketplace-category-type .block-category input:checked').length;
                jQuery(this).parents('li.parent').each(function(key, val){
					
                    jQuery(val).find('input[type="checkbox"]:first').prop('checked', true);
                    //find('input[type="checkbox"]').attr('checked', true);
                })
                if(checked_count > 1) {
                    $j('.block-category .ch-box-err').html('Multiple selections are not allowed.').fadeIn('slow');
					$j('html, body').animate({ scrollTop: $j('.block-category .ch-box-err').position().top-100 }, 'slow');
                    jQuery(this).prop('checked', false);
					return;
                }
            }
        })
    });
</script>