<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.6
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 */
?>
<?php
/**
 * Assign posted values in varibles like
 * filter_id
 * filter_name
 * filter_price
 * filter_quantity
 * filter_status
 * filterProductType
 */

$store = Mage::app()->getStore();
$storeID = Mage::app()->getStore()->getStoreId();
$currency_symbol = Mage::app()->getStore($storeID)->getCurrentCurrencyCode();
$locale = Mage::app()->getLocale()->getLocaleCode();

$filter_id = $this->getRequest()->getParam('filter_id');
$filter_name = $this->getRequest()->getParam('filter_name');
$filter_price = $this->getRequest()->getParam('filter_price');
$filter_quantity = $this->getRequest()->getParam('filter_quantity');

$filter_status = $this->getRequest()->getParam('filter_status');
$filterProductType = $this->getRequest()->getParam('filter_product_type');
?>
<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $sellerData = Mage::getSingleton('customer/session')->getCustomer();
    $sellerId = $sellerData->getId();
    //$allowedAmount = $this->availablePayoutAmount($sellerId); Edit by Ali. This function is not giving correct value so used the function created by Azhar
    /*-------------------------Edited by Azhar 05-16-2016--------------------------*/
    $allowedAmount = Mage::helper('marketplace/marketplace')->getSellerAccountsDetail($sellerId);
    $getPendingAmount =
        Mage::helper('marketplace/marketplace')->getSellerTotalPayoutRequestAmount($sellerId, 'Pending');
    $getApproveAmount =
        Mage::helper('marketplace/marketplace')->getSellerTotalPayoutRequestAmount($sellerId, 'Approve');
    $getPaidAmount = Mage::helper('marketplace/marketplace')->getSellerTotalPayoutRequestAmount($sellerId, 'Paid');
    $getOrderRefundAmount = Mage::helper('marketplace/marketplace')->getOrderRefundAmount($sellerId);
    $getSellerTotalPayoutRequestAmount = $getPendingAmount + $getApproveAmount + $getPaidAmount;
    $finalRemainingAmount = $allowedAmount['seller_amount'] - $getSellerTotalPayoutRequestAmount;
    $finalRemainingAmount = $finalRemainingAmount - $getOrderRefundAmount;
    /*-------------------------------------------------*/

}
?>
<div class="account-login market_place_manage_products" id="market_place_manage_products">
    <div class="page-title">
        <h1 class="manage_products_head"><?php echo $this->__('Manage Products') ?></h1>
    </div>
    <div class="my-account-wrapper">
        <div class="page-title sellers_store mp_order_transaction" id="mp_order_transaction">

            <?php //Display remaining amount and received amount from admin ?>
            <div class="top_amount">

                <?php if ($getPaidAmount): ?>
                    <span class="right_space">
                <?php echo $this->__('Total Lifetime Amount Received') ?> : <b><?php //echo $totalPaid; ?>
                            <span><?php if ($locale == "ar_SA") {
                                    echo $this->__($currency_symbol);
                                } ?></span>
                            <?php echo Mage::helper('core')->currency($getPaidAmount, true, false); ?>
                </b>
            </span>
                    <br>
                <?php endif; ?>
                <br>
                <?php if ($getApproveAmount): ?>
                    <span class="right_space">
                <?php echo $this->__('Approved by Admin') ?> : <b>
                <span><?php if ($locale == "ar_SA") {
                        echo $this->__($currency_symbol);
                    } ?></span>
                            <?php
                            echo Mage::helper('core')->currency($getApproveAmount, true, false); ?></b>
            </span>
                <?php endif; ?>
                <br>
                <?php if ($getPendingAmount): ?>
                    <span class="right_space">
                <?php echo $this->__('Waiting for Admin Approval') ?> : <b>
                <span><?php if ($locale == "ar_SA") {
                        echo $this->__($currency_symbol);
                    } ?></span>
                            <?php
                            echo Mage::helper('core')->currency($getPendingAmount, true, false); ?></b>
            </span>
                <?php endif; ?>
                <br>
                <span>
           
            <?php echo $this->__('Remaining Amount') ?> :  <b>
                <span><?php if ($locale == "ar_SA") {
                        echo $this->__($currency_symbol);
                    } ?></span>
                        <?php echo Mage::helper('core')->currency($finalRemainingAmount, true, false); ?></b>
        </span>
            </div>
        </div>
        <div class="clear"></div>
        <button onclick="window.location='<?php echo Mage::helper('marketplace/url')->getCreateProductUrl(); ?>';"
                title="<?php
                echo $this->__('Add New Product'); ?>" class="button right mp_addnew_pdt"><?php
                    /**
                     * Display add new product option
                     */
                    echo $this->__('Add New Product'); ?></button>

        <form name="multiple_select" id="multiple_select" class="multiple_select" method="post"
              action="<?php echo $this->getmultiselectUrl(); ?>">
            <div class="mp_action"><b><?php echo $this->__('Action'); ?> </b>
                <select name="multi">
                    <option name="" value="Select an option"><?php echo $this->__('Select an option'); ?></option>
                    <?php
                    /**
                     * Display delete option
                     */
                    ?>
                    <?php if( Mage::getStoreConfig('marketplace/product/show_delete_action') ){ ?>
                        <option name="delete" value="delete"><?php echo $this->__('Delete'); ?></option>
                    <?php }?>
                    <?php if( Mage::getStoreConfig('marketplace/product/show_disable_action') ){ ?>
                        <option name="disable" value="disable"><?php echo $this->__('Disable'); ?></option>
                    <?php }?>
                    <option name="soldout" value="soldout"><?php echo $this->__('Sold out'); ?></option>
                    <option name="paused" value="paused"><?php echo $this->__('Paused'); ?></option>
                </select>

                <button type="submit" class="button multi_submit"
                        onclick="document.getElementById('multi_submit').value='1'; "
                        title="<?php echo $this->__('Submit') ?>" name="multi_submit" id="multi_submit">
                    <span><span><?php echo $this->__('Submit') ?></span></span></button>
            </div>
            <div style="clear: both;"></div>
            <div class="clear"></div>
            <div class="order-tabs">
                <!-- <ul id="orderTab" class="nav nav-tabs">
            <li><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage?filter_status=1" id="enabled">Approved</a></li>
            <li><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage?filter_status=2" id="disabled" >Pending Approved</a></li>
            <li><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage/" id="deleted" >Rejected</a></li>
            <li class="active" ><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage/" id="all">ALL</a></li>
        </ul> -->
                <ul id="orderTab" class="nav nav-tabs">
                    <li><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage?product_status=1023"
                           id="1023"><?php echo $this->__('Published') ?></a></li>
                    <li><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage?product_status=1024"
                           id="1024"><?php echo $this->__('Pending review') ?></a></li>
                    <li><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage?product_status=1025"
                           id="1025"><?php echo $this->__('Rejected') ?></a></li>
                    <li><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage?product_status=1026"
                           id="1026"><?php echo $this->__('Paused') ?></a></li>
                    <li><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage?product_status=1027"
                           id="1027"><?php echo $this->__('Sold out') ?></a></li>
                    <li class="active"><a href="<?php echo $this->getBaseUrl() ?>marketplace/product/manage/"
                                          id="all"><?php echo $this->__('ALL') ?></a></li>
                </ul>
            </div>
            <?php if (isset($_GET["product_status"]) && $_GET["product_status"] != ""):
                if ($_GET["product_status"] == '1023'):
                    $product_status = $_GET["product_status"];
                elseif ($_GET["product_status"] == '1024' || $_GET["product_status"] == '1025'
                        || $_GET["product_status"] == '1026'
                        || $_GET["product_status"] == '1027'
                ):
                    $product_status = $_GET["product_status"];
                else :
                    $product_status = '';
                endif ?>
                <script>
                    if (jQuery("#orderTab li a#<?php echo $product_status ?>").parent().hasClass('active')) {

                    } else {
                        jQuery('#orderTab li').removeClass('active');
                        jQuery("#orderTab li a#<?php echo $product_status ?>").parent().addClass('active');

                    }
                </script>
            <?php
            else:
            ?>
                <script>
                    if (jQuery("#orderTab li a#all").parent().hasClass('active')) {

                    } else {
                        jQuery('#orderTab li').removeClass('active');
                        jQuery("#orderTab li a#all").parent().addClass('active');

                    }
                </script>
            <?php endif ?>
            <?php echo $this->getMessagesBlock()->getGroupedHtml();
            $_products = $this->getCollection();
            /**
             * Set sno in collection
             */
            $sNo = 1;
            $current_page = Mage::getBlockSingleton('page/html_pager')->getCurrentPage();
            $getPageSize = $_products->getPageSize();
            /**
             * Checking current page is greater than or equal to 2
             */
            if ($current_page >= 2) {
                /**
                 * Checking current page is less than or equal to calculate page
                 */
                $cal_page = ceil($_products->getSize() / $getPageSize);
                if ($current_page <= $cal_page) {
                    $sNo = abs(($current_page * $getPageSize) - $getPageSize) + 1;
                } else {
                    $sNo = abs(($cal_page * $getPageSize) - $getPageSize) + 1;
                }
            } else {
                $sNo = 1;
            }
            ?>
            <table class="data-table my-product-table market_place_manage_products_table manage-products-datas-table
                <?php if (isset($_GET["product_status"]) && $_GET["product_status"] != "") { echo "helper_class"; }
                ?>" id="my-product-table">
                <col width="1"/>
                <col width="1"/>
                <col/>
                <col width="1"/>
                <col width="1"/>
                <col width="1"/>
                <span class="table_spinner" style="display: none;">
                    <img src="<?php echo $this->getSkinUrl('marketplace/images/bx_loader.gif') ?>" alt="">
                </span>
                <thead>
                <tr>
                    <th><?php echo $this->__('#') ?></th>
                    <th class="mtext_left"><?php echo $this->__('Id') ?></th>

                    <th colspan="3" width="33%" class="mtext_left"><?php
                        /**
                         * Display product Name, Quantity, Price, Type & Status
                         */
                        echo $this->__('Product Name') ?></th>
                    <th><?php
                        echo $this->__('Supplier Sku') ?></th>
                    <th><?php
                        echo $this->__('Quantity') ?></th>
                    <th><?php
                        echo $this->__('Price') ?></th>
                    <!-- <th width="12%"><?php
                    echo $this->__('Type') ?></th> -->
                    <th width="12%"><?php
                        echo $this->__('Status') ?></th>
                    <th class="no-border-right"><?php echo $this->__('Action') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php if ($_products->getSize()): ?>
                <tr class="search-fields">
                    <td colspan="4">
                        <input type="text" data-type="name" id="search-by-name" value=""
                               placeholder="<?php echo($this->__('Search by Name')) ?>">
                        <div id="search-by-name-btn" class="button multi_submit">
                            <span class="spinner" style="display:none">
                                <img src="<?php echo $this->getSkinUrl('marketplace/images/bx_loader.gif') ?>" alt="">
                            </span>
                            <?php echo($this->__('Search')) ?>
                        </div>
                    </td>
                    <td colspan="4">
                        <input type="text" data-type="sku" id="search-by-sku" value=""
                               placeholder="<?php echo($this->__('Search by SKU')) ?>">
                        <div id="search-by-sku-btn" class="button multi_submit">
                            <span class="spinner" style="display:none">
                                <img src="<?php echo $this->getSkinUrl('marketplace/images/bx_loader.gif') ?>" alt="">
                            </span>
                            <?php echo($this->__('Search')) ?>
                        </div>
                    </td>
                </tr>
                <?php foreach ($_products as $_product): ?>
                    <tr>
                        <td>
                            <input type="checkbox" name="id[]" id="id" value="<?php echo $_product->getId(); ?>"/>
                        </td>
                        <td class="mtext_left"><em><?php echo $_product->getId(); ?></em></td>
                        <td align="center" style="text-align: center !important; width: 17px; font-size: 23px;">
                            <?php
                            if ($_product->getTypeId() == "configurable"
                                && sizeof($_product->getTypeInstance()
                                                   ->getUsedProductIds()) > 0
                            ):
                                ?>
                                <span style="cursor: pointer" class="more"
                                      data-id="<?php echo $_product->getId(); ?>">+</span>
                            <?php else: ?>
                                <span style="cursor: pointer" class="more"
                                      data-id="<?php echo $_product->getId(); ?>"></span>
                                <?php
                            endif;
                            ?>
                        </td>
                        <td class="img_td" style="width: 10px !important;">
                            <?php
                            /**
                             * Check product status is equal to 1
                             */
                            if ($_product->getStatus() == 1) { ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                                    <img src="<?php echo $this->helper('catalog/image')
                                                              ->init($_product, 'small_image')
                                                              ->resize(55, 45); ?>" width="55" height="45" alt="<?php
                                    echo $_product->getName(); ?>"/>
                                    <div class="big_image">
                                        <img src="<?php echo $this->helper('catalog/image')
                                                                  ->init($_product, 'small_image')
                                                                  ->resize(146, 196); ?>" width="146" height="196"
                                             alt="<?php
                                             echo $_product->getName(); ?>"/>
                                        <div><h5><?php
                                                echo $_product->getName(); ?></h5>
                                            <p><?php
                                                echo $_product->getShortDescription(); ?></p></div>
                                    </div>
                                </a>
                            <?php } else { ?>
                                <img src="<?php echo $this->helper('catalog/image')
                                                          ->init($_product, 'small_image')
                                                          ->resize(55, 45); ?>" width="55" height="45" alt="<?php
                                echo $_product->getName(); ?>" title="<?php
                                echo $_product->getName(); ?>"/>
                            <?php } ?>
                        </td>
                        <td class="mtext_left" style="width:160px;">
                            <?php
                            /**
                             * Check the product status is equal to 1
                             */
                            if ($_product->getStatus() == 1) { ?>
                                <a href="<?php echo $_product->getProductUrl(); ?>"
                                   class="get_pdct_name manage_get_pdct_name"><?php
                                    echo $_product->getName(); ?>
                                </a>
                            <?php } else { ?>
                                <span class="get_pdct_name"><?php echo $_product->getName(); ?></span>
                            <?php } ?>
                            <?php
                            $categoryIdsCollection = $_product->getCategoryIds();
                            $count = count($categoryIdsCollection);
                            $cat = Mage::getModel('catalog/category')
                                       ->getCollection()
                                       ->addAttributeToSelect('category_id');
                            $incCatagory = 1;
                            /**
                             * Check the count of category is greater than 0
                             */
                            if ($count > 0) {
                                echo $this->__('(');
                                foreach ($categoryIdsCollection as $_categoryIds) {
                                    $cat = Mage::getModel('catalog/category');
                                    $cat->load($_categoryIds);
                                    ?>
                                    <a href="<?php echo $cat->getUrl(); ?>"><?php
                                        /**
                                         * Display category name
                                         */
                                        echo $cat->getName(); ?></a>
                                    <?php
                                    if ($incCatagory != $count) {
                                        echo ',';
                                    }
                                    $incCatagory = $incCatagory + 1;
                                }
                                echo $this->__(')');
                            } ?>
                        </td>

                        <?php if ($_product->getSupplierSku()): ?>
                            <td><?php echo "<span class='pro-sku'>".$_product->getSupplierSku()."</span>"; ?></td>
                        <?php else: ?>
                            <td><?php echo "<span class='pro-sku'>".$_product->getSku()."</span>"; ?></td>
                        <?php endif ?>
                        <td width="14%" style="width: 68px !important"><em>
                                <?php if ($_product->isSaleable()): ?>
                                    <?php echo $val = (int)Mage::getModel('cataloginventory/stock_item')
                                                               ->loadByProduct($_product)
                                                               ->getQty(); ?>
                                    <?php /*     $itemsinstock = 0;
                    foreach ($_product->getTypeInstance(true)->getUsedProducts ( null, $_product) as $simple) {
                        $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($simple)->getQty();
                        $stock = round($stock,2);
                         $simple->getName()." : $stock pieces";
                        //echo '<br/>';
                        $itemsinstock+= $stock;
                    }
                    echo $itemsinstock." Items";*/ ?>
                                <?php else: ?><?php
                                    /**
                                     * Display out of stock message
                                     * If the product is nto available for sale
                                     * or the product has been sold out fully
                                     */
                                    echo $this->__('Out of Stock');
                                endif; ?>
                            </em>
                        </td>


                        <td style="width: 13%;text-align: center;padding-right: 4px !important;"
                            data-id="<?php echo $_product->getId() ?>" data-price="<?php echo $_product->getPrice() ?>">
                            <em onclick="getNewPrice(this)">
                                <?php
                                if ($locale == "ar_SA") {
                                    echo $this->__($currency_symbol);
                                } ?>
                                <?php echo Mage::helper('core')->currency($_product->getPrice(), true, false); ?></em>
                        </td>
                        <!-- <td width="12%"><?php echo ucfirst($_product->getTypeId()); ?></td>  -->
                        <td width="12%">
                            <!-- <em><span> -->
                            <!-- <select name="product_status" style="width: 87px" data-id="<?php echo $_product->getId() ?>">
                    <option value="1" <?php echo $_product->getStatus() ? 'selected' : ''; ?>>Enabled</option>
                    <option value="0" <?php echo $_product->getStatus() ? '' : 'selected'; ?>>Disabled</option>
                </select> -->
                            <?php if ($_product->getStatus() == 1):
                                echo $this->__('Published');
                            else:
                                echo $this->__('Unpublished');
                            endif;
                            ?>
                            <?php
                            /**
                             * Checking product status is 1
                             */

                            // if($_product->getStatus()==1):
                            // echo $this->__('Enabled');
                            // else:
                            // echo '<em>'.$this->__('Disabled').'</em>';
                            // endif; ?>
                            <!-- </span></em> -->

                        </td>

                        <td style="width: 120px;"><em>
                <span class="nobr"><a href="<?php echo Mage::getUrl('marketplace/product/edit/',
                        array('id' => $_product->getId())); ?>">
                <img src="<?php echo $this->getSkinUrl('marketplace/images/edit.png') ?>" alt="" title="<?php
                /**
                 * Display edit Option
                 */
                echo $this->__('Edit') ?>"/></a>

                 <?php if( Mage::getStoreConfig('marketplace/product/show_delete_action') ){ ?>
                    <a href="<?php echo Mage::getUrl('marketplace/product/delete/', array('id' => $_product->getId())); ?>"
                  onclick="return confirm('<?php
                  /**
                   * confirming message before delete
                   */
                  echo $this->__('Are you sure want to delete?'); ?>');">
                <img src="<?php echo $this->getSkinUrl('marketplace/images/delete.png') ?>" alt="" title="<?php
                /**
                 * Display delete option
                 */
                echo $this->__('Delete') ?>"/> </a>
                <?php } ?>

                <?php if( Mage::getStoreConfig('marketplace/product/show_disable_action') ){ ?>
                   <a href="<?php echo Mage::getUrl('marketplace/product/disable/', array('id' => $_product->getId())); ?>"
                    onclick="return confirm('<?php
                   /**
                    * confirming message before disable
                    */
                    echo $this->__('Are you sure want to disable?'); ?>');">
                <img src="<?php echo $this->getSkinUrl('marketplace/images/disable.png') ?>" alt="" title="<?php
                /**
                 * Display Disable option
                 */
                echo $this->__('Disable') ?>"/> </a>
                    <?php } ?>
                </span>
                            </em>
                        </td>

                    </tr>
                    <tr class="sub product_<?php echo $_product->getId(); ?>"
                        data-id="<?php echo $_product->getId(); ?>" style="display: none">
                        <td></td>
                        <td></td>
                        <td colspan="7" style="width: 603px !important; padding: 8px !important" class="variation">
                            <table width="100%" cellpadding="0" cellspacing="0" class="variation-tab">
                                <tbody>
                                <tr>
                                    <td></td>
                                </tr>
                                </tbody>
                            </table>
                        </td>

                    </tr>
                    <?php $sNo++;
                endforeach; ?>
                </tbody>
                <?php else: ?>
                    <tr class="mtext_center">
                        <td colspan="10"
                            class="no_product_content"><?php echo $this->__('You have no product.'); ?></td>
                    </tr>
                <?php endif ?>
            </table>
            <script type="text/javascript">decorateTable('my-product-table');
            </script>
            <?php echo $this->getPagerHtml(); ?>
        </form>
    </div>
</div>
<?php echo($this->getChildHtml('marketplace_productmanage_upload')) ?>
<script type="text/javascript">
    function getNewPrice(obj) {
        inputs = jQuery("input[class=nprice]");
        if (inputs.length >= 1) {
            inputs.first().focus();
            return false;
        }

        em = jQuery(obj);
        td = em.parent();
        price = parseFloat(td.attr('data-price'));

        if (em.length > 0) {
            jQuery(td).on("click", em, function () {
                td.text("");
                td.append("<input onchange='updatePrice(this)' type='text' name='nprice' style='width:70%; margin: 0 !important; text-align:center' class='nprice' value='" + price.toFixed(2) + "' /><span style='cursor:pointer' onclick='reloadPrice(this)'>X</span>");
                jQuery(".nprice").select();
            });
        }
        return false;
    }

    function reloadPrice(obj) {
        link = jQuery(obj);
        td = link.parent();
        // cur = "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>";
        cur = "<?php echo Mage::app()
                              ->getLocale()
                              ->currency(Mage::app()->getStore()->getBaseCurrencyCode())
                              ->getSymbol(); ?>";
        jQuery(td).on("click", link, function (e) {
            e.preventDefault();
            // var price = parseFloat(link.parent().attr("data-price"));
            var price = parseFloat(td.attr("data-price"));
            td.text("");
            td.append("<em onclick='getNewPrice(this)'>" + cur + price.toFixed(2) + "</em>")
        });
    }

    function updateQtyVar(obj) {
        var input = jQuery(obj);
        // var span = $;
        var product_id = input.attr("data-id");
        var qty = input.val();
        if (jQuery.isNumeric(qty) === false) {
            input.css("background-color", "#FFDDDD");
            return false;
        } else {
            input.css("background-color", "");
        }
        input.attr("disabled", "disabled");
        input.css("background-color", "#D9FFD9");
        jQuery.ajax({
            url: "<?php echo Mage::getUrl('marketplace/product/edit_qty') ?>",
            cache: false,
            data: {product_id: product_id, qty: qty},
            type: "GET",
            beforeSend: function () {
                input.after("<span class='tpst'><br>Updating ...</span>");
            },
            success: function (data, status) {
                input.removeAttr("disabled");
                input.css("background-color", "");
                input.val(jQuery.trim(data));
                jQuery(".tpst").text("Done").fadeOut(1000);
                // o.remove();
            }
        });
    }

    function updatePriceVar(obj) {
        var input = jQuery(obj);
        var product_id = input.attr("data-id");
        var price = input.val();
        var sym = "<?php echo Mage::app()
                                  ->getLocale()
                                  ->currency(Mage::app()->getStore()->getBaseCurrencyCode())
                                  ->getSymbol() ?>";
        if (jQuery.isNumeric(price) === false) {
            input.css("background-color", "#FFDDDD");
            return false;
        } else {
            input.css("background-color", "#D9FFD9");
            // $(".tpst_2").show();
        }
        input.attr("disabled", "disabled");
        jQuery.ajax({
            url: "<?php echo Mage::getUrl('marketplace/product/edit_price') ?>",
            cache: false,
            data: {product_id: product_id, price: price},
            type: "GET",
            beforeSend: function () {
                input.after("<span class='tpst'><br>Updating ...</span>");
            },
            success: function (data, status) {
                var i = data.replace(sym, "");
                input.removeAttr("disabled");
                input.css("background-color", "");
                input.val(i);
                jQuery(".tpst").text("Done").fadeOut(1000);
            }
        });
    }


    function updatePrice(obj) {
        input = jQuery(obj);
        td = input.parent();
        var product_id = td.attr("data-id");
        var price = input.val();
        if (jQuery.isNumeric(price) === false) {
            input.css("background-color", "#FFDDDD");
            return false;
        } else {
            input.css("background-color", "");
        }
        input.attr("disabled", "disabled");
        input.css("background-color", "#D9FFD9");
        input.attr("disabled", "disabled");
        jQuery.ajax({
            url: "<?php echo Mage::getUrl('marketplace/product/edit_price') ?>",
            cache: false,
            data: {product_id: product_id, price: price},
            type: "GET",
            success: function (data, status) {
                input.removeAttr("disabled");
                td.attr("data-price", price);
                td.text("");
                // td.append("<em onclick='getNewPrice(this)'>AED"+Math.round(price,2).toFixed(2)+"</em>")
                td.append("<em onclick='getNewPrice(this)'>" + data + "</em>")
                input.css("background-color", "");
            }
        });
    }


    //< ![CDATA[
    var bulkProductUploadForm = new VarienForm('bulk-product-upload-form');
    //]]>

    // Upload file validation
    var validFileExtensionsCsv = [".csv"];
    var validFileExtensionsZip = [".zip"];

    function bulkProductUploadValidate(oForm) {
        var arrInputs = oForm.getElementsByTagName("input");
        for (var i = 0; i < arrInputs.length; i++) {
            var oInput = arrInputs[i];

            if (oInput.type == "file" && oInput.id == 'bulk-product-upload-csv-file') {
                var sFileName = oInput.value;
                if (sFileName.length > 0) {
                    var blnValid = false;
                    for (var j = 0; j < validFileExtensionsCsv.length; j++) {
                        var sCurExtension = validFileExtensionsCsv[j];
                        if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                            blnValid = true;
                            break;
                        }
                    }

                    if (!blnValid) {
                        alert("<?php echo Mage::helper('marketplace')->__('Sorry'); ?>, " + sFileName + " <?php
                                echo Mage::helper('marketplace')
                                         ->__('is invalid, allowed extensions are'); ?>: " + validFileExtensionsCsv.join(", "));
                        return false;
                    }
                }
            }

            if (oInput.type == "file" && oInput.id == 'bulk-product-upload-image-file') {
                var sFileName = oInput.value;
                if (sFileName.length > 0) {
                    var blnValid = false;
                    for (var j = 0; j < validFileExtensionsZip.length; j++) {
                        var sCurExtension = validFileExtensionsZip[j];
                        if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                            blnValid = true;
                            break;
                        }
                    }

                    if (!blnValid) {
                        alert("<?php echo Mage::helper('marketplace')->__('Sorry'); ?>, " + sFileName + " <?php
                                echo Mage::helper('marketplace')
                                         ->__('is invalid, allowed extensions are'); ?>: " + validFileExtensionsZip.join(", "));
                        return false;
                    }
                }
            }
        }

        return true;
    }


    function showConfigurablePorductAttributeList() {
        if ($('configurable_product_attributes_list').visible()) {
            Effect.Fade('configurable_product_attributes_list', {duration: 0.5});
        } else {
            Effect.Appear('configurable_product_attributes_list', {duration: 0.5});
        }
    }

</script>
<script type="text/javascript">
    jQuery(function ($) {
        $(document).on("keydown", ".nprice", function (e) {
            obj = this;
            if (e.keyCode == 13) {
                updatePrice(obj);
                return false;
            }
        });

        $(document).on("keydown", ".newqtyv", function (e) {
            obj = $(this);
            if (e.keyCode == 13) {
                updateQtyVar(obj);
                return false;
            }
        });

        $(document).on("keydown", ".newpricev", function (e) {
            obj = $(this);
            if (e.keyCode == 13) {
                updatePriceVar(obj);
                return false;
            }
        });

        $(".more").click(function () {
            $this = $(this);
            if ($this.attr('state') != "on") {
                $("tr[class^='sub']").each(function () {
                    $(this).hide();
                    $("span[data-id=" + $(this).attr("data-id") + "]").attr("state", "off").text("+");
                });
                $this.text("-");
                $target = $(".product_" + $this.attr("data-id"))
                $target.slideToggle(200);
                var product_id = $(this).attr("data-id");
                $.ajax({
                    url: "<?php echo Mage::getUrl('marketplace/product/get_child') ?>",
                    cache: false,
                    dataType: 'html',
                    data: {product_id: product_id},
                    type: "GET",
                    beforeSend: function () {
                        $('td[class=variation]').html('');
                        $('td[class=variation]').html('<center>Loading ... </center>');
                    },
                    success: function (data, status) {
                        // alert(data);
                        $('td[class=variation]').html(data);
                        $this.attr('state', 'on');
                    }
                });
            } else {
                $this.text("+");
                $("tr[class^='sub']").each(function () {
                    $(this).hide();
                    $("span[data-id=" + $(this).attr("data-id") + "]").attr("state", "off");
                });
            }

        });

        // Collection on data that should be send for manage products search request.
        // Created obj for that because this request can be sent from different places.
        var requestData = {
            name: "<?php echo($this->getRequest()->getParam('name') ? $this->getRequest()->getParam('name') : '') ?>",
            type: "<?php echo($this->getRequest()->getParam('type') ? $this->getRequest()->getParam('type') : '') ?>",
            page: 1
        };

        var searchBySkuInput    = $('#search-by-sku');
        var searchByNameInput   = $('#search-by-name');
        var searchBySkuBtn      = $('#search-by-sku-btn');
        var searchByNameBtn     = $('#search-by-name-btn');

        searchBySkuInput.keypress(function (e) {
            if (e.keyCode == 13) {
                e.preventDefault();
                searchBySkuBtn.click();
            }
        });

        searchByNameInput.keypress(function (e) {
            if (e.keyCode == 13) {
                e.preventDefault();
                searchByNameBtn.click();
            }
        });

        searchBySkuBtn.click(function () {
            var self = searchBySkuInput;
            var input = self.val();
            var type = self.data("type");
            self.attr("disabled", "disabled");
            $(this).addClass('active');
            $('.table_spinner').toggle();
            $('#my-product-table').addClass('active');
            // Populate requestData object with data
            requestData.name = input;
            requestData.type = type;
            requestData.page = 1;
            // Do ajax request.
            doRequest(self);
        });

        searchByNameBtn.click(function () {
            var self = searchByNameInput;
            var input = self.val();
            var type = self.data("type");
            self.attr("disabled", "disabled");
            $(this).addClass('active');
            $('.table_spinner').toggle();
            $('#my-product-table').addClass('active');
            // Populate requestData object with data
            requestData.name = input;
            requestData.type = type;
            requestData.page = 1;
            // Do ajax request.
            doRequest(self);
        });

        $('.pages li a').click(function (e) {
            var step = 7;
            e.preventDefault();
            $('.table_spinner').toggle();
            $('#my-product-table').addClass('active');
            var paramPage = "<?php echo $this->getRequest()->getParam('page') ?>";
            var page = $.trim($(this).text());
            if (page === 'Next') {
                if (paramPage.length === 0) {
                    page = requestData.page;
                } else {
                    page = parseInt(paramPage);
                }
                page += 1;
            }
            if (page === 'Previous') {
                if (paramPage.length === 0) {
                    page = requestData.page;
                } else {
                    page = parseInt(paramPage);
                }
                page -= 1;
            }
            if (page === '...') {
                if (paramPage.length === 0) {
                    page = requestData.page;
                } else {
                    page = parseInt(paramPage);
                }
                if ($(this).hasClass('next_jump')) {
                    page += step;
                } else {
                    page -= step;
                }
            }
            requestData.page = page;
            // Do ajax request.
            doRequest();
        });



        // Extract ajax request to independent function to use it for both search by name and sku.
        function doRequest(obj = null) {
            $.ajax({
                url: "<?php echo Mage::getUrl('marketplace/ajax/filter') ?>",
                cache: false,
                data: {
                    name: requestData.name,
                    type: requestData.type,
                    page: requestData.page
                },
                type: "POST",
                success: function (data) {
                    $('#market_place_manage_products').replaceWith(data);
                    if (obj !== null) {
                        obj.removeAttr("disabled");
                    }
                }
            });
        }
    });
</script>
