<?php if (count($this->getAwStorecredit()) > 0): ?>
    <?php foreach($this->getAwStorecredit() as $storeCredit): ?>
    <tr>
        <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-left storecredit_th">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                <strong>
            <?php endif; ?>
            <?php echo $this->__('Store Credit'); ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                </strong>
            <?php endif; ?>
        </td>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right storecredit_td">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                <strong>
            <?php endif; ?>
            -<?php echo $this->helper('checkout')->formatPrice($storeCredit->getStorecreditAmount()) ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                </strong>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach;?>
<?php endif;?>