<?php
/** @var Progos_Magidev_Block_Sort_Adminhtml_Catalog_Category_Tab_Sort $this */
/** @var Mage_Catalog_Helper_Output $_helper */
$_helper = $this->helper('catalog/output');

$_categoryProducts = $this->getCategoryProducts();
$_collectionSize = $this->getCollectionSize();
$_columnCount = $this->getColumnCount();
$_pageCount = $this->getPageCount();

?>

<div style="display: none;">
    <button id="available-sort"
            onclick="mAvailable.sort(<?php echo $this->getCategoryId() ?>, '<?php echo $this->getAdminUrl("*/sortproduct/save", array()); ?>?isAjax=true','<?php echo $this->getType() ?>'); return false;">
        <?php echo $this->__('Out of Stock to the End') ?>
    </button>
</div>

<?php
$_close = false;
$_ul = false;
$_open = true;
$i = 0;
$j = 0;
$p = 1;
?>

<?php foreach ($_categoryProducts as $_position => $_product): ?>
    <?php if ($j % $_pageCount == 0 && $_open == true || $_open == true): ?>
        <?php $_open = false; ?>
        <div class="pages">
    <?php endif ?>

    <?php if ($i++ % $_columnCount == 0): ?>
<?php $_ul = false; ?>
    <ul class="products-grid">
<?php endif ?>

    <?php if ($i == $_collectionSize): ?>
    <li id="position-<?php echo $i ?>" data-position="<?php echo $_position ?>" class="position-to-insert" style="display: none;">
<?php else: ?>
    <li id="position-<?php echo $i ?>" data-position="<?php echo $_position ?>"
        class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
<?php endif; ?>

    <?php if ($i != $_collectionSize): ?>
        <div data-stock="<?php echo ($_product->getStockItem() && $_product->getStockItem()->getIsInStock()) ? '1' : '0' ?>"
             data-id="<?php echo $_product->getId() ?>"
             class="product <?php if ($_product->getStatus() == Mage_Catalog_Model_Product_Status::STATUS_DISABLED): ?>disabled-item<?php endif; ?>"
             id="productId-<?php echo $_product->getId() ?>" style="text-align: center">
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(135); ?>"
                 width="135" height="135"/>
            <h2 class="product-name" style="width:180px;">
                <span class="proName"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
                <br/><span><?php echo $this->__('SK:'); ?></span> <span
                        class="proSKU <?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku'); ?>"><?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku'); ?></span>
                <br/><span><?php echo $this->__('Pr:'); ?></span> <?php echo Mage::helper('core')->currency($_product->getPrice(), true, false); ?>

                <br/><span><?php echo $this->__('IR:(size, qty)'); ?></span>

                <?php
                    echo '<ul style="list-style-type:circle;">';
                        foreach ($_product->getTypeInstance(true)->getUsedProducts ( null, $_product) as $simple) {
                            //using existing object retrieved attribute, no extra call @RT
                            $productSize = $simple->getAttributeText('size');
                            //available qty of this product @RT
                            $productQty = (int)$simple->getStockItem()->getQty();
                            echo "<li style='border: unset;margin: 0px;display:block'>(".$productSize.", ". $productQty .")</li>";
                        }
                    echo '</ul>';
                ?>

            </h2>
            <div class="actions <?php echo $_product->getIndicator() ?>">
                <a title="Quick edit Product" class="edit-item"
                   rel="<?php echo $this->getAdminUrl("*/sortproduct/edit", array('id' => $_product->getId())); ?>">
                    <img src="<?php echo $this->getSkinUrl('images/magidev/sort/tab_edit.png') ?>">
                </a>
                <a target="_blank" title="Edit Product"
                   href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/catalog_product/edit", array('id' => $_product->getId())); ?>">
                    <img src="<?php echo $this->getSkinUrl('images/icon_edit_address.gif') ?>">
                </a>
                <a class="disable-item" title="Enable/Disable Product"
                   rel="<?php echo $this->getAdminUrl("*/sortproduct/status", array('id' => $_product->getId())); ?>">
                    <img src="<?php echo $this->getSkinUrl('images/icon-enabled.png') ?>">
                </a>
                <a class="delete-item" title="Remove from the Category"
                   rel="<?php echo $this->getAdminUrl("*/sortproduct/delete", array('id' => $_product->getId(), 'categoryId' => $this->getCategoryId())); ?>">
                    <img src="<?php echo $this->getSkinUrl('images/icon_remove_address.gif') ?>">
                </a>
            </div>
        </div>
    <?php endif; ?>

    </li>

    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
    </ul>
<?php $_ul = true; ?>
<?php endif; ?>

    <?php $j++; ?>
    <?php if ($_close == false && ($j % $_pageCount == 0)) $_close = true; ?>
    <?php if ($_close && $_ul || $i == $_collectionSize): ?>
        <?php
        $_close = false;
        $_ul = false;
        $_open = true;
        ?>
        <div class="pages-label"><?php echo $this->helper('magidev_sort')->__('Page #%s', $p++) ?></div>
        </div><!-- .pages -->
    <?php endif; ?>
<?php endforeach ?>

<script type="text/javascript">
    //<![CDATA[
    var Sort = new Magidev.Sort(<?php echo $this->getCategoryId() ?>, '<?php echo $this->getAdminUrl("*/sortproduct/save", array()) ?>?isAjax=true', '<?php echo $this->getType() ?>');
    //]]>
</script>