<?php
/**
 * Progos_CustomOrderFlags
 *
 * @category    Progos
 * @package     Progos_CustomOrderFlags
 * @author      Saroop Chand <saroop.chand@progos.org> 22-02-2018
 * @copyright   Copyright (c) 2018 Progos, Ltd (http://progos.org)
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function prefferedSyncButton() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            dataType:   'json',
            onComplete: function(transport){
                alert( transport.responseText );
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>

<p class="note">
    <span>
        Sync Preffered Courier Flag from Core Order table to Mageworx Grid Table
    </span>
</p>

