<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     0.1.0
  * @license     http://www.apptha.com/LICENSE.txt
 * 
 */

/**
 * Seller profile Update
 * This file contains add seller profile
 * Edit seller profile
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>

<!DOCTYPE html>
<?php
    $storeCode = Mage::app()->getStore()->getCode();
    $storeCode = explode("_",$storeCode);
?>
<html lang="<?php echo $storeCode[0] ?>-<?php echo strtoupper($storeCode[1]); ?>" data-country="<?php echo strtoupper($storeCode[1]); ?>" data-lang="<?php echo $storeCode[0] ?>" id="top" class="no-js">
<head>
<?php
 echo $this->getChildHtml('head') ?>
</head>
<body<?php 
echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getBlockHtml('header_custom') ?>
        <div class="main-container col2-right-layout"><div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
                <div class="col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div></div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
