<?php

/**
 * Apptha
 * NOTICE OF LICENSE
  ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 * 
 * @package     Apptha_Marketplace
 * @version     0.1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<!DOCTYPE html>
<?php
    $storeCode = Mage::app()->getStore()->getCode();
    $storeCode = explode("_",$storeCode);
?>
<!--[if lt IE 7 ]> <html lang="<?php echo $storeCode[0] ?>-<?php echo strtoupper($storeCode[1]); ?>" data-country="<?php echo strtoupper($storeCode[1]); ?>" data-lang="<?php echo $storeCode[0] ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $storeCode[0] ?>-<?php echo strtoupper($storeCode[1]); ?>" data-country="<?php echo strtoupper($storeCode[1]); ?>" data-lang="<?php echo $storeCode[0] ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $storeCode[0] ?>-<?php echo strtoupper($storeCode[1]); ?>" data-country="<?php echo strtoupper($storeCode[1]); ?>" data-lang="<?php echo $storeCode[0] ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $storeCode[0] ?>-<?php echo strtoupper($storeCode[1]); ?>" data-country="<?php echo strtoupper($storeCode[1]); ?>" data-lang="<?php echo $storeCode[0] ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $storeCode[0] ?>-<?php echo strtoupper($storeCode[1]); ?>" data-country="<?php echo strtoupper($storeCode[1]); ?>" data-lang="<?php echo $storeCode[0] ?>" id="top" class="no-js"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?></head>
<body class="page-empty 
<?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
    <div>
        <?php echo $this->getChildHtml('after_body_start') ?>
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('content') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
    </div>
</body>
</html>
