<?php 
	$mobDetect    = Mage::helper('mobiledetect');
	if ( $mobDetect->isMobile() && !$mobDetect->isTablet() ){
		if( $mobDetect->is('iOS') ){

			$_category_detail = Mage::registry('current_category');
			$categoryId = $_category_detail->getId();
			$params = $this->getRequest()->getParams();
			$brandIds = $colors = $price = $size = "";
			if( !empty($params['price']) )
				$price = $params['price'];
			if( !empty($params['manufacturer']) )
				$brandIds = $params['manufacturer'];
			if( !empty($params['color']) )
				$colors = $params['color'];
			if( !empty($params['size']) )
				$size = $params['size'];

			$url = 'elabelz://category/?cid='.$categoryId.'&manufecturer='.$brandIds.'&color='.$colors.'&price='.$price.'&size='.$size;
?>
			<meta name="apple-itunes-app" content="app-id=1145303714, app-argument=<?php echo $url ?>" />
			<meta name="app-rich-data" content="<?php echo $url ?>" />
<?php	} ?>

<?php	if( $mobDetect->is('AndroidOS') ){
			$_category_detail = Mage::registry('current_category');
			$categoryId = $_category_detail->getId();
			$params = $this->getRequest()->getParams();
			$brandIds = $colors = $price = $size = "";
			if( !empty($params['price']) )
				$price = $params['price'];
			if( !empty($params['manufacturer']) )
				$brandIds = $params['manufacturer'];
			if( !empty($params['color']) )
				$colors = $params['color'];
			if( !empty($params['size']) )
				$size = $params['size'];

			$url = 'elabelz://category/?cid='.$categoryId.'&manufecturer='.$brandIds.'&color='.$colors.'&price_range='.$price.'&size='.$size;
?>
			<meta name="google-play-app" content="app-id=com.progos.elabelz">
			<meta name="app-rich-data" content="<?php echo $url ?>" />
<?php	} ?>
<?php } ?>