<?php
$pids_raw = $this->getData('product_ids');
$pids_temp = explode(',', $pids_raw);
$pids = array();
foreach ($pids_temp as $pid_temp) {
    $pids[] = $pid_temp;
}

$products = $this->getRecentProducts($pids);
$baseCurrency = Mage::app()->getStore()->getBaseCurrencyCode();
//echo "<pre>";
//print_r($products);
$productMediaConfig = Mage::getModel('catalog/product_media_config');

if (!function_exists('getCatPath')) {
    function getCatPath($sku)
    {
        $product = Mage::getModel('catalog/product')->loadByAttribute('sku', $sku);

        $pathArray = array();
        $collection1 = $product->getCategoryCollection()
            ->setStoreId(Mage::app()->getStore()->getId())
            ->addAttributeToSelect('path')
            ->addAttributeToSelect('is_active');


        foreach ($collection1 as $cat1) {
            $pathIds = explode('/', $cat1->getPath());
            $collection = Mage::getModel('catalog/category')->getCollection()
                ->setStoreId(Mage::app()->getStore()->getId())
                ->addAttributeToSelect('name')
                ->addAttributeToSelect('is_active')
                ->addFieldToFilter('entity_id', array('in' => $pathIds));

            $pahtByName = '';
            foreach ($collection as $cat) {
                $pahtByName .= '/' . strtolower($cat->getName());
            }

            $pathArray[] = $pahtByName;

        }

        return $pathArray;
    }
}
?>


<?php if (is_array($products) && count($products)) { ?>
    <?php
    $i = 0;
    foreach ($products as $product) {

        $product_model = Mage::getModel('catalog/product');
        $my_product_id = $product_model->getIdBySku($product['sku']);
        $my_product = $product_model->load($my_product_id);
        $purl = $product_model->getProductUrl($product);

        $thumbnailUrl = $productMediaConfig->getMediaUrl($product['thumb']);
        $i++;
        $arr = getCatPath($product['sku']);
        $arr_temp = explode('/default category', $arr[count($arr) - 1]);
        //print_r($arr_temp);
        //$str = ltrim('/',$arr_temp[1]);

        //$purl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$arr_temp[1]."/".$product['urlkey'].".html";

        $blockHtml = $this->getLayout()->createBlock('cms/block')->setBlockId('newsletter-products-grid')->toHtml();
        $blockHtml = str_replace('{PRODUCT_URL}', $purl, $blockHtml);
        $blockHtml = str_replace('{PRODUCT_IMAGE}', $thumbnailUrl, $blockHtml);
		$blockHtml = str_replace('{BRAND_TITLE}', $my_product->getAttributeText('manufacturer'), $blockHtml);
        $blockHtml = str_replace('{PRODUCT_TITLE}', $product['name'], $blockHtml);
        $blockHtml = str_replace('{PRODUCT_CURRENCY}', $baseCurrency, $blockHtml);
        $blockHtml = str_replace('{PRODUCT_PRICE}', number_format($product['finalPrice'], 2), $blockHtml);
        echo $blockHtml;
        ?>


       


        <?php
		echo '</td><td valign="top">';
        if ($i % 3 == 0) {
            echo '</tr><tr style="width:100%;"><td class="three-column test">';
        }
        ?>

    <?php } ?>
<?php } ?>
