<?php
/**
 * @author     RT
 * @category   Progos
 * @package    Progos_Storecredit
 * @version    0.1.0
 */

$locale = Mage::app()->getLocale()->getLocaleCode();
$currencySymbol = Mage::app()->getStore(Mage::app()->getStore()->getId())->getCurrentCurrencyCode();
?><?php if (count($this->getAwStorecredit()) > 0): ?>
    <?php foreach($this->getAwStorecredit() as $storeCredit): ?>
    <tr>
        <th colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right storecredit_th">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                <strong>
            <?php endif; ?>
            <?php $_title = $this->__('Remove'); ?>
            <?php
                $_url = Mage::getUrl('awstorecredit/storecredit/remove',
                    array(
                         '_secure' => Mage::app()->getStore(true)->isCurrentlySecure(),
                         'awstorecredit_code' => base64_encode($storeCredit->getStorecreditId())
                    )
                );
            ?>
            <?php echo $this->__('Store Credit'); ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                </strong>
            <?php endif; ?>
        </th>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right storecredit_td">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                <strong>
            <?php endif; ?>
            <?php //hardcoded for ar_SA locale, currency symbol ?>
            <?php if($locale == "ar_SA"): ?><strong><?php echo $this->__($currencySymbol) ?></strong><?php endif; ?>
            -<?php echo $this->helper('checkout')->formatPrice($storeCredit->getStorecreditAmount()) ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?>
                </strong>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach;?>
<?php endif;?>