<script type="text/javascript">
    //<![CDATA[
    function removeconfig() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            dataType:   'json',
            onComplete: function(transport){
                alert( transport.responseText );
                location.reload();
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>

<p class="note">
    <span>
        Remove Config Product.<br>
    </span>
    <?php
    if( file_exists(Mage::getBaseDir('media').DS.'oos'.DS.'configprodremove_dry.csv') ){ ?>
        <a href="<?php echo Mage::getBaseUrl('media').DS.'oos'.DS.'configprodremove_dry.csv' ?>" target="_blank">Download Dry Run Results.</a>
    <?php } ?>
    <br/>
    <?php
    if( file_exists(Mage::getBaseDir('media').DS.'oos'.DS.'configprodremove.csv') ){ ?>
        <a href="<?php echo Mage::getBaseUrl('media').DS.'oos'.DS.'configprodremove.csv' ?>" target="_blank">Download Original Results.</a>
    <?php } ?>
</p>