<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
  * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_MageShop
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 */
/**
 * Home page template
 */
?>
<div id="content">
	<div class="site_width_container site_width_main">
		<div id="template_home">
			<!--<h1 class="visually_hidden">zlabelz</h1>-->
			<section class="top_features">
				<div class="site_width_container site_width_main"> 

					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_top_feature_category_block')->toHtml() ?> 
					
                   <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage_is_top_categories_show')->toHtml(); ?>

					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_top_feature_before_brands')->toHtml() ?>

				</div>
			</section>
		</div>
	</div>	
</div>