<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.4
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $imageSearchEnabled = (bool)Mage::getStoreConfig('image_search/image_search_settings/enabled');
    if( $imageSearchEnabled ){
        $imageSearchAppKey = (string)Mage::getStoreConfig('image_search/image_search_settings/app_key');
        $imageSearchAccessKey= (string)Mage::getStoreConfig('image_search/image_search_settings/access_key');
        $imageSearchSecretKey = (string)Mage::getStoreConfig('image_search/image_search_settings/secret_key');
        $imageSearchTimeout = (int)Mage::getStoreConfig('image_search/image_search_settings/timeout');
?>
<script type="text/javascript">
    !function(e,r,t,a,s){e.__visearch_obj=s;var c=e[s]=e[s]||{};c.q=c.q||[],c.factory=function(e){return function(){var r=Array.prototype.slice.call(arguments);return r.unshift(e),c.q.push(r),c}},c.methods=["idsearch","uploadsearch","colorsearch","set","send"];for(var n=0;n<c.methods.length;n++){var o=c.methods[n];c[o]=c.factory(o)}var i=r.createElement(t);i.type="text/javascript",i.async=!0,i.src=a;var h=r.getElementsByTagName(t)[0];h.parentNode.insertBefore(i,h)}(window,document,"script","//cdn.visenze.com/visearch/dist/js/visearch-1.1.0.min.js","visearch");
    visearch.set("app_key", "<?php echo $imageSearchAppKey; ?>");
    visearch.set("access_key", "<?php echo $imageSearchAccessKey; ?>");
    visearch.set("secret_key", "<?php echo $imageSearchSecretKey; ?>");
    visearch.set("timeout", <?php echo $imageSearchTimeout; ?>);
</script>
<?php } ?>
<script type="text/javascript">
    <?php
        $baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
        $currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
        $currentCurrencySymbol = Mage::app()->getLocale()->currency($currentCurrencyCode)->getSymbol();
        $rates = Mage::getModel('directory/currency')->getCurrencyRates($baseCurrencyCode, $currentCurrencyCode);
    ?>
    window.current_store_code = "<?php echo Mage::app()->getStore()->getCode(); ?>";
    window.CurrentCurrencyCode = "<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>";
    window.CurrentCurrencySymbol = "<?php echo Mage::app()->getLocale()->currency( Mage::app()->getStore()->getCurrentCurrencyCode() )->getSymbol(); ?>";
</script>
<?php $_helperOutput = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var ajaxCartUrl = "<?php echo Mage::getUrl('checkout/cart/ajaxAdd') ?>";
    var alertHead = "<?php echo $this->__('Error');?>";
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    var currentSku = "<?php echo $this->__($_helperOutput->productAttribute($_product, $_product->getSku(), 'sku')); ?>";
</script>
<?php
/**
 * form for Product information
 */
?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post"
              id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
                <input type="hidden" name="related_product" id="related-products-field" value=""/>
            </div>
            <div class="product-img-box">
                <div class="product-name"></div>
                <?php echo $this->getChildHtml('media'); ?>
                    <div class="social_block right">
                    <a class="social_block_item" id="social_block_popup"><?php echo $this->__("Share"); ?></a>
                    <?php $fullUrl = Mage::helper('core/url')->getCurrentUrl();
                    $Product_name = $this->__($_helperOutput->productAttribute($_product, $_product->getName(), 'name'));
                    ?>
                    <div class="social_share_block" id="social_share_block_popup" style="display:none;">
                        <a target="_blank" class="facebook-btn fa fa-facebook" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $fullUrl; ?>"></a>
                        <a target="_blank" class="pinterest-btn fa fa-pinterest" href="https://pinterest.com/pin/create/button/?url=&media=<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>&description=<?php echo $Product_name; ?>"></a>
                        <a target="_blank" class="twitter-btn fa fa-twitter" href="https://twitter.com/home?status=<?php echo $Product_name; ?> <?php echo $fullUrl; ?>"></a>
                        <a target="_blank" class="email-btn fa fa-envelope" href="mailto:?&subject=<?php echo $Product_name; ?>&body=Hi%20friend%20see%20this%20website%0Alink%20is%20below%20%0A<?php echo $fullUrl; ?>"></a>
                    </div>
                    <script type="text/javascript">
                        //show popup when clicking the trigger
                        jQuery('#social_block_popup').on('click touch', function(){
                          jQuery("#social_share_block_popup").slideToggle("fast");
                        });         
                         
                        //hide it when clicking anywhere else except the popup and the trigger
                        jQuery(document).on('click touch', function(event) {
                          if (!jQuery(event.target).parents().addBack().is('#social_block_popup')) {
                            jQuery('#social_share_block_popup').slideUp("fast");
                          }
                        });
                         
                        // Stop propagation to prevent hiding "#tooltip" when clicking on it
                        jQuery('#social_share_block_popup').on('click touch', function(event) {
                          event.stopPropagation();
                        });
                    </script>
                </div>
            </div>
            <div class="product-shop">
                <?php //echo $this->getReviewsSummaryHtml($_product, 'default', true)?>
                <div class="clear"></div>
                <div class="product-info-wr">
                    <?php
                    if ($_product->getSpecialPrice()) {
                        $json_price = Mage::helper('core')->currency($_product->getSpecialPrice(), false, false);
                    } else {
                        $json_price = Mage::helper('core')->currency($_product->getPrice(), false, false);
                    }
                    $json_store_id = Mage::app()->getStore()->getId();
                    $json_cur_code = $this->__(Mage::app()->getStore()->getCurrentCurrencyCode());

                    if ($_product->getAttributeText('manufacturer') == '') {
                        $json_brand = $this->__($_helperOutput->productAttribute($_product, $_product->getName(), 'name'));
                    } else {
                        $json_brand = $this->__($_product->getAttributeText('manufacturer'));
                    }

                    $json_brand_obj = Mage::getModel('shopbybrand/brand')->setStoreId($json_store_id)->load($json_brand, "name");
                    $json_brand_url = Mage::helper('shopbybrand')->getUrlLogo($json_brand_obj->getId()) . '/' . $json_brand_obj->getThumbnailImage();
                    ?>
                    <script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "Product",
    "description": "<?php echo $this->__($this->helper('catalog/output')->productAttribute($this->getProduct(), $this->getProduct()->getDescription(), 'description')); ?>",
    "name": "<?php echo $this->__($_helperOutput->productAttribute($_product, $_product->getName(), 'name')); ?>",
    "sku": "<?php echo $this->__($_helperOutput->productAttribute($_product, $_product->getSku(), 'sku')); ?>",
    "image": "<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail'); ?>",
    <?php if ($_product->getIssalable()): ?>
    "offers": {
        "@type": "Offer",
        "url": "<?php echo $_product->getUrlInStore(); ?>",
        "price": "<?php echo $json_price; ?>",
        "priceCurrency": "<?php echo $json_cur_code ?>",
        "acceptedPaymentMethod": ["http://purl.org/goodrelations/v1#COD", "http://purl.org/goodrelations/v1#PayPal", "http://purl.org/goodrelations/v1#VISA", "http://purl.org/goodrelations/v1#MasterCard"],
        "availability": "http://schema.org/InStock",
        "itemCondition": "http://schema.org/NewCondition"
    },
    <?php endif; ?>
    "brand": {
        "@type": "Brand",
        "name": "<?php echo $json_brand ?>",
        "logo": "<?php echo $json_brand_url ?>"
    }
}
                    </script>

                    <div class="product-name">
                        <h1 class="h1">
                            <?php $_manufacturerId = $_product->getManufacturer();
                            $shopbybrands = $model = Mage::getModel('shopbybrand/brand')->load($_manufacturerId, 'option_id');
                            $_brandUrlKey = Mage::helper('shopbybrand')->refineUrlKey($shopbybrands->getUrl_key());
                            ?>

                            <?php if ($_product->getAttributeText('manufacturer') == '') { ?>
                                <?php echo $this->__($_helperOutput->productAttribute($_product, $_product->getName(), 'name')); ?>
                            <?php } else { ?>
                                <a href="<?php echo Mage::getBaseUrl() . $_brandUrlKey; ?>"><?php echo $this->__($_product->getAttributeText('manufacturer')); ?></a>
                            <?php } ?>

                        </h1>
                    </div>
                    <div class="detailpage_top_section">
                        <div class="topsectionleft">
                            <?php
                            /**
                             * Check the product has short description
                             * if has display the product short description
                             */
                            if ($_product->getShortDescription()):?>
                                <div class="short-description">
                                    <?php //echo $_helperOutput->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description')
                                    ?>
                                    <h2 class="productnametop">
                                        <?php echo $this->__($_helperOutput->productAttribute($_product, $_product->getName(), 'name')); ?>
                                    </h2>
                                </div>
                            <?php endif; ?>
                            <div class="price-info">
                                <?php echo $this->getChildHtml('marketplace_customer'); ?>
                                <?php //echo $this->getChildHtml('product_type_availability'); ?>
                                <?php
                                /**
                                 * Display product price
                                 */
                                ?>

                                <?php
                                echo $this->getPriceHtml($_product);

                                ?>

                                <?php
                                //endif;
                                /**
                                 * Display Product bundle prices
                                 */
                                echo $this->getChildHtml('bundle_prices') ?>
                                <?php
                                /**
                                 * Display the Product tier price
                                 */
                                echo $this->getTierPriceHtml() ?>
                                <?php
                                /**
                                 * Starts super deals timer
                                 */

                                ?>

                                <?php
                                /**
                                 *  Count for timer calculation declared here
                                 */

                                if (!Mage::registry('timer_count')) :
                                    $counts = 1;
                                    Mage::register('timer_count', $counts);
                                else:
                                    $counts = Mage::registry('timer_count');
                                    $counts = $counts + 1;
                                    Mage::unregister('timer_count');
                                    Mage::register('timer_count', $counts);
                                endif;

                                $_helperOutput = $this->helper('catalog/output');
                                /**
                                 *  Admin Controllers for timer are declared here
                                 */
                                $dealsEnable = Mage::helper('core/data')->isModuleEnabled('Apptha_Superdeals');
                                /**
                                 * Get the admin deal enable status in a variable
                                 */
                                $dealsEnabled = intval($dealsEnable);
                                $advanceOption = Mage::getStoreConfig('advanced/modules_disable_output/Apptha_Superdeals');
                                /**
                                 * Get the admin advance option in a variable
                                 */
                                $advanceOption = intval($advanceOption);
                                /**
                                 * Define deals enable status in constant
                                 */
                                $STORE_CONFIG_DEALS_ENABLED = Mage::getStoreConfig('superdeals/superdeals_group/deals_enable');
                                /**
                                 * Define custom color enable status in constant
                                 */
                                $STORE_CONFIG_CUSTOM_COLOR_ENABLED = Mage::getStoreConfig('superdeals/timer/custom_color_enable');
                                /**
                                 * Define timer enable status in constant
                                 */
                                $STORE_CONFIG_TIMER_ENABLED = Mage::getStoreConfig('superdeals/timer/show_timer');
                                /**
                                 * Define timer active status in constant
                                 */
                                $timer_active = Mage::getStoreConfig('superdeals/timer/show_timer');
                                /**
                                 * Define text color in constant
                                 */
                                $timer_color = Mage::getStoreConfig('superdeals/timer/text');
                                /**
                                 * Define timer background color in constant
                                 */
                                $timer_background = Mage::getStoreConfig('superdeals/timer/background_color');
                                /**
                                 * Define timer caption color in constant
                                 */
                                $caption_color = Mage::getStoreConfig('superdeals/timer/caption_color');
                                /**
                                 * Define timer heading color in constant
                                 */
                                $heading_color = Mage::getStoreConfig('superdeals/timer/heading_text_color');
                                /**
                                 * Define timer label color in constant
                                 */
                                $save_dis_lable_color = Mage::getStoreConfig('superdeals/timer/save_dis_lable_color');
                                /**
                                 * Define price color in constant
                                 */
                                $save_dis_price_color = Mage::getStoreConfig('superdeals/timer/save_dis_price_color');
                                /**
                                 * Define timer font size in constant
                                 */
                                $save_dis_font_size = Mage::getStoreConfig('superdeals/timer/save_dis_font_size');
                                /**
                                 * Define timer category font size in constant
                                 */
                                $save_cat_time_font_size = Mage::getStoreConfig('superdeals/timer/save_cat_time_font_size');
                                /**
                                 * Define save view font size in constant
                                 */
                                $save_view_time_font_size = Mage::getStoreConfig('superdeals/timer/save_view_time_font_size');

                                $timer_head = Mage::getStoreConfig('superdeals/timer/timer_head');
                                /**
                                 * Get special price end date
                                 */
                                $toDate = $_product->getSpecialTODate();
                                $now = Mage::getModel('core/date')->timestamp(time());
                                $now = date('Y-m-d' . ' 00:00:00', $now);
                                ?>
                                <?php
                                /**
                                 * check customer color enabled and
                                 * deals enabled and
                                 * advance option is zero
                                 */
                                if (($STORE_CONFIG_CUSTOM_COLOR_ENABLED == 1) && ($dealsEnabled == 1) && ($advanceOption == 0)) {
                                    ?>
                                    <style type="text/css">
                                        /* design for Category page */
                                        .deal-price-box .price-label {
                                            color: # <?php echo $save_dis_lable_color ?>;
                                        }

                                        .deal-price-box .price {
                                            color: # <?php echo $save_dis_price_color ?>;
                                        }

                                        .dealtimer_listpage .dealtimer_listpage_timer span, .dealtimer_listpage .dealtimer_listpage_timer {
                                            color: # <?php echo $timer_color ?>;
                                            font-size: <?php echo $save_cat_time_font_size ?>px;
                                        }

                                        /* design for Detail page */
                                        .dealtimer_detailpage .dealtimer_detailpage_offerlabel {
                                            color: # <?php echo $heading_color ?>;
                                            font-weight: bold;
                                            font-size: <?php echo $save_view_time_font_size ?>px;
                                        }

                                        .detail-deal-page-box .price-label {
                                            color: # <?php echo $save_dis_lable_color ?>;
                                            font-size: <?php echo $save_dis_font_size ?>px;
                                        }

                                        .detail-deal-page-box .price {
                                            color: # <?php echo $save_dis_price_color ?>;
                                            font-size: <?php echo $save_dis_font_size ?>px;
                                        }

                                        .app_deal_time_container app_offer_head {
                                            color: # <?php echo $heading_color ?>;
                                        }

                                        .dealtimer_detailpage .dealtimer_detailpage_timer span, .dealtimer_detailpage .dealtimer_detailpage_timer {
                                            color: # <?php echo $timer_color ?>;
                                            font-size: <?php echo $save_view_time_font_size ?>px;
                                        }
                                    </style>
                                <?php } ?>
                                <?php
                                /**
                                 *  Display the saving amount here
                                 *  Check product price is greater than product special price
                                 *  and deals has been enables
                                 *  and product special price is not equal to empty
                                 */

                                if ($_product->getPrice() > $_product->getSpecialPrice() && $dealsEnabled == 1 && $_product->getSpecialPrice() != '') {
                                    $savingsDollarValue = ($_product->getPrice() - $_product->getFinalPrice());
                                    /**
                                     * Get product original price
                                     */
                                    $originalPrice = $_product->getPrice();
                                    /**
                                     * Get product discount price
                                     */
                                    $discountPrice = $_product->getFinalPrice();
                                    /**
                                     * Calculate the savings price
                                     */
                                    $savings = $originalPrice - $discountPrice;
                                    /**
                                     * Calculate the savings pecentage
                                     */
                                    $savingsPercentage = round(($savings / $originalPrice) * 100, 0);
                                    /**
                                     * Get the product type
                                     */
                                    $productType = $_product->getTypeId();
                                    $coreHelper = $this->helper('core');
                                    ?>
                                    <?php
                                    /**
                                     * check the price of the product is greater than product special price
                                     * and product type is not equal to bundle
                                     */
                                    if (($_product->getPrice()) > ($_product->getSpecialPrice()) && $productType != 'bundle') { ?>
                                        <!--<div class="clear saving_options">
                <?php
                                        /**
                                         * Check saving price dollar value is greater than zero
                                         * if so display savings price value
                                         */
                                        if ($savingsDollarValue > 0) { ?>
                <span> <?php echo $this->__('Save') . ':'; ?> <span><b><?php echo $coreHelper->currency($savingsDollarValue, true, false); ?></b> </span> </span>
                <?php } ?>
                <?php
                                        /**
                                         * Check savings percentage is greater than zero
                                         * if so display the savings percentage
                                         */
                                        if ($savingsPercentage > 0) { ?>
                <span><?php echo $this->__('Discount') . ':'; ?> </span> <span><b><?php echo $savingsPercentage, '%'; ?></b> </span>
                <?php } ?>
              </div>-->
                                    <?php }
                                } ?>
                                <!--timer starts-->
                                <?php
                                /**
                                 * Check the product price is greater than prodcut special price
                                 * and deals has been enabled in configuration
                                 * and timer has been enabled in configuration
                                 * and deals enabled equal to 1
                                 * and advance option is equal to zero
                                 */
                                if ((($_product->getPrice() > $_product->getSpecialPrice())) && ($STORE_CONFIG_DEALS_ENABLED == 1) && ($STORE_CONFIG_TIMER_ENABLED == 1)):
                                    if (($dealsEnabled == 1) && ($advanceOption == 0)) {
                                        ?>
                                        <?php
                                        /**
                                         * Check the to date is not empty
                                         * and to date is greater than or equal to current date time
                                         */
                                    if (!empty($toDate) && $toDate >= $now){ ?>
                                        <?php
                                        /**
                                         * check the product special price is not equal to zero
                                         * or the product special price is not equal to empty
                                         */
                                    if ($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice() != "") : ?>
                                        <?php if (Mage::registry('product')) : ?>
                                        <div class="dealtimer_detailpage">
                                            <div id="heading<?php echo $counts; ?>"
                                                 class="dealtimer_detailpage_offerlabel">
                                                <?php echo $timer_head ?>
                                            </div>
                                            <div id="countbox<?php echo $counts; ?>"
                                                 class="dealtimer_detailpage_timer"></div>
                                        </div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                        <!-- first if ends here -->
                                    <?php }else{
                                        /**
                                         * Checking the product special price is not equal to zero
                                         * and product to date is empty
                                         * if so display as on sale
                                         */
                                    if ($_product->getSpecialPrice() != 0 && empty($toDate)){ ?>
                                        <?php if (Mage::registry('product')) { ?>
                                        <div class="dealtimer_detailpage">
                                            <div class="dealtimer_detailpage_timer">
                                                <?php echo $this->__('On Sale!'); ?>
                                            </div>
                                        </div>
                                    <?php }
                                    } ?>
                                    <?php } ?>
                                        <script type="text/javascript">
                                            var dthen<?php
                echo $counts; ?> = new Date("<?php
                 echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
                                            start = "<?php
                 echo Date("m/d/y h:i:s A", strtotime(Mage::app()->getLocale()->date(null, null, "en_US", true))); ?>";
                                            start_date = Date.parse(start);
                                            var dnow<?php
                 echo $counts; ?> = new Date(start_date);
                                            if (CountStepper > 0)
                                                ddiff = new Date((dnow<?php
                     echo $counts; ?>) - (dthen<?php
                      echo $counts; ?>));
                                            else
                                                ddiff = new Date((dthen<?php
                     echo $counts; ?>) - (dnow<?php
                      echo $counts; ?>));
                                            gsecs<?php echo $counts; ?> = Math.floor(ddiff.valueOf() / 1000);
                                            var iid<?php echo $counts; ?> = "countbox<?php
                 echo $counts; ?>";
                                            CountBack(gsecs<?php echo $counts; ?>, iid<?php
                 echo $counts; ?>, <?php
                  echo $counts; ?>);
                                            j++;
                                        </script>
                                        <?php $counts = $counts + 1; ?>
                                    <?php } ?>
                                <?php endif;
                                /**
                                 * Timer Ends
                                 */
                                ?>
                                <?php
                                /**
                                 * Ends super deals timer
                                 */
                                ?>
                            </div>
                             <?php if(!$_product->isSaleable()){
                                $mageSession = Mage::getSingleton("core/session",  array(
                                    "name"=>"frontend"
                                    ));
                                $breadcrumbs = $mageSession->getBreadcrumbProductDatalayer();
                                if(is_array($breadcrumbs)){
                                    unset($breadcrumbs['product']);
                                    $categories = array_slice($breadcrumbs, -2);
                                ?>
                            <div class="short-description stock-msg">
                                <p>
                                <?php echo $this->__("We regret the requested product is out of stock."); ?><br>
                                <?php echo $this->__("see more from"); ?>
                                <?php echo $this->__($_product->getAttributeText('manufacturer')); ?>
                                <?php echo $this->__("or similar items."); ?>
                                </p>
                                <?php 
                                if(count($categories)){ ?>
                                    <p class="two-categories">
                                    <?php foreach ($categories as $category){ ?>
                                    <span class="cat-name"><a onclick="oosCategoryClick();" href="<?php echo $category['link'] ?>"><?php echo $this->__($category['label']); ?></a></span>
                                    <?php } ?>
                                    </p>
                                <?php } ?>
                                
                            </div>
                            <?php 
                            }
                            }?>
                            <?php //die ("dfsfdsfgdsgg"); ?>
                        </div>
                        <div class="extra-info ">
                            <?php echo $this->getChildHtml('extrahint') ?>
                        </div>
                    </div>
                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getChildHtml('other'); ?>
                    <div class="product-options-block">
                        <?php
                        /**
                         * check the product is saleable
                         * and the product has options
                         */
                        if ($_product->isSaleable() && $this->hasOptions()):?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                        <?php endif; ?>
                        <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                        <?php endif; ?>
                    </div>
                    <div class="add-to-cart-wrapper">
                        <?php
                        /**
                         * Confirm the product does not have options
                         */
                        if (!$this->hasOptions()) {
                            ?>
                            <div class="add-to-box">
                                <?php
                                /**
                                 * Check the product is available for sale
                                 * if so display add to cart option
                                 */
                                if ($_product->isSaleable()): ?>
                                    <?php echo $this->getChildHtml('addtocart') ?>
                                    <?php
                                    /**
                                     * Check the wishlist option allowed for the product
                                     * or compare url is available for the product
                                     */
                                    if ($this->helper('wishlist')->isAllow() || $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                        <span class="or">
						<?php echo $this->__('OR') ?>
						</span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php echo $this->getChildHtml('addto') ?>
                                <?php echo $this->getChildHtml('sharing') ?>
                            </div>
                            <?php echo $this->getChildHtml('extra_buttons') ?>
                        <?php } /**
                         * else if the product has options
                         */
                        else {
                            /**
                             * Check the product is not saelable
                             * if so display options like
                             * add to
                             * sharing
                             */
                            if (!$_product->isSaleable()) { ?>
                                <div class="add-to-box">
                                    <?php echo $this->getChildHtml('addto') ?>
                                    <?php echo $this->getChildHtml('sharing') ?>
                                </div>
                            <?php }
                        } ?>
                    </div>
                    <p class="delivery"><?php echo $this->__($_product->getattributeText('product_delivery_terms')); ?></p>
                    <div class="detailpage_attribute_bottom">
                        <div class="ele">
                        <?php
                        /**
                         * Check detailed info group has been set
                         */
                        if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):
                            ?>
                            <?php foreach ($detailedInfoGroup as $alias => $html): ?>
                            <?php echo $html ?>
                        <?php endforeach; ?>
                        <?php endif; ?>
                        </div>
                        <a class="showmore-btn-desc" href="javascript:;"><?php echo $this->__("Show More"); ?></a>
                    </div>
                </div>
            </div>
            <div class="clearer"></div>

            <?php $eavConfig = Mage::getModel('eav/config');
            $attributes = $eavConfig->getEntityAttributeCodes(Mage_Catalog_Model_Product::ENTITY, $_product);

            $createBlock = $this->getLayout()->createBlock('core/template');
            echo $createBlock->setTemplate('catalog/product/sizeguide_modals.phtml')->toHtml();
            ?>

            <div class="modal fade" id="myModalSizeunavailable" tabindex="-1" role="dialog"
                 aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="vertical-alignment-helper">
                    <div class="modal-dialog vertical-align-center">
                        <div class="modal-content">
                            <div class="modal-header">
                                <a href="" class=" closebtnsizeguid btn btn-default" data-dismiss="modal">X</a>
                                <h5 class="modal-title"
                                    id="myModalLabel"><?php echo $this->__("Notify me if back in stock") ?></h5>
                            </div>
                            <div class="modal-body">
                                <div class="unavalablesize_area">
                                    <div class="container mainUnavailableSize">
                                        <main id="mainUnavailableSize" rol="main">
                                            <fieldset>
                                                <input type="email"
                                                       placeholder="<?php echo $this->__("Please enter a vaild email address") ?>"
                                                       class="mail" id="email_customer">

                                                <p class="error"></p>
                                                <input type="hidden" name="product_customer"
                                                       value="<?php echo $_product->getId() ?>" id="product_customer"/>
                                                <input type="hidden" name="product_name_customer"
                                                       value="<?php echo $_product->getName() ?>"
                                                       id="product_name_customer"/>
                                            </fieldset>
                                            <div class="link">
                                                <div class="add">
                                                    <div class="example">
                                                        <div>
                                                            <input id="checkbox1" type="checkbox" name="checkbox"
                                                                   value="1" checked="checked">
                                                            <label for="checkbox1">
															<span>
															</span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <h3><?php echo $this->__('Please sign me up to Elabels emails'); ?></h3>

                                                    <p><?php echo $this->__('Read our privacy and cookie policy'); ?>
                                                        <a href="#"><?php echo $this->__('here'); ?></a>
                                                    </p>
                                                </div>
                                                <div class="post">
                                                    <a onclick="sendEmail()"
                                                       class="send"><?php echo $this->__('send'); ?></a>
                                                </div>
                                            </div>
                                            <p class="message"></p>
                                        </main>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php echo $this->getChildHtml('marketplace_compareprice'); ?>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function (button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function (button, url) {
                if (this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }

            }.bind(productAddToCartForm);
            //]]>
        </script>
    </div>
    <div class="related-tabs">
        <?php echo $this->getChildHtml('related_products') ?>
        <div id="visenze-widget-container" class="visenze-widget-container" style="display: none;">
            <h3 class="visenze-widget-title"><?php echo $this->__('Similar Products'); ?></h3>
            <ul id="visenze-widget-slider" class="custom_slider visenze-widget-slider">
                <!-- a template for a single product HTML -->
            </ul>
        </div>
        
        <!-- NeoWize related products prefab -->
        <div id="neowize-widget-container" class="neowize-widget-container" style="display: none;">
            <h3 class="neowize-widget-title"><?php echo $this->__('You might also like'); ?></h3>
            <ul id="neowize-widget-slider" class="custom_slider neowize-widget-slider">
                <!-- a template for a single product HTML -->
            </ul>
        </div>
        <!-- /// NeoWize related products prefab end -->
    </div>
    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
</div>
<script>
    $j(function() {
        $j(document).on('click', 'div.detailpage_attribute_bottom a.showmore-btn-desc', function() {
            var _h = 0;
            console.log('clicked');
            if ($j(this).hasClass('opened')) {
              $j(this).removeClass('opened');
              $j('.detailpage_attribute_bottom').css({overflow:'hidden'}).animate({height: '188px'});
              $j(this).html('<?php echo $this->__("Show More"); ?>');
            } else {
              $j(this).addClass('opened');
              $j('.detailpage_attribute_bottom .ele').each(function() {
                _h+=$j(this).height();
              });
              // add extra margins
              _h+=115;
              $j('.detailpage_attribute_bottom').css({overflow:'visible'}).animate({height: _h+'px'});
              $j(this).html('<?php echo $this->__("Show Less"); ?>');
            }
        });
    });

    /**
     *    Tabs script start
     */
    $j('document').ready(function () {
        $j('.myTabs > ul > li > a').click(function () {
            var target = $j(this).data('target');
            var getParentId = $j(this).parents('.myTabs').parent().attr('id');
            var setParentId = '#' + getParentId;
            $j(setParentId + ' > .myTab_container > .tab_info').hide();
            $j(setParentId + ' > .myTab_container > .tab_info.' + target).show();
            $j(setParentId + ' > .myTabs > ul > li > a').removeClass('active');
            $j(this).addClass('active');
            return false;
        });
    });
/**
*	Tabs script end
*/
</script>

<script>
    function sendEmail() {
        var email = document.getElementById("email_customer").value;
        var Id = document.getElementById("product_customer").value;
        var name = document.getElementById("product_name_customer").value;
        var size = document.getElementById("product_size_customer").value;

        var reg = new RegExp("/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/");
        if (email == "") {
            jQuery(".error").html("This is a required field");

        }
        else if (email != "") {
            if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+.[A-Z]{2,4}$/i.test(email)) {
                jQuery(".error").html("Please enter a valid email");
            }
            else {
                jQuery(".error").html("");
                jQuery.ajax({
                    url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/marketplace/index/sendOrderEmail/',
                    type: 'POST',
                    data: {
                        email: email,
                        id: Id,
                        name: name,
                        size: size
                    },
                    beforeSend: function () {
                        jQuery('.message').html("<img src='<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>' />");
                    },
                    success: function (data) {

                        jQuery('.message').html("Message send successfully");
                    }
                });
            }
        }
    }
</script>
