<div id="payment-method" class="onestepcheckout_block">
    <h2 class="op_block_title" id="payment_m">2. <?php echo $this->__('Payment Methods') ?></h2>
    <script type="text/javascript">
	//<![CDATA[
		var payment = new Payment('payment-method');
		function toggleToolTip(event){
			if($('payment-tool-tip')){
				$('payment-tool-tip').setStyle({
					top: (Event.pointerY(event)-300)+'px',
					left: (Event.pointerX(event)-200)+'px'
				});
				$('payment-tool-tip').toggle();
			}
			Event.stop(event);
		}
	//]]>
	</script>
    <div class="checkout_payment_method_load_container">
        <div id="checkout-payment-storecredit-load" class="" style="width: auto; height: auto;"></div>
		<div id="checkout-payment-method-load">
			<?php echo $this->getChildHtml('methods') ?>
		</div>
		<div class="tool-tip" id="payment-tool-tip" style="display:none;">
			<div class="btn-close"><a href="javascript:;" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
			<div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
		</div>
	</div>
	
	
    <script type="text/javascript">
    //<![CDATA[
        payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
		
		if($('payment-tool-tip-close')){
			Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
		}
    //]]>
    </script>
</div>
