<div class="color-definition">
    <ul>
        <li>
            <div class="content-header">
                <h3>Color Statuses</h3>
            </div>
        </li>
        <li>
            <div class="circ_large">
                <div class="circ_one circ_inner circ_green"> </div>
                <div class="circ_two circ_inner circ_green"> </div>
            </div>
            <div class="circ_text larg_circ_text ">Confirmed</div>
        </li>
        <li>
            <div class="circ_large">
                <div class="circ_one circ_inner circ_red"> </div>
                <div class="circ_two circ_inner circ_red"> </div>
            </div>
            <div class="circ_text larg_circ_text ">Pending</div>
        </li>
        <li>
            <div class="circ_large">
                <div class="circ_one circ_inner circ_gray"> </div>
                <div class="circ_two circ_inner circ_gray"> </div>
            </div>
            <div class="circ_text larg_circ_text ">Cancelled</div>
        </li>
    </ul>
</div>