<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.6
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */
?>
<?php 
/**
 *  This will be used for creating new seller
 */
?>

<?php
$fbStatus = Mage::getStoreConfig('sociallogin/facebook/enable_fb');
/**
 * Check if twitter is enabaled or not
 */
$twitterStatus = Mage::getStoreConfig('sociallogin/twitter/enable_twitter');
/**
 * Check if google is enabaled or not
 */
$googleStatus = Mage::getStoreConfig('sociallogin/google/enable_google');
/**
 * Check if yahoo is enabaled or not
 */
$yahooStatus = Mage::getStoreConfig('sociallogin/yahoo/enable_yahoo');
/**
 * Check if social login is enabaled or not
 */
$enableStatus = Mage::getStoreConfig('sociallogin/general/enable_sociallogin');
/**
 * Check if customer logged in or not 
 */
$loggedIn = $this->helper("customer")->isLoggedIn();
$facebookappId = Mage::getStoreConfig('sociallogin/facebook/fbapp_id');
$sellerHelper  = Mage::helper('marketplace/marketplace'); //Call Marketplace helper.
?>

<div id="tab-2" class="tab-content">
					<div class="row">
						<div class="account-create">
    
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php //echo $this->getMessagesBlock()->toHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.register.extra')?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />			
			<div class="col-xs-6">
				
				<div class="page-title">
					<h2><?php echo $this->__('Create an Account') ?></h2>
				</div>
				
				<ul class="form-list">
                    <li>
                        <div class="input-box">
                            <input placeholder="<?php echo $this->__('Store Name*')?>" type="text" name="store_name" id="store_name" value="<?php echo $this->escapeHtml($this->getFormData()->getStoreName()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Store Name')) ?>" class="input-text required-entry" />
                        </div>
                    </li>

					<li class="fields">
						<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
					</li>
					
					<li>
						<div class="input-box">
							<input placeholder="<?php echo $this->__('Email*')?> " type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" />
						</div>
					</li>

					<li class="fields">
						<div class="input-box">
							<!--label for="country" class="required">Country <em>*</em> </label -->  
							<label style="display:block !important " for="category_product" class="required"><?php echo $this->__('What Product are you selling?') ?> <em>*</em></label>
							<select name="category_product" id="category_product" class="validate-select input-text category_product normal-select" title="What Product are you selling?">
								<option value="">-- <?php echo $this->__('-- Please Select --') ?> --</option>
							<?php $_helper = Mage::helper('catalog/category') ?>
							<?php $_categories = $_helper->getStoreCategories() ?>
							<?php $currentCategory = Mage::registry('current_category') ?>
							<?php if (count($_categories) > 0): ?>
						        <?php foreach($_categories as $_category): ?>
						            <option value="<?php echo $_category->getId() ?>"><?php echo $this->__($_category->getName()); ?></option>
						                <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
						                <?php $_subcategories = $_category->getChildrenCategories() ?>
						                <?php if (count($_subcategories) > 0): ?>
						                    <?php foreach($_subcategories as $_subcategory): ?>
											<option value="<?php echo $_subcategory->getId() ?>">&nbsp;&nbsp;&nbsp;<?php echo $this->__($_subcategory->getName())?></option>

													<?php $_subcategory = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>
									                <?php $_subcategories_sub = $_subcategory->getChildrenCategories() ?>
									                <?php if (count($_subcategories_sub) > 0): ?>
									                    <?php foreach($_subcategories_sub as $_subcategory_sub): ?>
														<option value="<?php echo $_subcategory_sub->getId() ?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->__($_subcategory_sub->getName())?></option>
									                    <?php endforeach; ?>
									                <?php endif; ?>

						                    <?php endforeach; ?>
						                <?php endif; ?>
						        <?php endforeach; ?>
							<?php endif; ?>
							</select>
						</div>
					</li>
				
				<li class="fields clearfix">
				<div class="store_logos_fields">
				<label style="display:block !important" for="sample_product_profile_file"><?php echo $this->__('Upload your profile or sample products'); ?>  </label>
				<div class="store_logos clearfix">
					<div class="input-group">
					<label class="input-group-btn">
					<span class="btn">
					<?php echo $this->__('Choose File') ?>&hellip; <input type="file" style="display: none;" name="sample_product_profile_file" class="sample_product_profile_file required-entry" id="sample_product_profile_file" onchange="return validateFileExtension(this);"  >
					</span>
					</label>
					<input type="text" class="form-control required-entry" readonly name="Zip_file">
					</div>
				</div>
				<div style="display:none;color:red;" class="fileupload"><?php echo $this->__("File type is not correct. Pdf and zip file are allowed only."); ?></div>
				</div>

					</li>
					
					<li class="fields clearfix">
						<div class="field_store_logos">
							<label style="display:block !important" for="store_logo"><?php echo $this->__('Store Logo'); ?>  </label>
							<div class="store_logos clearfix">
								<div class="input-group">
								<label class="input-group-btn">
								<span class="btn">
								<?php echo $this->__('Choose File') ?>&hellip; <input type="file" style="display: none;" name="store_logo" class="store_logo required-entry" id="store_logo" onchange="return validateFileExtensionImage(this);"  >
								</span>
								</label>
								<input type="text" class="form-control required-entry" readonly name="graphic_file">
								</div>
							</div>
							<div style="display:none;color:red;" class="imageupload"><?php echo $this->__("File type is not correct. bmp,png,gif,jpg and jpeg file are allowed only."); ?></div>
						</div>
					</li>
					
				</ul>
			
			</div>

			<div class="col-xs-6">
			
				<div class="social_signup_block">
				<?php echo $this->getLayout()->createBlock("sociallogin/buttons")->setTemplate("sociallogin/customer/buttons.phtml")->toHtml(); ?>
				<?php echo $this->getChildHtml('oneall.sociallogin.login.login'); ?>
				</div>
				<ul class="form-list gender-info">
					<?php if ($this->isNewsletterEnabled()): ?>
					
					<?php endif ?>
					
					<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
					<?php if ($_gender->isEnabled()): ?>
						<li class="reg-gender"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
					<?php endif ?>
					
					<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
					<?php if ($_dob->isEnabled()): ?>
						<li class="hidden"><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
					<?php endif ?>
					
					<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
					<?php if ($_taxvat->isEnabled()): ?>
						<li class="hidden"><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
					<?php endif ?>
					<li style="margin-top: 1px;">
                        <div class="input-box">
                            <input type="text" name="phone_no" id="telephone" value="" placeholder="<?php echo $this->__('Telephone'); ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </li>
					
					<li style="margin-top: 1px;" class="have_stores">
                        <div class="fields">
							<label style="display:block !important " for="have_store" class="required"><?php echo $this->__('Do You have a Store') ?> <em>*</em></label>

							<div class="input-box">
							<label for="have_store" class="have_store_label">
							<input type="radio" name="have_store" id="have_store" value="yes" class="validate-one-required-by-name"><?php echo $this->__('Yes'); ?>
							<input type="radio" name="have_store" id="have_store" value="no" class="validate-one-required-by-name"><?php echo $this->__('No'); ?>
							</label>
							</div>

                        </div>
                    </li>
					
					<li style="margin-top: 1px;">
                        <div class="input-box">
							<label for="no_of_style" class="required"><?php echo $this->__('How Many Styles Do You Have?') ?> <em>*</em></label>
                            <input type="text" name="no_of_style" id="no_of_style" value="" placeholder="<?php echo $this->__('How Many Styles Do You Have?');?> *" title="<?php echo $this->__('How Many Styles Do You Have?') ?>" class="input-text required-entry no_of_style" />
                        </div>
                    </li>
					
					<li>
						<div class="input-box">
							<input placeholder="<?php echo $this->__('Password*') ?>" type="password" name="password" id="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" class="input-text required-entry validate-password" />
						</div>
					
					</li>
					
					<li>
						<div class="input-box">
							<input placeholder="<?php echo $this->__('Confirm Password*')?>" type="password" name="confirmation" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
						</div>
					</li>
					<li>
						<div class="input-box">
							<input type="checkbox" name="is_subscribed" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
							<label for="is_subscribed" class="is_subscribed_label"><?php echo $this->__('Newsletter') ?></label>
						</div>
						<?php /* Extensions placeholder */ ?>
						<?php echo $this->getChildHtml('customer.form.register.newsletter')?>
					</li>
					
				</ul>
				
				<div class="buttons-set">
					<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><?php echo $this->__('Register') ?></button>
				</div>
				
			</div>
			
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        
        
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

</div>

</div>


<script type="text/javascript">
	//<![CDATA[
	var dataForm = new VarienForm('form-validate', true);
<?php if ($this->getShowAddressFields()): ?>
		new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
<?php endif; ?>
	
	function validateFileExtension(fld) {
        if (!/(\.zip|\.pdf)$/i.test(fld.value)) {
            fld.focus();
			fld.value = '';
            jQuery('.fileupload').show();
            return false;
        }else{
			jQuery('.fileupload').hide();
		}
        return true;
    }        
	function validateFileExtensionImage(fld) {
        if (!/(\.bmp|\.png|\.gif|\.jpg|\.jpeg)$/i.test(fld.value)) {
            fld.focus();
			fld.value = '';
			jQuery('.imageupload').show();
            return false;
        }else{
			jQuery('.imageupload').hide();
		}
        return true;
    }
	

	//]]>
    <?php if ($_gender->isEnabled()): ?>
        jQuery('.reg-gender select').addClass('validate-select');
    <?php endif; ?>
</script>
</div> <!-- end row -->

