<?php
/**
 * Progos_OrdersEdit
 *
 * @category    Progos
 * @package     Progos_OrdersEdit
 * @author      Touqeer Jalal <touqeer.jalal@progos.org>
 * @copyright   Copyright (c) 2017 Progos, Ltd (http://progos.org)
 */
?>
<script type="text/javascript">
    orderAddress.setAddresses(<?php echo $this->getAddressCollectionJson() ?>);
</script>
<?php
	$_fieldsContainerId = 'order-address_fields';
	$order = $this->getOrder();
	$orderId = $order->getId();
	if($this->getIsShipping()):
		$_addressChoiceContainerId = 'order-shipping_address_choice';
		$blockId = 'shipping_address';
	else:
		$_addressChoiceContainerId = 'order-billing_address_choice';
		$blockId = 'billing_address';
	endif;
?>
<div id = "<?php echo $_addressChoiceContainerId ?>" class="order-choose-address">
    <?php echo Mage::helper('sales')->__('Select from existing customer addresses:') ?>
    
    <?php 
    $guestAddresses = $this->getSyncAddressCollection();
    if(count($guestAddresses)){ ?>
    <br /><p><?php echo Mage::helper('sales')->__('Note: This customer has past orders and if you want to sync, click Addresses Sync button.') ?></p>
    <button class="f-right scalable add" type="button" title="<?php echo Mage::helper('sales')->__('Sync Addresses')?>" onclick="orderEdit.loadEditForm('shipping_address', this.up('div.entry-edit').down('fieldset'), '<?php echo $orderId?>'); return false;">
        <span><span><?=Mage::helper('sales')->__('Sync Addresses')?></span></span>
    </button><br/><br/>
    
    <?php } ?>
    <?php $_id = $this->getForm()->getHtmlIdPrefix() . 'customer_address_id' ?>
    <select id="<?php echo $_id ?>"  name="<?php echo $this->getForm()->getHtmlNamePrefix()?>[customer_address_id]" style="width:97.5%;" onchange="orderAddress.selectAddress(this, '<?php echo $_fieldsContainerId ?>')">
        <option value=""><?php echo Mage::helper('sales')->__('Add New Address') ?></option>
        <?php foreach ($this->getAddressCollection() as $_address): ?>
            <option value="<?php echo $_address->getId() ?>"<?php if ($_address->getId()==$this->getAddressId()): ?> selected="selected"<?php endif; ?>>
                <?php echo $this->getAddressAsString($_address) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>

<div id="order-address_fields" class="entry-edit">
    <div class="fieldset">
        <?php echo $this->getForm()->toHtml() ?>
    </div>
</div>
<script type="text/javascript">
    VatParameters.groupIdHtmlId = <?php echo $this->getCustomer()->getGroupId(); ?>;    
</script>
