<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Rma
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $_order = $this->getOrder();
$helper = Mage::helper('progos_sales/customer');
$orderStatuses = $helper->runtimeChangeOrderStatusLabel();
$orderStatusLabel = $helper->getOrderStatusHtml($_order->getStatus(), $orderStatuses );
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $orderStatusLabel ) ?></h1>
    <?php if ($this->helper('rss/order')->isStatusNotificationAllow()): ?>
        <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="link-rss"><?php echo $this->__('Subscribe to Order Status') ?></a>
        <span class="separator">|</span>
    <?php endif; ?>
    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
        <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
        <span class="separator">|</span>
    <?php endif ?>
    <a href="<?php echo $this->getPrintUrl($_order) ?>" class="link-print" onclick="this.target='_blank';"><?php echo $this->__('Print Order') ?></a>
    <?php if (Mage::helper('awrma')->isEnabled() && Mage::helper('awrma')->isAllowedForOrder($_order)) : ?>
        <span class="separator">|</span>
        <a href="<?php echo $this->getUrl('awrma/customer_rma/createfororder/', array('order_id' => $_order->getIncrementId())) ?>" class="link-print"><?php echo $this->__('Return Request') ?></a>
    <?php endif ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
            <?php foreach ($_links as $_link): ?>
                <?php if($_link->getUrl()): ?>
                <?php if(($_link->getLabel() !== "Track Order") && ($_link->getLabel() !== "متابعة الامر")):?>
                    <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php elseif (($_link->getLabel() == "Track Order") || ($_link->getLabel() == "متابعة الامر")): ?>
                    <li><a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackshipment','width=800,height=600,top=0,left=0,resizable=yes,scrollbars=yes'); return false;" title="<?php
                        echo $this->__('Track this shipment') ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
                <?php else: ?>
                    <li class="current"><?php echo $_link->getLabel() ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
    <div class="col2-set order-info-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipping Address') ?></h2>
                </div>
                <div class="box-content">
                    <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <?php
                    $shippingmethod = $this->escapeHtml($_order->getShippingMethod()); 
                    $shippingmethodDescription = $this->escapeHtml($_order->getShippingDescription());
                    if($shippingmethodDescription != 0){
                        if (is_numeric($shippingmethodDescription)) {
                            echo "<div class='box-title'><h2>".$this->__('Shipping Charges')."</h2></div>";
                            echo "<div class='box-content'><p>".$shippingmethodDescription."</p></div>";
                        }
                        else{
                            echo "<div class='box-title'><h2>".$this->__('Shipping Method')."</h2></div>";
                            echo "<div class='box-content'><p>".$this->__($shippingmethodDescription)."</p></div>";
                        }
                    }
                    else{
                        if($shippingmethod == "freeshipping_freeshipping"){
                            echo "<div class='box-title'><h2>".$this->__('Shipping Method')."</h2></div>";
                            echo "<div class='box-content'><p>".$this->__('Free Shipping')."</p></div>";
                        }
                        else if($shippingmethod){
                            echo "<div class='box-title'><h2>".$this->__('Shipping Method')."</h2></div>";
                            echo "<div class='box-content'><p>".$this->__($shippingmethod)."</p></div>";
                        }
                        else{
                            echo "<div class='box-title'><h2>".$this->__('Shipping Method')."</h2></div>";
                            echo "<div class='box-content'><p>".$this->helper('sales')->__('No shipping information available')."</p></div>";
                        }
                    }
                    ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>