<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.6
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */

/**
 * This file is used to display navigation links in "Seller My Account"
 * 
 * Links displayed are Seller Dashboard, Manage Products, Orders, Transaction History,
 * My Profile, Contact Admin and Vacation Mode
 */

$loginId = Mage::getSingleton('customer/session')->isLoggedIn();
$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
$getGroupId = Mage::helper('marketplace')->getGroupId();
$customer = Mage::getSingleton("customer/session")->getCustomer();
$customerStatus = $customer->getCustomerstatus();
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo Mage::helper('marketplace')->__('Market Place'); ?></span></strong>
    </div>
    <div class="block-content">
        <?php      
        if ($groupId == $getGroupId && $loginId && $customerStatus != 2 && $customerStatus != 0) { ?>
            <ul>
                <?php 
                /*
                * For sellers               
                */?>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/dashboard')->dashboardUrl()) { ?>current<?php } ?>">
                <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/dashboard')->dashboardUrl()) { ?>
                <strong>
                <?php echo $this->__('Seller Dashboard'); ?>
                </strong>
                <?php }else{ ?>
                <a href="<?php echo Mage::helper('marketplace/dashboard')->dashboardUrl(); ?>">
                <?php echo $this->__('Seller Dashboard'); ?>
                </a>
                <?php } ?>                
                </li>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getManageProductUrl() || Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getNewProductUrl()) {
                    ?>current<?php 
        } ?>">         
        <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getManageProductUrl() || Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getNewProductUrl()) { ?>
        <strong><?php echo $this->__('Manage Products'); ?></strong>
        <?php }else{ ?>
        <a href="<?php echo Mage::helper('marketplace/url')->getManageProductUrl() ?>">
        <?php echo $this->__('Manage Products'); ?>
        </a>
        <?php } ?>
        </li>
                <?php if (Mage::getStoreConfig('marketplace/product/assign_product') == 1) { ?>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getAssignProductUrl()) {
                    ?>current<?php 
        } ?>">        
        <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getAssignProductUrl()) { ?>
        <strong><?php echo $this->__('Assign Products'); ?></strong> 
        <?php }else{ ?>
        <a href="<?php echo Mage::helper('marketplace/url')->getAssignProductUrl(); ?>"> 
        <?php echo $this->__('Assign Products'); ?>
        </a> 
        <?php } ?>
        </li>
                <?php } ?>             
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getManageOrderUrl()) {
                    ?>current<?php 
        } ?>">        
        <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getManageOrderUrl()) { ?>
        <strong><?php echo $this->__('Orders'); ?></strong>
        <?php }else{ ?>
        <a href="<?php echo Mage::helper('marketplace/url')->getManageOrderUrl(); ?>"> 
        <?php echo $this->__('Orders'); ?>
        </a>
        <?php } ?>        
        </li>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/transaction')->getViewtransaction()) {
                    ?>current<?php 
        } ?>"> 
        <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/transaction')->getViewtransaction()) { ?>
        <strong>
        <?php echo $this->__('Transaction History'); ?>
        </strong>
        <?php }else{ ?>
        <a href="<?php echo Mage::helper('marketplace/transaction')->getViewtransaction(); ?>">
        <?php echo $this->__('Transaction History'); ?>
        </a>
        <?php } ?>
        </li>
        <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->addprofileUrl()) {
                    ?>current<?php 
        } ?>">        
        <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->addprofileUrl()) { ?>
        <strong>
        <?php echo $this->__('My Profile'); ?>
        </strong>
        <?php }else{ ?>
        <a href="<?php echo Mage::helper('marketplace/url')->addprofileUrl(); ?>">
        <?php echo $this->__('My Profile'); ?>
        </a>
        <?php } ?>
        </li>
                <?php if (Mage::getStoreConfig('marketplace/admin_approval_seller_registration/contact_admin') == 1) {
                     ?>
                    <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/common')->getContactFormUrl()) {
                        ?>current<?php 
                } ?>">               
                <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/common')->getContactFormUrl()) { ?>
                <strong><?php echo $this->__('Contact Admin'); ?></strong> 
                <?php }else{ ?>
                 <a href="<?php echo Mage::helper('marketplace/common')->getContactFormUrl(); ?>"> 
                <?php echo $this->__('Contact Admin'); ?>
                </a>
                <?php } ?>
                </li>
                <?php } ?>
                <?php if (Mage::getStoreConfig('superdeals/superdeals_group/deals_enable') == 1) {
                     ?>
                    <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getManageDealsUrl()) {
                        ?>current<?php 
                } ?>">             
                <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getManageDealsUrl()) { ?>
                <strong><?php echo $this->__('Manage Deals'); ?></strong>
                <?php }else{ ?>
                <a href="<?php echo Mage::helper('marketplace/url')->getManageDealsUrl(); ?>"> 
                <?php echo $this->__('Manage Deals'); ?>
                </a>
                <?php } ?>                
                </li>
                <?php } ?>
                <?php if (Mage::getStoreConfig('marketplace/admin_approval_seller_registration/vacation_mode') == 1) { ?>
                    <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getVacationModeUrl()) {
                        ?>current<?php 
                 } ?> last">                  
                 <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->getVacationModeUrl()) { ?>
                 <strong><?php echo $this->__('Vacation Mode') ?></strong>
                 <?php }else{ ?>
                 <a href="<?php echo Mage::helper('marketplace/url')->getVacationModeUrl(); ?>">
                 <?php echo $this->__('Vacation Mode') ?>
                 </a>
                 <?php } ?>                 
                 </li>
                <?php } ?>
            </ul>
        <?php } else { ?>
            <ul>
               <?php 
                /*
                * For Buyers               
                */?>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->becomemerchantUrl()) {
                    ?>current<?php 
                  } ?>"> 
                  <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/url')->becomemerchantUrl()) { ?>
                  <strong><?php echo $this->__('Become a Seller'); ?></strong>
                  <?php }else{ ?>
                  <a href="<?php echo Mage::helper('marketplace/url')->becomemerchantUrl(); ?>"> 
                  <?php echo $this->__('Become a Seller'); ?>
                  </a>
                  <?php } ?>
                  </li>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/common')->customerreviewUrl()) {
                    ?>current<?php 
                  } ?> last">                  
                  <?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('marketplace/common')->customerreviewUrl()) { ?>
                  <strong><?php echo $this->__('Seller Reviews'); ?></strong> 
                  <?php }else{ ?>
                  <a href="<?php echo Mage::helper('marketplace/common')->customerreviewUrl(); ?>"> 
                  <?php echo $this->__('Seller Reviews'); ?> 
                  </a>
                  <?php } ?>                
                  </li>
            </ul>
        <?php } ?>
    </div>
</div>