<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Owner
 * Date: 06.02.12
 * Time: 16:17
 * To change this template use File | Settings | File Templates.
 */
class Infomodus_Dhllabel_Model_Config_Options
{
    public function getProvinceCode($code)
    {
        $provinceCode = array(
            'Alabama' => 'AL',
            'Alaska' => 'AK',
            'American Samoa' => 'AS',
            'Arizona' => 'AZ',
            'Arkansas' => 'AR',
            'Armed Forces Africa' => 'AE',
            'Armed Forces Americas' => 'AA',
            'Armed Forces Canada' => 'AE',
            'Armed Forces Europe' => 'AE',
            'Armed Forces Middle East' => 'AE',
            'Armed Forces Pacific' => 'AP',
            'California' => 'CA',
            'Colorado' => 'CO',
            'Connecticut' => 'CT',
            'Delaware' => 'DE',
            'District of Columbia' => 'DC',
            'Federated States Of Micronesia' => 'FM',
            'Florida' => 'FL',
            'Georgia' => 'GA',
            'Guam' => 'GU',
            'Hawaii' => 'HI',
            'Idaho' => 'ID',
            'Illinois' => 'IL',
            'Indiana' => 'IN',
            'Iowa' => 'IA',
            'Kansas' => 'KS',
            'Kentucky' => 'KY',
            'Louisiana' => 'LA',
            'Maine' => 'ME',
            'Marshall Islands' => 'MH',
            'Maryland' => 'MD',
            'Massachusetts' => 'MA',
            'Michigan' => 'MI',
            'Minnesota' => 'MN',
            'Mississippi' => 'MS',
            'Missouri' => 'MO',
            'Montana' => 'MT',
            'Nebraska' => 'NE',
            'Nevada' => 'NV',
            'New Hampshire' => 'NH',
            'New Jersey' => 'NJ',
            'New Mexico' => 'NM',
            'New York' => 'NY',
            'North Carolina' => 'NC',
            'North Dakota' => 'ND',
            'Northern Mariana Islands' => 'MP',
            'Ohio' => 'OH',
            'Oklahoma' => 'OK',
            'Oregon' => 'OR',
            'Palau' => 'PW',
            'Pennsylvania' => 'PA',
            'Puerto Rico' => 'PR',
            'Rhode Island' => 'RI',
            'South Carolina' => 'SC',
            'South Dakota' => 'SD',
            'Tennessee' => 'TN',
            'Texas' => 'TX',
            'Utah' => 'UT',
            'Vermont' => 'VT',
            'Virgin Islands' => 'VI',
            'Virginia' => 'VA',
            'Washington' => 'WA',
            'West Virginia' => 'WV',
            'Wisconsin' => 'WI',
            'Wyoming' => 'WY',
            /* Canada */
            'Alberta' => 'AB',
            'British Columbia' => 'BC',
            'Manitoba' => 'MB',
            'New Brunswick' => 'NB',
            'Newfoundland and Labrador' => 'NL',
            'Northwest Territories' => 'NT',
            'Nova Scotia' => 'NS',
            'Nunavut' => 'NU',
            'Ontario' => 'ON',
            'Prince Edward Island' => 'PE',
            'Quebec' => 'QC',
            'Saskatchewan' => 'SK',
            'Yukon' => 'YT',
            /* Italy */
            'Agrigento' => 'AG',
            'Alessandria' => 'AL',
            'Ancona' => 'AN',
            'Aosta' => 'AO',
            'Ascoli Piceno' => 'AP',
            'L\'Aquila' => 'AQ',
            'Arezzo' => 'AR',
            'Asti' => 'AT',
            'Avellino' => 'AV',
            'Bari' => 'BA',
            'Bergamo' => 'BG',
            'Biella' => 'BI',
            'Belluno' => 'BL',
            'Benevento' => 'BN',
            'Bologna' => 'BO',
            'Brindisi' => 'BR',
            'Brescia' => 'BS',
            'Barletta-Andria-Trani' => 'BT',
            'Bolzano' => 'BZ',
            'Cagliari' => 'CA',
            'Campobasso' => 'CB',
            'Caserta' => 'CE',
            'Chieti' => 'CH',
            'Carbonia-Iglesias' => 'CI',
            'Caltanissetta' => 'CL',
            'Cuneo' => 'CN',
            'Como' => 'CO',
            'Cremona' => 'CR',
            'Cosenza' => 'CS',
            'Catania' => 'CT',
            'Catanzaro' => 'CZ',
            'Enna' => 'EN',
            'Forlì-Cesena' => 'FC',
            'Ferrara' => 'FE',
            'Foggia' => 'FG',
            'Firenze' => 'FI',
            'Fermo' => 'FM',
            'Frosinone' => 'FR',
            'Genova' => 'GE',
            'Gorizia' => 'GO',
            'Grosseto' => 'GR',
            'Imperia' => 'IM',
            'Isernia' => 'IS',
            'Crotone' => 'KR',
            'Lecco' => 'LC',
            'Lecce' => 'LE',
            'Livorno' => 'LI',
            'Lodi' => 'LO',
            'Latina' => 'LT',
            'Lucca' => 'LU',
            'Monza e della Brianza' => 'MB',
            'Macerata' => 'MC',
            'Messina' => 'ME',
            'Milano' => 'MI',
            'Mantova' => 'MN',
            'Modena' => 'MO',
            'Massa-Carrara' => 'MS',
            'Matera' => 'MT',
            'Napoli' => 'NA',
            'Novara' => 'NO',
            'Nuoro' => 'NU',
            'Ogliastra' => 'OG',
            'Oristano' => 'OR',
            'Olbia-Tempio' => 'OT',
            'Palermo' => 'PA',
            'Piacenza' => 'PC',
            'Padova' => 'PD',
            'Pescara' => 'PE',
            'Perugia' => 'PG',
            'Pisa' => 'PI',
            'Pordenone' => 'PN',
            'Prato' => 'PO',
            'Parma' => 'PR',
            'Pistoia' => 'PT',
            'Pesaro e Urbino' => 'PU',
            'Pavia' => 'PV',
            'Potenza' => 'PZ',
            'Ravenna' => 'RA',
            'Reggio Calabria' => 'RC',
            'Reggio Emilia' => 'RE',
            'Ragusa' => 'RG',
            'Rieti' => 'RI',
            'Roma' => 'RM',
            'Rimini' => 'RN',
            'Rovigo' => 'RO',
            'Salerno' => 'SA',
            'Siena' => 'SI',
            'Sondrio' => 'SO',
            'La Spezia' => 'SP',
            'Siracusa' => 'SR',
            'Sassari' => 'SS',
            'Savona' => 'SV',
            'Taranto' => 'TA',
            'Teramo' => 'TE',
            'Trento' => 'TN',
            'Torino' => 'TO',
            'Trapani' => 'TP',
            'Terni' => 'TR',
            'Trieste' => 'TS',
            'Treviso' => 'TV',
            'Udine' => 'UD',
            'Varese' => 'VA',
            'Verbano-Cusio-Ossola' => 'VB',
            'Vercelli' => 'VC',
            'Venezia' => 'VE',
            'Vicenza' => 'VI',
            'Verona' => 'VR',
            'Medio Campidano' => 'VS',
            'Viterbo' => 'VT',
            'Vibo Valentia' => 'VV',
            '' => '',
        );
        if (array_key_exists($code, $provinceCode)) {
            return $provinceCode[$code];
        }
        else {
            return $code;
        }
    }

    public function getUnitOfMeasurement(){
        $array = array(
            'I' => 'Inches',
            'C' => 'Centimeters',
        );
        return $array;
    }
}