<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2.3
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php 

$menuData = Mage::helper('custommenu')->getMenuData(); 
extract($menuData);

?>
<div class="nav-container">

    <div id="custommenu-loading" class="<?php echo $_rtl ? ' rtl' : ''; ?>">
        <div class="menu">
            <div class="parentMenu menu0">
                <a href="javascript:;">
                    <span><?php echo $this->__('Loading...'); ?></span>
                </a>
            </div>
        </div>
        <div class="clearBoth"></div>
    </div>
	
    <div id="custommenu" class="<?php echo $_rtl ? ' rtl' : ''; ?>" style="display:none;">
        <div class="menu">
            <div class="parentMenu menu0">
                <a href="javascript:;">
                    <span><?php echo $this->__('Loading...'); ?></span>
                </a>
            </div>
        </div>
		
        <div class="clearBoth"></div>
    </div>
	
    <div id="custommenu-mobile" class="<?php echo $_rtl ? ' rtl' : ''; ?>" style="display:none;">
        <div id="menu-button" onclick="MenuButtonToggle()" style="display:none !important;">
            <a href="javascript:void(0);">
                <span><?php echo $this->__('Menu'); ?></span>
            </a>
        </div>
        <div id="menu-content" style="display:block !important;">
            <div id="menu-mobile-loading" class="menu-mobile level0">
                <div class="parentMenu">
                    <a href="javascript:;">
                        <span><?php echo $this->__('Loading...'); ?></span>
                    </a>
                </div>
            </div>
            <div class="clearBoth"></div>
        </div>
    </div>
	
	<?php
		$catalogSearchHelper =  $this->helper('catalogsearch');
	?>
	<form id="search_mini_form" novalidate action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get" class="site_search inline_form_container ng-pristine ng-valid">
		<label for="site_search_term">Search</label>
		<input type="text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->__('Search entire store here...') ?>" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" class="site_search_term term required-entry" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" />
		<button type="submit" class="site_search_submit submit" title="<?php echo $this->__('Search') ?>"><i>Search</i></button>
		<ul ng-show="suggestions" class="site_search_suggestions ng-hide"></ul>
		
		<div id="search_autocomplete" class="search-autocomplete"></div>
	</form>
	
</div>
<script type="text/javascript">
//<![CDATA[
var CUSTOMMENU_POPUP_WIDTH = <?php echo $_popupWidth; ?>;
var CUSTOMMENU_POPUP_TOP_OFFSET = <?php echo $_popupTopOffset; ?>;
var CUSTOMMENU_POPUP_DELAY_BEFORE_DISPLAYING = <?php echo $_popupDelayBeforeDisplaying; ?>;
var CUSTOMMENU_POPUP_DELAY_BEFORE_HIDING = <?php echo $_popupDelayBeforeHiding; ?>;
var CUSTOMMENU_RTL_MODE = <?php echo $_rtl; ?>;
var CustommenuTimerShow = {};
var CustommenuTimerHide = {};
var ActiveMenu = null;
var MobileMenuEnabled = <?php echo $_mobileMenuEnabled; ?>;
var MenuAjaxUrl = '<?php echo $_menuAjaxUrl; ?>';
var MoblieMenuAjaxUrl = '<?php echo $_moblieMenuAjaxUrl; ?>';
var PopupMenuContent = '';
var MobileMenuContent = '';
CustomMenuMobileToggle();
Event.observe(window, 'resize', function() {
    CustomMenuMobileToggle();
});
//]]>
</script>
