<?php 

//echo get_class($this);
$brands = $this->getdesignerCollection();
$mediaurl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>
<?php $_helperOutput = $this->helper('catalog/output'); ?>

<div class="images-page-index image-page">
  

  <!-- <div class="single_designer">
    <a href=""><img src="" /></a>
  </div> -->
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('desinger-page-big-image')->toHtml();  ?>
  <?php   
      $c = 1; 
      foreach($brands as $brand): 
        $store = Mage::app()->getStore()->getId();

        $p = Mage::getModel('shopbybrand/brand')->setStoreId($store)->load($brand->getId());
        if($brand['is_designer_image']!=""):?>

      <div class="single_designer">
      <?php if($brand['is_upcoming']==0):?>
        <a href="<?php echo Mage::getBaseUrl().$brand['url_key'] ?>" ><img src="<?php echo $mediaurl."brands/designer/".$brand['brand_id']."/".$brand["is_designer_image"]?>"></a>
      <?php elseif($brand['is_upcoming']==1): ?>
            <a href="#" ><img src="<?php echo $mediaurl."brands/designer/".$brand['brand_id']."/".$brand["is_designer_image"]?>"></a>
      <?php endif; ?>
      </div>
      <?php 
      $c++;
         endif;
       endforeach;
     ?>

  <?php /* ?>
  
  <div class="row">
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('desinger-page-big-image')->toHtml();  ?>
   <?php   
   	  $c = 1; 
      foreach($brands as $brand): 
        $store = Mage::app()->getStore()->getId();

        $p = Mage::getModel('shopbybrand/brand')->setStoreId($store)->load($brand->getId());
        if($brand['is_designer_image']!=""):?>

      <div class="col-sm-3 image-holder <?php echo (($c<=4) ? "rside" : "bottomblock"); ?>">
      <?php if($brand['is_upcoming']==0):?>
      	<a href="<?php echo Mage::getBaseUrl().$brand['url_key'] ?>" ><img src="<?php echo $mediaurl."brands/designer/".$brand['brand_id']."/".$brand["is_designer_image"]?>"></a>
      <?php elseif($brand['is_upcoming']==1): ?>
            <a href="#" ><img src="<?php echo $mediaurl."brands/designer/".$brand['brand_id']."/".$brand["is_designer_image"]?>"></a>
      <?php endif; ?>
        <?php if($p->getPercentageDiscount() != ""): ?>
        <div class="title">
        	<!-- <h2><?php echo $this->__('up to'); ?> <span><?php echo $this->__($brand['percentage_discount']) ?>% </span><?php echo $this->__('off'); ?></h2> -->

              
              <h2><?php echo $p->getPercentageDiscount(); ?></h2>
            
          <!-- <h2><?php echo $this->__($brand['percentage_discount']) ?></h2> -->
        </div>
        <?php endif; ?>
        <?php if($brand['is_upcoming']==0):?>
        <a href="<?php echo Mage::getBaseUrl().$brand['url_key'] ?>" class="detail"><?php echo $this->__('shop now'); ?></a>
      <?php elseif($brand['is_upcoming']==1): ?>
             <p class="detail"><?php echo $this->__('Coming Soon'); ?></p>
      <?php endif ?>
      </div>
      <?php 
	  	$c++;
         endif;
       endforeach;
     ?>
    </div>
  
    <?php */ ?>


</div>
