<?php
require_once 'common.phtml';
$pageTitle = Mage::getSingleton('cms/page')->getTitle();
?>
    <script>
        window.dataLayer = window.dataLayer || [];
        dataLayer = [{
            'pageType': '<?php echo $pageTitle; ?>',
            'pageCategory': 'CMS',
            'userId': '<?php echo $customerId; ?>',
            'sha256Email': '<?php echo $customerSha256Email; ?>',
            'md5Email': '<?php echo $customerMd5Email; ?>',
            'userType': '<?php echo $user; ?>',
            'loggedInStatus': '<?php echo $loggedInStatus; ?>',
            'storeCountry': '<?php echo $store->getName(); ?>',
            'storeLanguage': '<?php echo $language; ?>',
            'currencyCode': '<?php echo $currency_code; ?>'
        }];
    </script>
<?php echo Mage::getStoreConfig('infotrust/infotrust/script'); ?>
<?php
if (Mage::getSingleton('cms/page')->getIdentifier() == 'registered-sucess' && Mage::getSingleton('checkout/session')->getRegisterCustomerFirstTime()) {
    ?>
    <script type="text/javascript">
        if (window.promotionData !== undefined) {
            dataLayer.push({
                'pageType': 'My Account',
                'pageCategory': 'No Category',
                'userId': window.promotionData.userId,
                'userType': window.promotionData.userType,
                'loggedInStatus': window.promotionData.loggedInStatus,
                'storeCountry': window.promotionData.storeCountry,
                'storeLanguage': window.promotionData.storeLanguage,
                'currencyCode': window.promotionData.currency_code,
                'event': 'customEvent',
                'eventCategory': 'User Engagement',
                'eventAction': 'Micro Conversion',
                'eventLabel': 'User Registration'
            });
        }
    </script>
    <?php
    Mage::getSingleton('checkout/session')->unsRegisterCustomerFirstTime();
} ?>

<?php
if (Mage::getSingleton('cms/page')->getIdentifier() == 'subscribe-scusssfully') {
    ?>
    <script type="text/javascript">
        if (window.promotionData !== undefined) {
            if (typeof(sessionStorage.newNewsletter) !== 'undefined') {
                var gender = sessionStorage.newsLettergender;
                dataLayer.push({
                    'pageType': 'Home',
                    'pageCategory': 'No Category',
                    'userId': window.promotionData.userId,
                    'userType': window.promotionData.userType,
                    'loggedInStatus': window.promotionData.loggedInStatus,
                    'storeCountry': window.promotionData.storeCountry,
                    'storeLanguage': window.promotionData.storeLanguage,
                    'currencyCode': window.promotionData.currency_code,
                    'event': 'customEvent',
                    'eventCategory': 'User Engagement',
                    'eventAction': 'Micro Conversion',
                    'eventLabel': 'Newsletter Subscription Successful',
                    'newsletterGender': gender
                });
                sessionStorage.removeItem("newNewsletter");
                sessionStorage.removeItem("newsLettergender");
            }
        }
    </script>
    <?php
    Mage::getSingleton('checkout/session')->unsRegisterCustomerFirstTime();
}