<!-- 4 ways to choose option -->
	<!-- 1 - item attribute default -->
	<!-- 2 - item attribute image -->
	<!-- 3 custom attribute default image -->
	<!-- 4 custom user  -->
<?php
function dealWithSpecialChars($str)
{
	$str = str_replace("&", " and ", $str);
	$str = str_replace('"', "", $str);
	$str = str_replace("'", "", $str);
	$str = str_replace(",", "", $str);
	return trim(strip_tags($str));
}
function checkAndSetData($data, $isImage = false, $restrictSubstr=true)
{
	if(!isset($data) || empty($data)) {
		if(!$isImage)
			$data = "-";
		else
			$data = $this->getSkinUrl('images/no-img.png');

	}
	//clean data now
	$data = dealWithSpecialChars($data);
	if($restrictSubstr) $data = substr($data, 0, 28);
	return $data;
}
?>
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<?php $value = $this->getValue(); ?>
<style type="text/css">
	.heading-widget {
		font-family:'Gotham Book','Montserrat',<?php echo $value['header_font_family']?> !important;
		font-size: <?php echo $value['header_font_size']?>px !important;
		<?php echo (isset($value['header_font_italic']) &&($value['header_font_italic'] == '1')) ? 'font-style:italic !important;' : ''?>
		<?php echo (isset($value['header_font_bold']) && ($value['header_font_bold'] == '1')) ? 'font-weight:bold !important;' : ''?>
	}
	
	.row-widget {
		font-family:'Gotham Book','Montserrat',<?php echo $value['row_font_family']?> !important;
		font-size: <?php echo $value['row_font_size']?>px !important;
		<?php echo (isset($value['row_font_italic']) and $value['row_font_italic'] == '1') ? 'font-style:italic !important;' : ''?>
		<?php echo (isset($value['row_font_bold']) and $value['row_font_bold'] == '1') ? 'font-weight:bold !important;' : ''?>
	}
</style>
<table id="table" class="items" cellspacing="0">
	<thead>
		<tr>
			<?php $i = 0;?>
			<?php foreach($this->getColumn() as $_column):?>
				<th style="width:<?php echo $_column['width']?>px;" class="heading-widget header <?php echo $_column['option']?><?php if($i==0) echo ' first'?>"><?php echo checkAndSetData($_column['title'])?></th>
				<?php $i++;?>
			<?php endforeach ?>
		</tr> 
	</thead> 
	<tbody>
		<?php $j = 0;?>
		<?php foreach($this->getItems() as $item):?>
			<?php if(empty($item) || empty($this->getColumn()) || empty($item->getData('name'))) continue;?>
			<tr class="<?php if($j%2==0) echo 'even'; else echo 'odd'; ?>">
				<?php foreach($this->getColumn() as $_column): ?>
					<?php if(empty($_column['option'])) continue;?>
					<?php if($_column['option'] == 'position'):?>
					<td style="width:<?php echo $_column['width']?>px;" class="row-widget num"><?php echo $j?></td>
					<?php elseif($_column['option'] == 'name'):?>
						<!-- td>CandS CL PREMIUM HEADWEARAAAA</td -->
					<td style="width:<?php echo $_column['width']?>px;" class="row-widget"><?php echo checkAndSetData($item->getData('name')); ?>
			<table class="tbl-product-options" border="0" width="100%"><!-- Product Options added on First TD -->
			<?php foreach($item->getOptions() as $option):?>
				<?php
				if(empty($option->getValue())) continue;
				?>
				<tr class="<?php if($j % 2):?>odd<?php else:?>even<?php endif;?>">
					<td colspan="<?php echo sizeof($this->getColumn())?>"><strong><?php echo checkAndSetData($option->getLabel())?></strong> :<?php echo checkAndSetData($option->getValue())?></td>
				</tr>
			<?php endforeach;?></table>
					</td>
					<?php elseif($_column['option'] == 'ves_custom'):?>
						<td>TEST1</td>
					<?php /*<td style="width:<?php echo $_column['width']?>px;" class="row-widget <?php echo $_column['option'] ?>"><?php echo $item->getData($_column['custom']) ?></td>*/?>
					<?php else: ?>
						<?php if($_column['option_choose'] == VES_AdvancedPdfProcessor_Model_Source_Widget_Optiontype::OPTION_TEXT):?>
							<?php if(strpos($_column['option'], 'ves') !== false):?>
								<td>TEST2</td>
								<?php /*?><td style="width:<?php echo $_column['width']?>px;" class="row-widget <?php echo $_column['option'] ?>"><?php echo checkAndSetData($item->getProduct()->getData(str_replace('ves_','',$_column['option']))); ?></td><?php*/?>
							<?php else:?>
								<td>TEST3</td>
								<?php /*?><td style="width:<?php echo $_column['width']?>px;" class="row-widget <?php echo $_column['option'] ?>"><?php echo checkAndSetData($item->getData($_column['option'])); ?></td><?php */?>
							<?php endif ?>
						<?php elseif($_column['option_choose'] == VES_AdvancedPdfProcessor_Model_Source_Widget_Optiontype::OPTION_IMAGE):?>
							<td>TEST4</td>
						<?php /*?><td style="width:<?php echo $_column['width']?>px;" class="row-widget <?php echo $_column['option'] ?>"><img alt="<?php echo $_column['option'] ?>" width="<?php echo $_column['option_width']?>" height="<?php echo $_column['option_height']?>" src="<?php echo checkAndSetData($item->getProduct()->getData(str_replace('ves_','',$_column['option'])), true); ?>" /></td><?php */?>
						<?php endif ?>
					<?php endif ?>
					<?php //if($j==5){die();}?>
				<?php endforeach ?>
			</tr>
			<?php /*if($item->getSubItems()):?>
			<?php foreach ($item->getSubItems() as $bundle):?>
				<?php
				if(empty($bundle->getValue())) continue;
				?>
				<tr class="<?php if($j%2==0) echo 'even'; else echo 'odd'; ?>">
					<?php foreach($this->getColumn() as $_column): ?>
						<?php if($_column['option'] == 'name'):?>
							<td style="width:<?php echo $_column['width']?>px;" class="row-widget">
								<div style="margin-left:20px;">
									<strong><?php echo $bundle->getLabel() ?></strong>
									<div class="product-options">
										<?php echo $bundle->getValue() ?>
									</div>
								</div>
							</td>
						<?php elseif($_column['option'] == 'ves_custom'):?>
						<td style="width:<?php echo $_column['width']?>px;" class="row-widget <?php echo $_column['option'] ?>"><?php echo $bundle->getData($_column['custom']) ?></td>
						<?php else: ?>
							<?php if($_column['option_choose'] == VES_AdvancedPdfProcessor_Model_Source_Widget_Optiontype::OPTION_TEXT):?>
								<?php if(strpos($_column['option'], 'ves') !== false):?>
									<td style="width:<?php echo $_column['width']?>px;" class="row-widget <?php echo $_column['option'] ?>"><?php echo checkAndSetData($bundle->getProduct()->getData(str_replace('ves_','',$_column['option']))); ?></td>
								<?php else:?>
									<td style="width:<?php echo $_column['width']?>px;" class="row-widget <?php echo $_column['option'] ?>"><?php echo checkAndSetData($bundle->getData($_column['option'])); ?></td>
								<?php endif ?>
							<?php elseif($_column['option_choose'] == VES_AdvancedPdfProcessor_Model_Source_Widget_Optiontype::OPTION_IMAGE):?>
							<td style="width:<?php echo $_column['width']?>px;" class="row-widget <?php echo $_column['option'] ?>"><img alt="<?php echo $_column['option'] ?>" width="<?php echo $_column['option_width']?>" height="<?php echo $_column['option_height']?>" src="<?php echo checkAndSetData($bundle->getProduct()->getData(str_replace('ves_','',$_column['option'])), true) ?>" /></td>
							<?php endif ?>
						<?php endif ?>
					<?php endforeach ?>
				</tr>
			<?php endforeach ?>
			<?php endif*/ ?>
		<?php $j++; if($j==6) break; ?>
		<?php endforeach ?>
	</tbody>
</table>