<?php
/**
 * Created by PhpStorm.
 * User: vitalij
 * Date: 25.05.17
 * Time: 17:16
 */
$html="";
$order_id = $this->getRequest()->getParam('order_id');
$shipment_id = $this->getRequest()->getParam('shipment_id', NULL);
$type = $this->getRequest()->getParam('type');



$AccessLicenseNumber = Mage::getStoreConfig('upslabel/credentials/accesslicensenumber');
$UserId = Mage::getStoreConfig('upslabel/credentials/userid');
$Password = Mage::getStoreConfig('upslabel/credentials/password');
$shipperNumber = Mage::getStoreConfig('upslabel/credentials/shippernumber');

$collection = Mage::getModel('upslabel/upslabel');
$colls = $collection->getCollection()->addFieldToFilter('shipment_id', $shipment_id)->addFieldToFilter('type', $type);
if (!empty($colls)) {
    $shipm = Mage::getModel('sales/order_shipment')->load($shipment_id);
    $tracks = $shipm->getAllTracks();
    foreach ($colls AS $v) {
        $coll = $v;

        $lbl = Mage::getModel('upslabel/ups');

        $lbl->setCredentials($AccessLicenseNumber, $UserId, $Password, $shipperNumber);
        $lbl->packagingReferenceNumberCode = Mage::getStoreConfig('upslabel/packaging/packagingreferencenumbercode');
        $lbl->testing = Mage::getStoreConfig('upslabel/testmode/testing');
        

        $result = $lbl->deleteLabel($coll['shipmentidentificationnumber']);
        if (!is_array($result)) {
            if(file_exists(Mage::getBaseDir('media') . '/upslabel/label/' . $coll['labelname'])) {
                unlink(Mage::getBaseDir('media') . '/upslabel/label/' . $coll['labelname']);
            }
            if(file_exists(Mage::getBaseDir('media') . '/upslabel/label/' . $coll['trackingnumber'] . '.html')){
                unlink(Mage::getBaseDir('media') . '/upslabel/label/' . $coll['trackingnumber'] . '.html');
            }
            if(file_exists(Mage::getBaseDir('media') . '/upslabel/label/' . "HVR" . $coll['shipmentidentificationnumber'] . ".html")){
                unlink(Mage::getBaseDir('media') . '/upslabel/label/' . "HVR" . $coll['shipmentidentificationnumber'] . ".html");
            }
            if(file_exists(Mage::getBaseDir('media') . '/upslabel/inter_pdf/' . $coll['trackingnumber'] . ".pdf")){
                unlink(Mage::getBaseDir('media') . '/upslabel/inter_pdf/' . $coll['trackingnumber'] . ".pdf");
            }
            $collection->setId($coll->getId())->delete();
            foreach ($tracks as $track) {
                if ($track->getNumber() == $coll['trackingnumber']) {
                    $track->delete();
                }
            }
        } else {
            return 'Error';
            /*print_r($result);*/
        }
    }
}
$html .= '<br />Removal was successful. Back to <a href="' . $this->getUrl('adminhtml/sales_order/view/order_id/' . $order_id) . '">order</a>.';
if($shipment_id !== NULL) {
    if ($type == 'shipment') {
        $html .= ' Back to <a href="' . $this->getUrl('adminhtml/sales_order_shipment/view/shipment_id/' . $shipment_id) . '">shipment</a>.';
    } else {
        $html .= ' Back to <a href="' . $this->getUrl('adminhtml/sales_order_creditmemo/view/creditmemo_id/' . $shipment_id) . '">credit memo</a>.';
    }
}
$html .= ' Or <a href="' . $this->getUrl('adminhtml/upslabel_upslabel/intermediate/order_id/' . $order_id . ($shipment_id!==NULL?'/shipment_id/' . $shipment_id:'') . '/type/'.$type) . '"> Create new</a>';


echo $html;