<?php /* @var $this Progos_Page_Block_Page_Html_Header */ ?>
<?php
$storeCategories = $this->getCategoryCollection();
$genders = array( "WOMEN" , "MEN" , "KIDS" ); 
$arabicGender = array( "WOMEN" => "النساء" , "MEN" => "الرجال" , "KIDS"=> "الاطفال" );
$storeId = Mage::app()->getStore()->getId();
?>
<div id="navigation" class="slide-in-on-top">
    <a href="#navigation" data-type="close" data-parent=".wrapper"
   data-remove-to-parent="slide-in-on-top-open" class="site--breadcrumb">
        <span></span>
        <span></span>
        <span></span>
    </a>
    <!-- Dynamic the Main Tab as per gender Start -->
    <div class="overflow">
        <div class="main-cat clearfix">
            <ul>
                <?php 
                    $genderCount = 1;
                    foreach( $genders as $gender ){ ?>
                        <li class="<?php echo (($genderCount == 1 )?'active':'') ?>">
                            <a href="#grand-parent-<?php echo $genderCount ; ?>" data-hide="#grand-parent-<?php echo $genderCount ; ?>"><?php echo $this->__($gender); ?></a>
                        </li>
               <?php $genderCount++; 
                    } ?>
            </ul>
        </div>
        <nav id="nav">
          <?php 
                $genderCount = 1;
                foreach ($genders as $gender){ ?>
                 <ul id="grand-parent-<?php echo $genderCount;?>" >
                    <li class="level0">
                        <a href="<?php echo Mage::getBaseUrl() .strtolower($gender);?>/" >
                            <span><?php echo $this->__($gender."'s home page"); ?></span>
                        </a>
                    </li>
                    <?php foreach( $storeCategories as $category ){ 
                            $children = $category->getChildrenCategories(); 
                            if( !$children )
                                $children = $category->getChildren();
                            if( $category->getName() == 'New Arrivals' || trim($category->getName()) == "ÙˆØµÙ„Ù†Ø§ Ø­Ø¯ÙŠØ«Ø§Ù‹" ){
                                foreach ($children as $child) { 
                                    if( strtolower($child->getName()) == strtolower($gender) || $arabicGender[$gender] == $this->__(trim($child->getName())) ){
                                        echo($this->generateParentLevel($child, $category->getName()));
                                    }
                                }       
                            }else if( strtolower($category->getName()) ==  strtolower($gender) || $arabicGender[$gender] == $this->__(trim($category->getName())) ){
                                foreach ($children as $child) { 
                                    echo($this->generateParentLevel($child));
                                } 
                            }else{
                                continue;
                            }
                          } 
                        $menuTitle = "Sale";
                        $url =  strtolower($gender).'-'.strtolower($menuTitle).'/';
                        ?>
                        <li class="level0 sale">
                            <a href="<?php echo Mage::getBaseUrl();?>sale/<?php echo $url; ?>">
                                <span><?php echo $this->__($menuTitle); ?></span>
                            </a>
                        </li>
                        <li class="level0 parent">
                            <a href="javascript:void(0);"><?php echo $this->__('Top Brands')?></a>
                           <?php 
                            $identifier = "mobile-mega-menu-desktop-".strtolower($gender);
                            echo $this->getLayout()->createBlock('cms/block')->setStoreId($storeId)->setBlockId($identifier)->toHtml();
                           ?>
                        </li>
                 </ul>
          <?php $genderCount++; 
                } ?>
        </nav>
    </div>
    <!-- Dynamic the Main Tab as per gender End -->
</div>