<?php //Template used by block: Kartaca_Pos_Block_Payment_Form_Pos ?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode(); ?>





    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <?php 
            $desciptionField = Mage::getStoreConfig('payment/telrtransparent/appMethodDescription'); 

            if (isset($desciptionField) && $desciptionField!="") {
                echo "<li style='display: block;'><p>".$desciptionField."</p></li>";
            }
        ?>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required"></span></label><br />
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>"  onblur="check_function()" class="input-text validate-cc-number validate-cc-type" value="" />
            </div>
        </li>
        <li><div id="telrtransparent_cc_logos"></div></li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required"></span></label><br />
                <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month required-entry validate-cc-exp">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                </div>
                <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                </div>
            </div>
        </li>
        <li style="display: none;">
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required"></span></label><br />
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                    <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $this->__($_typeName) ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </li>
        <?php if($this->hasVerification()): ?>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required"></span></label><br />
                <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="cvv required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" /></div>
                &nbsp;
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>
        <?php endif; ?>
    </ul>
</fieldset>
<?php
if(Mage::getStoreConfig("marketplace/binno/binnoenable")):
    ?>
    <script>
        function check_function() {
            var value_of_card = jQuery('input.validate-cc-type').val();
            var bin_no_card = value_of_card.slice(0, 6);
            var url = "<?php echo $this->getUrl('marketplace/order/check_binno', array('_secure'=>true)) ?>";

            if (/^\d{6}$/.test(bin_no_card)) {
                new Ajax.Request(url,
                    {
                        method:'post',
                        parameters: {"bin_no":bin_no_card},
                        onComplete:function(request, json) {
                            console.log(request.responseText);
                            if(request.responseText == 1){
                                if(jQuery('input#coupon-code').val() !== "BIN.20") {
                                    jQuery('input#coupon-code').val("BIN.20");
                                    jQuery("button#coupon-apply").trigger("click");
                                }
                            }
                            else if(request.responseText == 0){
                                if(jQuery('input#coupon-code').val() == "BIN.20") {
                                    jQuery('input#coupon-code').val("");
                                    jQuery("button#coupon-cancel").trigger("click");
                                }
                            }
                        }
                    });
            }
        }
    </script>
    <?php
endif; ?>